(function(U,P){var d=U.PIE||(U.PIE={});d.wa=function(b){var a,e,c,f,g=arguments;a=1;for(e=g.length;a<e;a++){f=g[a];for(c in f)if(f.hasOwnProperty(c))b[c]=f[c]}return b};d.wa(d,{k:"-pie-",Ia:"Pie",ea:"pie_",Vc:{TD:1,TH:1},gc:{TABLE:1,THEAD:1,TBODY:1,TFOOT:1,TR:1,INPUT:1,TEXTAREA:1,SELECT:1,OPTION:1,IMG:1,HR:1},xb:{A:1,INPUT:1,TEXTAREA:1,SELECT:1,BUTTON:1},vd:{submit:1,button:1,reset:1},ua:function(){}});try{P.execCommand("BackgroundImageCache",false,true)}catch(ca){}(function(){for(var b=4,a=P.createElement("div"),
e=a.getElementsByTagName("i");a.innerHTML="<!--[if gt IE "+ ++b+"]><i></i><![endif]--\>",e[0];);d.Va=b;if(b===6)d.k=d.k.replace(/^-/,"");d.P=P.documentMode||d.Va;a.innerHTML='<v:shape adj="1"/>';b=a.firstChild;b.style.behavior="url(#default#VML)";d.Gb=typeof b.adj==="object"})();(function(){var b=0,a={};d.na={Sa:function(e){return e&&e._pieId||(e._pieId="_"+b++)},ad:function(e,c,f){var g=a[e],h,i;if(g)Object.prototype.toString.call(g)==="[object Array]"?g.push([c,f]):c.call(f,g);else{i=a[e]=[[c,f]];
h=new Image;h.onload=function(){g=a[e]={g:h.width,f:h.height};for(var j=0,m=i.length;j<m;j++)i[j][0].call(i[j][1],g);h.onload=null};h.src=e}}}})();d.Ea={qc:function(b,a,e,c){function f(){m=h>=90&&h<270?a:0;n=h<180?e:0;l=a-m;o=e-n}function g(){for(;h<0;)h+=360;h%=360}var h=c.pa;c=c.Ua;var i,j,m,n,l,o,t,u;if(c){c=c.coords(b,a,e);i=c.x;j=c.y}if(h){h=h.jc();g();f();if(!c){i=m;j=n}c=d.Ea.Ic(i,j,h,l,o);b=c[0];c=c[1]}else if(c){b=a-i;c=e-j}else{i=j=b=0;c=e}t=b-i;u=c-j;if(h===void 0){h=!t?u<0?90:270:!u?t<
0?180:0:-Math.atan2(u,t)/Math.PI*180;g();f()}return{pa:h,Sc:i,Tc:j,lc:b,mc:c,Ad:m,Bd:n,sd:l,td:o,pd:t,qd:u,Dc:d.Ea.kc(i,j,b,c)}},Ic:function(b,a,e,c,f){if(e===0||e===180)return[c,a];else if(e===90||e===270)return[b,f];else{e=Math.tan(-e*Math.PI/180);b=e*b-a;a=-1/e;c=a*c-f;f=a-e;return[(c-b)/f,(e*c-a*b)/f]}},kc:function(b,a,e,c){b=e-b;a=c-a;return Math.abs(b===0?a:a===0?b:Math.sqrt(b*b+a*a))}};d.L=function(){this.ab=[];this.Bb={}};d.L.prototype={J:function(b){var a=d.na.Sa(b),e=this.Bb,c=this.ab;if(!(a in
e)){e[a]=c.length;c.push(b)}},Z:function(b){b=d.na.Sa(b);var a=this.Bb;if(b&&b in a){delete this.ab[a[b]];delete a[b]}},W:function(){for(var b=this.ab,a=b.length;a--;)b[a]&&b[a]()}};d.ga=new d.L;d.ga.Nc=function(){var b=this;if(!b.Oc){setInterval(function(){b.W()},250);b.Oc=1}};(function(){function b(){d.G.W();U.detachEvent("onunload",b);U.PIE=null}d.G=new d.L;U.attachEvent("onunload",b);d.G.Oa=function(a,e,c){a.attachEvent(e,c);this.J(function(){a.detachEvent(e,c)})}})();d.ja=new d.L;d.G.Oa(U,"onresize",
function(){d.ja.W()});(function(){function b(){d.Ha.W()}d.Ha=new d.L;d.G.Oa(U,"onscroll",b);d.ja.J(b)})();d.Ga=new d.L;d.G.Oa(P,"onmouseup",function(){d.Ga.W()});d.jd=function(){function b(j){this.F=j}var a=P.createElement("length-calc"),e=P.body||P.documentElement,c=a.style,f={},g=["mm","cm","in","pt","pc"],h=g.length,i={};c.position="absolute";c.top=c.left="-9999px";for(e.appendChild(a);h--;){c.width="100"+g[h];f[g[h]]=a.offsetWidth/100}e.removeChild(a);c.width="1em";b.prototype={db:/(px|em|ex|mm|cm|in|pt|pc|%)$/,
tc:function(){var j=this.Fc;if(j===void 0)j=this.Fc=parseFloat(this.F);return j},Ta:function(){var j=this.Wc;if(!j)j=this.Wc=(j=this.F.match(this.db))&&j[0]||"px";return j},c:function(j,m){var n=this.tc(),l=this.Ta();switch(l){case "px":return n;case "%":return n*(typeof m==="function"?m():m)/100;case "em":return n*this.Ra(j);case "ex":return n*this.Ra(j)/2;default:return n*f[l]}},Ra:function(j){var m=j.currentStyle.fontSize,n,l;if(m.indexOf("px")>0)return parseFloat(m);else if(j.tagName in d.gc){l=
this;n=j.parentNode;return d.h(m).c(n,function(){return l.Ra(n)})}else{j.appendChild(a);m=a.offsetWidth;a.parentNode===j&&j.removeChild(a);return m}}};b.zd=function(j){return j/f.pt};d.h=function(j){return i[j]||(i[j]=new b(j))};return b}();d.ca=function(){function b(f){this.D=f}var a=d.h("50%"),e={top:1,center:1,bottom:1},c={left:1,center:1,right:1};b.prototype={uc:function(){if(!this.pb){var f=this.D,g=f.length,h=d.n,i=h.Ka,j=d.h("0");i=i.ha;j=["left",j,"top",j];if(g===1){f.push(new h.Ja(i,"center"));
g++}if(g===2){i&(f[0].e|f[1].e)&&f[0].a in e&&f[1].a in c&&f.push(f.shift());if(f[0].e&i)if(f[0].a==="center")j[1]=a;else j[0]=f[0].a;else if(f[0].B())j[1]=d.h(f[0].a);if(f[1].e&i)if(f[1].a==="center")j[3]=a;else j[2]=f[1].a;else if(f[1].B())j[3]=d.h(f[1].a)}this.pb=j}return this.pb},coords:function(f,g,h){var i=this.uc(),j=i[1].c(f,g);f=i[3].c(f,h);return{x:i[0]==="right"?g-j:j,y:i[2]==="bottom"?h-f:f}}};return b}();d.da=function(){function b(a,e){this.g=a;this.f=e}b.prototype={c:function(a,e,c,
f,g){var h=this.g,i=this.f,j=e/c;f=f/g;if(h==="contain"){h=f>j?e:c*f;i=f>j?e/f:c}else if(h==="cover"){h=f<j?e:c*f;i=f<j?e/f:c}else if(h==="auto"){i=i==="auto"?g:i.c(a,c);h=i*f}else{h=h.c(a,e);i=i==="auto"?h/f:i.c(a,c)}return{g:h,f:i}}};b.Mb=new b("auto","auto");return b}();d.Kb=function(){function b(a){this.F=a}b.prototype={db:/[a-z]+$/i,Ta:function(){return this.$b||(this.$b=this.F.match(this.db)[0].toLowerCase())},jc:function(){var a=this.Vb,e;if(a===undefined){a=this.Ta();e=parseFloat(this.F,10);
a=this.Vb=a==="deg"?e:a==="rad"?e/Math.PI*180:a==="grad"?e/400*360:a==="turn"?e*360:0}return a}};return b}();d.Lb=function(){function b(c,f,g){if(g<0)g+=1;else if(g>1)g-=1;return 255*(6*g<1?c+(f-c)*g*6:2*g<1?f:3*g<2?c+(f-c)*(2/3-g)*6:c)}function a(c){this.F=c}var e={};a.Mc=/\s*rgba?\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*(,\s*(\d+|\d*\.\d+))?\s*\)\s*/;a.yc=/\s*hsla?\(\s*(\d*\.?\d+)\s*,\s*(\d{1,3})%\s*,\s*(\d{1,3})%\s*(,\s*(\d+|\d*\.\d+))?\s*\)\s*/;a.Ya={aliceblue:"F0F8FF",antiquewhite:"FAEBD7",
aqua:"0FF",aquamarine:"7FFFD4",azure:"F0FFFF",beige:"F5F5DC",bisque:"FFE4C4",black:"000",blanchedalmond:"FFEBCD",blue:"00F",blueviolet:"8A2BE2",brown:"A52A2A",burlywood:"DEB887",cadetblue:"5F9EA0",chartreuse:"7FFF00",chocolate:"D2691E",coral:"FF7F50",cornflowerblue:"6495ED",cornsilk:"FFF8DC",crimson:"DC143C",cyan:"0FF",darkblue:"00008B",darkcyan:"008B8B",darkgoldenrod:"B8860B",darkgray:"A9A9A9",darkgreen:"006400",darkkhaki:"BDB76B",darkmagenta:"8B008B",darkolivegreen:"556B2F",darkorange:"FF8C00",
darkorchid:"9932CC",darkred:"8B0000",darksalmon:"E9967A",darkseagreen:"8FBC8F",darkslateblue:"483D8B",darkslategray:"2F4F4F",darkturquoise:"00CED1",darkviolet:"9400D3",deeppink:"FF1493",deepskyblue:"00BFFF",dimgray:"696969",dodgerblue:"1E90FF",firebrick:"B22222",floralwhite:"FFFAF0",forestgreen:"228B22",fuchsia:"F0F",gainsboro:"DCDCDC",ghostwhite:"F8F8FF",gold:"FFD700",goldenrod:"DAA520",gray:"808080",green:"008000",greenyellow:"ADFF2F",honeydew:"F0FFF0",hotpink:"FF69B4",indianred:"CD5C5C",indigo:"4B0082",
ivory:"FFFFF0",khaki:"F0E68C",lavender:"E6E6FA",lavenderblush:"FFF0F5",lawngreen:"7CFC00",lemonchiffon:"FFFACD",lightblue:"ADD8E6",lightcoral:"F08080",lightcyan:"E0FFFF",lightgoldenrodyellow:"FAFAD2",lightgreen:"90EE90",lightgrey:"D3D3D3",lightpink:"FFB6C1",lightsalmon:"FFA07A",lightseagreen:"20B2AA",lightskyblue:"87CEFA",lightslategray:"789",lightsteelblue:"B0C4DE",lightyellow:"FFFFE0",lime:"0F0",limegreen:"32CD32",linen:"FAF0E6",magenta:"F0F",maroon:"800000",mediumauqamarine:"66CDAA",mediumblue:"0000CD",
mediumorchid:"BA55D3",mediumpurple:"9370D8",mediumseagreen:"3CB371",mediumslateblue:"7B68EE",mediumspringgreen:"00FA9A",mediumturquoise:"48D1CC",mediumvioletred:"C71585",midnightblue:"191970",mintcream:"F5FFFA",mistyrose:"FFE4E1",moccasin:"FFE4B5",navajowhite:"FFDEAD",navy:"000080",oldlace:"FDF5E6",olive:"808000",olivedrab:"688E23",orange:"FFA500",orangered:"FF4500",orchid:"DA70D6",palegoldenrod:"EEE8AA",palegreen:"98FB98",paleturquoise:"AFEEEE",palevioletred:"D87093",papayawhip:"FFEFD5",peachpuff:"FFDAB9",
peru:"CD853F",pink:"FFC0CB",plum:"DDA0DD",powderblue:"B0E0E6",purple:"800080",red:"F00",rosybrown:"BC8F8F",royalblue:"4169E1",saddlebrown:"8B4513",salmon:"FA8072",sandybrown:"F4A460",seagreen:"2E8B57",seashell:"FFF5EE",sienna:"A0522D",silver:"C0C0C0",skyblue:"87CEEB",slateblue:"6A5ACD",slategray:"708090",snow:"FFFAFA",springgreen:"00FF7F",steelblue:"4682B4",tan:"D2B48C",teal:"008080",thistle:"D8BFD8",tomato:"FF6347",turquoise:"40E0D0",violet:"EE82EE",wheat:"F5DEB3",white:"FFF",whitesmoke:"F5F5F5",
yellow:"FF0",yellowgreen:"9ACD32"};a.prototype={parse:function(){if(!this.Ma){var c=this.F,f;if(f=c.match(a.Mc)){c=this.Fb(+f[1],+f[2],+f[3]);f=f[5]?+f[5]:1}else if(f=c.match(a.yc)){var g=f[1],h=f[2],i=f[3],j,m;c=Math.round;h/=100;i/=100;if(h){h=i<=0.5?i*(h+1):i+h-i*h;j=i*2-h;g=g%360/360;i=b(j,h,g+1/3);m=b(j,h,g);g=b(j,h,g-1/3)}else i=m=g=i*255;c={Lc:c(i),nc:c(m),cc:c(g)};c=this.Fb(c.Lc,c.nc,c.cc);f=f[5]?+f[5]:1}else{if(a.Ya.hasOwnProperty(f=c.toLowerCase()))c="#"+a.Ya[f];f=c==="transparent"?0:1}this.Ma=
c;this.Ub=f}},Fb:function(c,f,g){return"#"+(c<16?"0":"")+c.toString(16)+(f<16?"0":"")+f.toString(16)+(g<16?"0":"")+g.toString(16)},tb:function(c){this.parse();return this.Ma==="currentColor"?d.N(c.currentStyle.color).tb(c):this.Ma},ac:function(){this.parse();return this.Ub}};d.N=function(c){return e[c]||(e[c]=new a(c))};return a}();d.n=function(){function b(e){this.ta=e;this.ch=0;this.D=[];this.Y=0}var a=b.Ka={ba:1,jb:2,i:4,Nb:8,lb:16,ha:32,p:64,R:128,Fa:256,ka:512,Tb:1024,URL:2048};b.Ja=function(e,
c){this.e=e;this.a=c};b.Ja.prototype={Xa:function(){return this.e&a.p||this.e&a.R&&this.a==="0"},B:function(){return this.Xa()||this.e&a.ka}};b.prototype={$c:/\s/,Gc:/^[\+\-]?(\d*\.)?\d+/,url:/^url\(\s*("([^"]*)"|'([^']*)'|([!#$%&*-~]*))\s*\)/i,zb:/^\-?[_a-z][\w-]*/i,Uc:/^("([^"]*)"|'([^']*)')/,wc:/^#([\da-f]{6}|[\da-f]{3})/i,Xc:{px:a.p,em:a.p,ex:a.p,mm:a.p,cm:a.p,"in":a.p,pt:a.p,pc:a.p,deg:a.ba,rad:a.ba,grad:a.ba},ic:{rgb:1,rgba:1,hsl:1,hsla:1},next:function(e){function c(o,t){o=new b.Ja(o,t);if(!e){m.D.push(o);
m.Y++}return o}function f(){m.Y++;return null}var g,h,i,j,m=this;if(this.Y<this.D.length)return this.D[this.Y++];for(;this.$c.test(this.ta.charAt(this.ch));)this.ch++;if(this.ch>=this.ta.length)return f();h=this.ch;g=this.ta.substring(this.ch);i=g.charAt(0);switch(i){case "#":if(j=g.match(this.wc)){this.ch+=j[0].length;return c(a.i,j[0])}break;case '"':case "'":if(j=g.match(this.Uc)){this.ch+=j[0].length;return c(a.Tb,j[2]||j[3]||"")}break;case "/":case ",":this.ch++;return c(a.Fa,i);case "u":if(j=
g.match(this.url)){this.ch+=j[0].length;return c(a.URL,j[2]||j[3]||j[4]||"")}}if(j=g.match(this.Gc)){i=j[0];this.ch+=i.length;if(g.charAt(i.length)==="%"){this.ch++;return c(a.ka,i+"%")}if(j=g.substring(i.length).match(this.zb)){i+=j[0];this.ch+=j[0].length;return c(this.Xc[j[0].toLowerCase()]||a.Nb,i)}return c(a.R,i)}if(j=g.match(this.zb)){i=j[0];this.ch+=i.length;if(i.toLowerCase()in d.Lb.Ya||i==="currentColor"||i==="transparent")return c(a.i,i);if(g.charAt(i.length)==="("){this.ch++;if(i.toLowerCase()in
this.ic){g=function(o){return o&&o.e&a.R};j=function(o){return o&&o.e&(a.R|a.ka)};var n=function(o,t){return o&&o.a===t},l=function(){return m.next(1)};if((i.charAt(0)==="r"?j(l()):g(l()))&&n(l(),",")&&j(l())&&n(l(),",")&&j(l())&&(i==="rgb"||i==="hsa"||n(l(),",")&&g(l()))&&n(l(),")"))return c(a.i,this.ta.substring(h,this.ch));return f()}return c(a.lb,i)}return c(a.ha,i)}this.ch++;return c(a.jb,i)},j:function(){return this.D[this.Y-- -2]},all:function(){for(;this.next(););return this.D},$:function(e,
c){for(var f=[],g,h;g=this.next();){if(e(g)){h=true;this.j();break}f.push(g)}return c&&!h?null:f}};return b}();d.ib=function(b){this.d=b};d.ib.prototype={H:0,Jc:function(){var b=this.Na,a;return!b||(a=this.X())&&(b.x!==a.x||b.y!==a.y)},Qc:function(){var b=this.Na,a;return!b||(a=this.X())&&(b.g!==a.g||b.f!==a.f)},yb:function(){var b=this.d,a=b.getBoundingClientRect(),e=d.P===9,c=d.Va===7,f=a.right-a.left;return{x:a.left,y:a.top,g:e||c?b.offsetWidth:f,f:e||c?b.offsetHeight:a.bottom-a.top,xd:c&&f?b.offsetWidth/
f:1}},X:function(){return this.H?this.oa||(this.oa=this.yb()):this.yb()},vc:function(){return!!this.Na},va:function(){++this.H},Da:function(){if(!--this.H){if(this.oa)this.Na=this.oa;this.oa=null}}};(function(){function b(a){var e=d.na.Sa(a);return function(){if(this.H){var c=this.ob||(this.ob={});return e in c?c[e]:(c[e]=a.call(this))}else return a.call(this)}}d.m={H:0,xa:function(a){function e(c){this.d=c;this.nb=this.O()}d.wa(e.prototype,d.m,a);e.Zb={};return e},v:function(){var a=this.O(),e=this.constructor.Zb;
return a?a in e?e[a]:(e[a]=this.za(a)):null},O:b(function(){var a=this.d,e=this.constructor,c=a.style;a=a.currentStyle;var f=this.Pa,g=this.cb,h=e.Xb||(e.Xb=d.k+f);e=e.Yb||(e.Yb=d.Ia+g.charAt(0).toUpperCase()+g.substring(1));return c[e]||a.getAttribute(h)||c[g]||a.getAttribute(f)}),z:b(function(){return!!this.v()}),sb:b(function(){var a=this.O(),e=a!==this.nb;this.nb=a;return e}),V:b,va:function(){++this.H},Da:function(){--this.H||delete this.ob}}})();d.fb=d.m.xa({Pa:d.k+"background",cb:d.Ia+"Background",
bc:{scroll:1,fixed:1,local:1},Ba:{"repeat-x":1,"repeat-y":1,repeat:1,"no-repeat":1},Db:{"padding-box":1,"border-box":1,"content-box":1},Kc:{top:1,right:1,bottom:1,left:1,center:1},Rc:{contain:1,cover:1},Aa:{fa:"backgroundClip",i:"backgroundColor",K:"backgroundImage",ia:"backgroundOrigin",q:"backgroundPosition",s:"backgroundRepeat",ma:"backgroundSize"},za:function(b){function a(r){return r&&r.B()||r.e&m&&r.a in u}function e(r){return r&&(r.B()&&d.h(r.a)||r.a==="auto"&&"auto")}var c=this.d.currentStyle,
f,g,h,i=d.n.Ka,j=i.Fa,m=i.ha,n=i.i,l,o,t=0,u=this.Kc,v,k,p={I:[]};if(this.Qa()){f=new d.n(b);for(h={};g=f.next();){l=g.e;o=g.a;if(!h.w&&l&i.lb&&o==="linear-gradient"){v={Q:[],w:o};for(k={};g=f.next();){l=g.e;o=g.a;if(l&i.jb&&o===")"){k.color&&v.Q.push(k);v.Q.length>1&&d.wa(h,v);break}if(l&n){if(v.pa||v.Ua){g=f.j();if(g.e!==j)break;f.next()}k={color:d.N(o)};g=f.next();if(g.B())k.Cb=d.h(g.a);else f.j()}else if(l&i.ba&&!v.pa&&!k.color&&!v.Q.length)v.pa=new d.Kb(g.a);else if(a(g)&&!v.Ua&&!k.color&&!v.Q.length){f.j();
v.Ua=new d.ca(f.$(function(r){return!a(r)},false))}else if(l&j&&o===","){if(k.color){v.Q.push(k);k={}}}else break}}else if(!h.w&&l&i.URL){h.Ab=o;h.w="image"}else if(a(g)&&!h.T){f.j();h.T=new d.ca(f.$(function(r){return!a(r)},false))}else if(l&m)if(o in this.Ba&&!h.Wa)h.Wa=o;else if(o in this.Db&&!h.ra){h.ra=o;if((g=f.next())&&g.e&m&&g.a in this.Db)h.qa=g.a;else{h.qa=o;f.j()}}else if(o in this.bc&&!h.qb)h.qb=o;else return null;else if(l&n&&!p.color)p.color=d.N(o);else if(l&j&&o==="/"&&!h.sa&&h.T){g=
f.next();if(g.e&m&&g.a in this.Rc)h.sa=new d.da(g.a);else if(g=e(g)){l=e(f.next());if(!l){l=g;f.j()}h.sa=new d.da(g,l)}else return null}else if(l&j&&o===","&&h.w){h.bb=b.substring(t,f.ch-1);t=f.ch;p.I.push(h);h={}}else return null}if(h.w){h.bb=b.substring(t);p.I.push(h)}p.hc=h.qa}else this.Ib(d.P<9?function(){var r=this.Aa,q=c[r.q+"X"],y=c[r.q+"Y"],A=c[r.K],E=c[r.i];if(E!=="transparent")p.color=d.N(E);if(A!=="none")p.I=[{w:"image",Ab:(new d.n(A)).next().a,Wa:c[r.s],T:new d.ca((new d.n(q+" "+y)).all())}]}:
function(){var r=this.Aa,q=/\s*,\s*/,y=c[r.K].split(q),A=c[r.i],E,F,I,K,H,J;if(A!=="transparent")p.color=d.N(A);if((K=y.length)&&y[0]!=="none"){A=c[r.s].split(q);E=c[r.q].split(q);F=c[r.ia].split(q);I=c[r.fa].split(q);r=c[r.ma].split(q);p.I=[];for(q=0;q<K;q++)if((H=y[q])&&H!=="none"){J=r[q].split(" ");p.I.push({bb:H+" "+A[q]+" "+E[q]+" / "+r[q]+" "+F[q]+" "+I[q],w:"image",Ab:(new d.n(H)).next().a,Wa:A[q],T:new d.ca((new d.n(E[q])).all()),ra:F[q],qa:I[q],sa:new d.da(J[0],J[1])})}}});return p.color||
p.I[0]?p:null},Ib:function(b){var a=d.P>8,e=this.Aa,c=this.d.runtimeStyle,f=c[e.K],g=c[e.i],h=c[e.s],i,j,m,n;if(f)c[e.K]="";if(g)c[e.i]="";if(h)c[e.s]="";if(a){i=c[e.fa];j=c[e.ia];n=c[e.q];m=c[e.ma];if(i)c[e.fa]="";if(j)c[e.ia]="";if(n)c[e.q]="";if(m)c[e.ma]=""}b=b.call(this);if(f)c[e.K]=f;if(g)c[e.i]=g;if(h)c[e.s]=h;if(a){if(i)c[e.fa]=i;if(j)c[e.ia]=j;if(n)c[e.q]=n;if(m)c[e.ma]=m}return b},O:d.m.V(function(){return this.Qa()||this.Ib(function(){var b=this.d.currentStyle,a=this.Aa;return b[a.i]+" "+
b[a.K]+" "+b[a.s]+" "+b[a.q+"X"]+" "+b[a.q+"Y"]})}),Qa:d.m.V(function(){var b=this.d;return b.style[this.cb]||b.currentStyle.getAttribute(this.Pa)}),oc:function(b,a,e,c){var f=this.d,g=a.X();a=g.g;g=g.f;if(b!=="border-box")if((e=e.v())&&(e=e.aa)){a-=e.l.c(f)+e.l.c(f);g-=e.t.c(f)+e.b.c(f)}if(b==="content-box")if(b=c.v()){a-=b.l.c(f)+b.l.c(f);g-=b.t.c(f)+b.b.c(f)}return{g:a,f:g}},Cc:function(){var b=0;if(d.Va<7){b=this.d;b=""+(b.style[d.Ia+"PngFix"]||b.currentStyle.getAttribute(d.k+"png-fix"))==="true"}return b},
z:d.m.V(function(){return(this.Qa()||this.Cc())&&!!this.v()})});d.hb=d.m.xa({Pc:["Top","Right","Bottom","Left"],Ec:{thin:"1px",medium:"3px",thick:"5px"},za:function(){var b={},a={},e={},c=false,f=true,g=true,h=true;this.Jb(function(){for(var i=this.d.currentStyle,j=0,m,n,l,o,t,u,v;j<4;j++){l=this.Pc[j];v=l.charAt(0).toLowerCase();m=a[v]=i["border"+l+"Style"];n=i["border"+l+"Color"];l=i["border"+l+"Width"];if(j>0){if(m!==o)g=false;if(n!==t)f=false;if(l!==u)h=false}o=m;t=n;u=l;e[v]=d.N(n);l=b[v]=d.h(a[v]===
"none"?"0":this.Ec[l]||l);if(l.c(this.d)>0)c=true}});return c?{aa:b,Cd:a,nd:e,Fd:h,od:f,Dd:g}:null},O:d.m.V(function(){var b=this.d,a=b.currentStyle,e;b.tagName in d.Vc&&b.offsetParent.currentStyle.borderCollapse==="collapse"||this.Jb(function(){e=a.borderWidth+"|"+a.borderStyle+"|"+a.borderColor});return e}),Jb:function(b){var a=this.d.runtimeStyle,e=a.borderWidth,c=a.borderColor;if(e)a.borderWidth="";if(c)a.borderColor="";b=b.call(this);if(e)a.borderWidth=e;if(c)a.borderColor=c;return b}});d.gb=
d.m.xa({Pa:"border-image",cb:"borderImage",Ba:{stretch:1,round:1,repeat:1,space:1},za:function(b){var a=null,e,c,f,g,h,i,j=0,m=d.n.Ka,n=m.ha,l=m.R,o=m.ka;if(b){e=new d.n(b);a={};for(var t=function(k){return k&&k.e&m.Fa&&k.a==="/"},u=function(k){return k&&k.e&n&&k.a==="fill"},v=function(){g=e.$(function(k){return!(k.e&(l|o))});if(u(e.next())&&!a.fill)a.fill=true;else e.j();if(t(e.next())){j++;h=e.$(function(k){return!k.B()&&!(k.e&n&&k.a==="auto")});if(t(e.next())){j++;i=e.$(function(k){return!k.Xa()})}}else e.j()};b=
e.next();){c=b.e;f=b.a;if(c&(l|o)&&!g){e.j();v()}else if(u(b)&&!a.fill){a.fill=true;v()}else if(c&n&&this.Ba[f]&&!a.repeat){a.repeat={f:f};if(b=e.next())if(b.e&n&&this.Ba[b.a])a.repeat.eb=b.a;else e.j()}else if(c&m.URL&&!a.src)a.src=f;else return null}if(!a.src||!g||g.length<1||g.length>4||h&&h.length>4||j===1&&h.length<1||i&&i.length>4||j===2&&i.length<1)return null;if(!a.repeat)a.repeat={f:"stretch"};if(!a.repeat.eb)a.repeat.eb=a.repeat.f;b=function(k,p){return{t:p(k[0]),r:p(k[1]||k[0]),b:p(k[2]||
k[0]),l:p(k[3]||k[1]||k[0])}};a.slice=b(g,function(k){return d.h(k.e&l?k.a+"px":k.a)});if(h&&h[0])a.aa=b(h,function(k){return k.B()?d.h(k.a):k.a});if(i&&i[0])a.yd=b(i,function(k){return k.Xa()?d.h(k.a):k.a})}return a}});d.mb=d.m.xa({za:function(b){b=new d.n(b);for(var a=[],e;(e=b.next())&&e.B();)a.push(d.h(e.a));return a.length>0&&a.length<5?{t:a[0],r:a[1]||a[0],b:a[2]||a[0],l:a[3]||a[1]||a[0]}:null},O:d.m.V(function(){var b=this.d,a=b.runtimeStyle,e=a.padding;if(e)a.padding="";b=b.currentStyle.padding;
if(e)a.padding=e;return b})});d.la={$a:function(b){function a(e,c,f,g){this.d=e;this.rb=c;this.C=f;this.parent=g}d.wa(a.prototype,d.la,b);return a},Za:function(){return false},Eb:d.ua,Hb:function(){this.z()?this.ub():this.o()},xc:function(){this.d.runtimeStyle.borderColor="transparent"},o:function(){}};d.Qb=d.la.$a({Yc:d.ua,Hb:d.ua,Ed:d.ua,Hc:/^,+|,+$/g,Bc:/,+/g,Ca:function(b,a){(this.La||(this.La=[]))[b]=a||void 0},wb:function(){var b=this.La,a;if(b&&(a=b.join(",").replace(this.Hc,"").replace(this.Bc,
","))!==this.Wb)this.Wb=this.d.runtimeStyle.background=a},o:function(){this.d.runtimeStyle.background="";delete this.La}});d.Ob=d.la.$a({S:1,Za:function(){return this.C.M.sb()},z:function(){var b=this.C;return b.M.z()||b.u.z()},ub:function(){var b=this.C,a=b.M,e=a.v(),c,f,g=0,h,i;if(e){c=[];if(f=e.I)for(;h=f[g++];)if(h.w==="linear-gradient"){i=a.oc(c.ra,this.rb,b.U,b.ya);i=(h.sa||d.da.Mb).c(this.d,i.g,i.f,i.g,i.f);c.push("url(data:image/svg+xml,"+escape(this.rc(h,i.g,i.f))+") "+this.dc(h.T)+" / "+
i.g+"px "+i.f+"px "+(h.qb||"")+" "+(h.ra||"")+" "+(h.qa||""))}else c.push(h.bb);if(e.color)c.push(e.color.F+" "+(e.hc||""));this.parent.Ca(this.S,c.join(","))}},dc:function(b){return b?b.D.map(function(a){return a.a}).join(" "):"0 0"},rc:function(b,a,e){var c=this.d,f=b.Q,g=f.length,h=d.Ea.qc(c,a,e,b);b=h.Sc;var i=h.Tc,j=h.lc,m=h.mc;h=h.Dc;var n,l,o,t,u;n=[];for(l=0;l<g;l++)n.push(f[l].Cb?f[l].Cb.c(c,h):l===0?0:l===g-1?h:null);for(l=1;l<g;l++)if(n[l]===null){t=n[l-1];o=l;do u=n[++o];while(u===null);
n[l]=t+(u-t)/(o-l+1)}a=['<svg width="'+a+'" height="'+e+'" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="g" gradientUnits="userSpaceOnUse" x1="'+b/a*100+'%" y1="'+i/e*100+'%" x2="'+j/a*100+'%" y2="'+m/e*100+'%">'];for(l=0;l<g;l++)a.push('<stop offset="'+n[l]/h+'" stop-color="'+f[l].color.tb(c)+'" stop-opacity="'+f[l].color.ac()+'"/>');a.push('</linearGradient></defs><rect width="100%" height="100%" fill="url(#g)"/></svg>');return a.join("")},o:function(){this.parent.Ca(this.S)}});d.Pb=
d.la.$a({s:"repeat",Sb:"stretch",Rb:"round",S:0,Za:function(){return this.C.u.sb()},z:function(){return this.C.u.z()},ub:function(){var b=this,a=b.C.u.v(),e=b.C.U.v(),c=b.rb.X(),f=a.repeat,g=f.f,h=f.eb,i=b.d,j=0;d.na.ad(a.src,function(m){function n(R,V,W,X,Y,Z,S,s,w,B){C.push('<pattern patternUnits="userSpaceOnUse" id="pattern'+N+'" x="'+(g===k?R+W/2-w/2:R)+'" y="'+(h===k?V+X/2-B/2:V)+'" width="'+w+'" height="'+B+'"><svg width="'+w+'" height="'+B+'" viewBox="'+Y+" "+Z+" "+S+" "+s+'" preserveAspectRatio="none"><image xlink:href="'+
v+'" x="0" y="0" width="'+t+'" height="'+u+'" /></svg></pattern>');x.push('<rect x="'+R+'" y="'+V+'" width="'+W+'" height="'+X+'" fill="url(#pattern'+N+')" />');N++}var l=c.g,o=c.f,t=m.g,u=m.f,v=b.zc(a.src,t,u),k=b.s,p=b.Sb;m=b.Rb;var r=Math.ceil,q=d.h("0"),y=a.aa||(e?e.aa:{t:q,r:q,b:q,l:q});q=y.t.c(i);var A=y.r.c(i),E=y.b.c(i);y=y.l.c(i);var F=a.slice,I=F.t.c(i),K=F.r.c(i),H=F.b.c(i);F=F.l.c(i);var J=l-y-A,z=o-q-E,Q=t-F-K,T=u-I-H,M=g===p?J:Q*q/I,G=h===p?z:T*A/K,D=g===p?J:Q*E/H;p=h===p?z:T*y/F;var C=
[],x=[],N=0;if(g===m){M-=(M-(J%M||M))/r(J/M);D-=(D-(J%D||D))/r(J/D)}if(h===m){G-=(G-(z%G||G))/r(z/G);p-=(p-(z%p||p))/r(z/p)}m=['<svg width="'+l+'" height="'+o+'" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">'];n(0,0,y,q,0,0,F,I,y,q);n(y,0,J,q,F,0,Q,I,M,q);n(l-A,0,A,q,t-K,0,K,I,A,q);n(0,q,y,z,0,I,F,T,y,p);if(a.fill)n(y,q,J,z,F,I,Q,T,M||D||Q,p||G||T);n(l-A,q,A,z,t-K,I,K,T,A,G);n(0,o-E,y,E,0,u-H,F,H,y,E);n(y,o-E,J,E,F,u-H,Q,H,D,E);n(l-A,o-E,A,E,t-K,u-H,K,H,A,E);m.push("<defs>"+
C.join("\n")+"</defs>"+x.join("\n")+"</svg>");b.parent.Ca(b.S,"url(data:image/svg+xml,"+escape(m.join(""))+") no-repeat border-box border-box");j&&b.parent.wb()},b);j=1},zc:function(){var b={};return function(a,e,c){var f=b[a],g;if(!f){f=new Image;g=P.createElement("canvas");f.src=a;g.width=e;g.height=c;g.getContext("2d").drawImage(f,0,0);f=b[a]=g.toDataURL()}return f}}(),Eb:function(){if(this.z()){var b=this.d,a=b.runtimeStyle,e=this.C.u.v().aa;a.borderStyle="solid";if(e){a.borderTopWidth=e.t.c(b)+
"px";a.borderRightWidth=e.r.c(b)+"px";a.borderBottomWidth=e.b.c(b)+"px";a.borderLeftWidth=e.l.c(b)+"px"}this.xc()}},o:function(){var b=this.d.runtimeStyle;this.parent.Ca(this.S);b.borderColor=b.borderStyle=b.borderWidth=""}});d.kb=function(){function b(k,p){k.className+=" "+p}function a(k){var p=v.slice.call(arguments,1),r=p.length;setTimeout(function(){if(k)for(;r--;)b(k,p[r])},0)}function e(k){var p=v.slice.call(arguments,1),r=p.length;setTimeout(function(){if(k)for(;r--;){var q=p[r];q=u[q]||(u[q]=
new RegExp("\\b"+q+"\\b","g"));k.className=k.className.replace(q,"")}},0)}function c(k){function p(){if(!V){var s,w,B=d.P,O=k.currentStyle,L=O.getAttribute(g)==="true",$=O.getAttribute(i)!=="false",aa=O.getAttribute(j)!=="false";S=O.getAttribute(h);S=B>7?S!=="false":S==="true";if(!R){R=1;k.runtimeStyle.zoom=1;O=k;for(var ba=1;O=O.previousSibling;)if(O.nodeType===1){ba=0;break}ba&&b(k,o)}C.va();if(L&&(w=C.X())&&(s=P.documentElement||P.body)&&(w.y>s.clientHeight||w.x>s.clientWidth||w.y+w.f<0||w.x+w.g<
0)){if(!Y){Y=1;d.Ha.J(p)}}else{V=1;Y=R=0;d.Ha.Z(p);if(B===9){x={M:new d.fb(k),u:new d.gb(k),U:new d.hb(k),ya:new d.mb(k)};N=[x.M,x.U,x.u,x.ya];D=new d.Qb(k,C,x);s=[new d.Ob(k,C,x,D),new d.Pb(k,C,x,D)]}else{x={M:new d.fb(k),U:new d.hb(k),u:new d.gb(k),ec:new d.dd(k),fc:new d.gd(k),ya:new d.mb(k),Zc:new d.ld(k)};N=[x.M,x.U,x.u,x.ec,x.fc,x.ya,x.Zc];D=new d.kd(k,C,x);s=[new d.fd(k,C,x,D),new d.bd(k,C,x,D),new d.ed(k,C,x,D),new d.cd(k,C,x,D)];k.tagName==="IMG"&&s.push(new d.hd(k,C,x,D));D.md=s}G=[D].concat(s);
if(s=k.currentStyle.getAttribute(d.k+"watch-ancestors")){s=parseInt(s,10);w=0;for(L=k.parentNode;L&&(s==="NaN"||w++<s);){z(L,"onpropertychange",J);z(L,"onmouseenter",A);z(L,"onmouseleave",E);z(L,"onmousedown",F);if(L.tagName in d.xb){z(L,"onfocus",K);z(L,"onblur",H)}L=L.parentNode}}if(S){d.ga.J(q);d.ga.Nc()}q(0,1)}if(!W){W=1;B<9&&z(k,"onmove",r);z(k,"onresize",r);z(k,"onpropertychange",y);aa&&z(k,"onmouseenter",A);if(aa||$)z(k,"onmouseleave",E);$&&z(k,"onmousedown",F);if(k.tagName in d.xb){z(k,"onfocus",
K);z(k,"onblur",H)}d.ja.J(r);d.G.J(Q)}C.Da()}}function r(){C&&C.vc()&&q()}function q(s,w){if(!Z)if(V){C.va();for(var B=N.length;B--;)N[B].va();var O=G.length,L=C.Qc();for(B=0;B<O;B++)G[B].Eb();for(B=0;B<O;B++)if(w||L||s&&G[B].Za())G[B].Hb();D.wb();if(w||(!s||D.wd)&&C.Jc())D.Yc();for(s=N.length;s--;)N[s].Da();C.Da()}else R||p()}function y(){var s=event;s&&s.propertyName in t||q(1)}function A(){a(k,m)}function E(){e(k,m,n)}function F(){a(k,n);d.Ga.J(I)}function I(){e(k,n);d.Ga.Z(I)}function K(){a(k,
l)}function H(){e(k,l)}function J(){var s=event.propertyName;if(s==="className"||s==="id")y()}function z(s,w,B){s.attachEvent(w,B);X.push([s,w,B])}function Q(){if(W){for(var s=X.length,w;s--;){w=X[s];w[0].detachEvent(w[1],w[2])}d.G.Z(Q);W=0;X=[]}}function T(){if(!Z){var s,w;Q();Z=1;if(G){s=0;for(w=G.length;s<w;s++){G[s].ud=1;G[s].o()}}S&&d.ga.Z(q);d.ja.Z(q);G=C=x=N=k=null;M.vb=M=0}}var M=this,G,D,C=new d.ib(k),x,N,R,V,W,X=[],Y,Z,S;M.vb=k;M.Ac=p;M.o=T}var f={},g=d.k+"lazy-init",h=d.k+"poll",i=d.k+
"track-active",j=d.k+"track-hover",m=d.ea+"hover",n=d.ea+"active",l=d.ea+"focus",o=d.ea+"first-child",t={background:1,bgColor:1,display:1},u={},v=[];c.sc=function(k){var p=k.uniqueID;return f[p]||(f[p]=new c(k))};c.o=function(k){k=k.uniqueID;var p=f[k];if(p){p.o();delete f[k]}};c.rd=function(){var k=[],p;if(f){for(var r in f)if(f.hasOwnProperty(r)){p=f[r];k.push(p.vb);p.o()}f={}}return k};return c}();d.version="2.0beta1-SNAPSHOT";d.supportsVML=d.Gb;d.attach=function(b){if(d.P===9||d.P<9&&d.Gb)d.kb.sc(b).Ac()};
d.detach=function(b){d.kb.o(b)}})(window,document);
