(function(O,H){var i=O.PIE||(O.PIE={});i.Fa=function(a){var b,e,c,d,f=arguments;b=1;for(e=f.length;b<e;b++){d=f[b];for(c in d)if(d.hasOwnProperty(c))a[c]=d[c]}return a};i.Fa(i,{H:"-pie-",nb:"Pie",Oa:"pie_",sc:{TD:1,TH:1},Tb:{TABLE:1,THEAD:1,TBODY:1,TFOOT:1,TR:1,INPUT:1,TEXTAREA:1,SELECT:1,OPTION:1,IMG:1,HR:1},Zb:{A:1,INPUT:1,TEXTAREA:1,SELECT:1,BUTTON:1},Hd:{submit:1,button:1,reset:1},od:function(){}});try{H.execCommand("BackgroundImageCache",false,true)}catch(aa){}(function(){for(var a=4,b=H.createElement("div"),
e=b.getElementsByTagName("i");b.innerHTML="<!--[if gt IE "+ ++a+"]><i></i><![endif]--\>",e[0];);i.Z=a;if(a===6)i.H=i.H.replace(/^-/,"");i.pa=H.documentMode||i.Z;b.innerHTML='<v:shape adj="1"/>';a=b.firstChild;a.style.behavior="url(#default#VML)";i.rc=typeof a.adj==="object"})();(function(){var a=0,b={};i.Q={oa:function(e){return e&&e._pieId||(e._pieId="_"+a++)},xc:function(e,c,d){var f=b[e],g,j;if(f)Object.prototype.toString.call(f)==="[object Array]"?f.push([c,d]):c.call(d,f);else{j=b[e]=[[c,d]];
g=new Image;g.onload=function(){f=b[e]={f:g.width,e:g.height};for(var h=0,k=j.length;h<k;h++)j[h][0].call(j[h][1],f);g.onload=null};g.src=e}}}})();i.kb={xd:function(a,b,e,c){function d(){k=g>=90&&g<270?b:0;n=g<180?e:0;m=b-k;o=e-n}function f(){for(;g<0;)g+=360;g%=360}var g=c.ya;c=c.zb;var j,h,k,n,m,o,r,s;if(c){c=c.coords(a,b,e);j=c.x;h=c.y}if(g){g=g.fd();f();d();if(!c){j=k;h=n}c=i.kb.mc(j,h,g,m,o);a=c[0];c=c[1]}else if(c){a=b-j;c=e-h}else{j=h=a=0;c=e}r=a-j;s=c-h;if(g===void 0){g=!r?s<0?90:270:!s?r<
0?180:0:-Math.atan2(s,r)/Math.PI*180;f();d()}return{ya:g,be:j,ce:h,re:a,se:c,$d:k,ae:n,pd:m,qd:o,gd:r,hd:s,Jd:i.kb.Vb(j,h,a,c)}},mc:function(a,b,e,c,d){if(e===0||e===180)return[c,b];else if(e===90||e===270)return[a,d];else{e=Math.tan(-e*Math.PI/180);a=e*a-b;b=-1/e;c=b*c-d;d=b-e;return[(c-a)/d,(e*c-b*a)/d]}},Vb:function(a,b,e,c){a=e-a;b=c-b;return Math.abs(a===0?b:b===0?a:Math.sqrt(a*a+b*b))}};i.ia=function(){this.Eb=[];this.fc={}};i.ia.prototype={ba:function(a){var b=i.Q.oa(a),e=this.fc,c=this.Eb;
if(!(b in e)){e[b]=c.length;c.push(a)}},Ka:function(a){a=i.Q.oa(a);var b=this.fc;if(a&&a in b){delete this.Eb[b[a]];delete b[a]}},Da:function(){for(var a=this.Eb,b=a.length;b--;)a[b]&&a[b]()}};i.Qa=new i.ia;i.Qa.Td=function(){var a=this;if(!a.Ud){setInterval(function(){a.Da()},250);a.Ud=1}};(function(){function a(){i.J.Da();O.detachEvent("onunload",a);O.PIE=null}i.J=new i.ia;O.attachEvent("onunload",a);i.J.za=function(b,e,c){b.attachEvent(e,c);this.ba(function(){b.detachEvent(e,c)})}})();i.Ta=new i.ia;
i.J.za(O,"onresize",function(){i.Ta.Da()});(function(){function a(){i.mb.Da()}i.mb=new i.ia;i.J.za(O,"onscroll",a);i.Ta.ba(a)})();(function(){function a(){e=i.jb.jd()}function b(){if(e){for(var c=0,d=e.length;c<d;c++)i.attach(e[c]);e=0}}var e;i.J.za(O,"onbeforeprint",a);i.J.za(O,"onafterprint",b)})();i.lb=new i.ia;i.J.za(H,"onmouseup",function(){i.lb.Da()});i.Ra=function(){function a(h){this.ga=h}var b=H.createElement("length-calc"),e=H.body||H.documentElement,c=b.style,d={},f=["mm","cm","in","pt",
"pc"],g=f.length,j={};c.position="absolute";c.top=c.left="-9999px";for(e.appendChild(b);g--;){c.width="100"+f[g];d[f[g]]=b.offsetWidth/100}e.removeChild(b);c.width="1em";a.prototype={Fb:/(px|em|ex|mm|cm|in|pt|pc|%)$/,bc:function(){var h=this.Ld;if(h===void 0)h=this.Ld=parseFloat(this.ga);return h},yb:function(){var h=this.ge;if(!h)h=this.ge=(h=this.ga.match(this.Fb))&&h[0]||"px";return h},a:function(h,k){var n=this.bc(),m=this.yb();switch(m){case "px":return n;case "%":return n*(typeof k==="function"?
k():k)/100;case "em":return n*this.wb(h);case "ex":return n*this.wb(h)/2;default:return n*d[m]}},wb:function(h){var k=h.currentStyle.fontSize,n,m;if(k.indexOf("px")>0)return parseFloat(k);else if(h.tagName in i.Tb){m=this;n=h.parentNode;return i.m(k).a(n,function(){return m.wb(n)})}else{h.appendChild(b);k=b.offsetWidth;b.parentNode===h&&h.removeChild(b);return k}}};a.fb=function(h){return h/d.pt};i.m=function(h){return j[h]||(j[h]=new a(h))};return a}();i.Ma=function(){function a(d){this.fa=d}var b=
i.m("50%"),e={top:1,center:1,bottom:1},c={left:1,center:1,right:1};a.prototype={Bd:function(){if(!this.Rb){var d=this.fa,f=d.length,g=i.p,j=g.xa,h=i.m("0");j=j.ua;h=["left",h,"top",h];if(f===1){d.push(new g.ob(j,"center"));f++}if(f===2){j&(d[0].j|d[1].j)&&d[0].c in e&&d[1].c in c&&d.push(d.shift());if(d[0].j&j)if(d[0].c==="center")h[1]=b;else h[0]=d[0].c;else if(d[0].N())h[1]=i.m(d[0].c);if(d[1].j&j)if(d[1].c==="center")h[3]=b;else h[2]=d[1].c;else if(d[1].N())h[3]=i.m(d[1].c)}this.Rb=h}return this.Rb},
coords:function(d,f,g){var j=this.Bd(),h=j[1].a(d,f);d=j[3].a(d,g);return{x:j[0]==="right"?f-h:h,y:j[2]==="bottom"?g-d:d}}};return a}();i.Na=function(){function a(b,e){this.f=b;this.e=e}a.prototype={a:function(b,e,c,d,f){var g=this.f,j=this.e,h=e/c;d=d/f;if(g==="contain"){g=d>h?e:c*d;j=d>h?e/d:c}else if(g==="cover"){g=d<h?e:c*d;j=d<h?e/d:c}else if(g==="auto"){j=j==="auto"?f:j.a(b,c);g=j*d}else{g=g.a(b,e);j=j==="auto"?g/d:j.a(b,c)}return{f:g,e:j}}};a.Gc=new a("auto","auto");return a}();i.zc=function(){function a(b){this.ga=
b}a.prototype={Fb:/[a-z]+$/i,yb:function(){return this.Tc||(this.Tc=this.ga.match(this.Fb)[0].toLowerCase())},fd:function(){var b=this.Oc,e;if(b===undefined){b=this.yb();e=parseFloat(this.ga,10);b=this.Oc=b==="deg"?e:b==="rad"?e/Math.PI*180:b==="grad"?e/400*360:b==="turn"?e*360:0}return b}};return a}();i.Fc=function(){function a(c,d,f){if(f<0)f+=1;else if(f>1)f-=1;return 255*(6*f<1?c+(d-c)*f*6:2*f<1?d:3*f<2?c+(d-c)*(2/3-f)*6:c)}function b(c){this.ga=c}var e={};b.Sd=/\s*rgba?\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*(,\s*(\d+|\d*\.\d+))?\s*\)\s*/;
b.Fd=/\s*hsla?\(\s*(\d*\.?\d+)\s*,\s*(\d{1,3})%\s*,\s*(\d{1,3})%\s*(,\s*(\d+|\d*\.\d+))?\s*\)\s*/;b.Db={aliceblue:"F0F8FF",antiquewhite:"FAEBD7",aqua:"0FF",aquamarine:"7FFFD4",azure:"F0FFFF",beige:"F5F5DC",bisque:"FFE4C4",black:"000",blanchedalmond:"FFEBCD",blue:"00F",blueviolet:"8A2BE2",brown:"A52A2A",burlywood:"DEB887",cadetblue:"5F9EA0",chartreuse:"7FFF00",chocolate:"D2691E",coral:"FF7F50",cornflowerblue:"6495ED",cornsilk:"FFF8DC",crimson:"DC143C",cyan:"0FF",darkblue:"00008B",darkcyan:"008B8B",
darkgoldenrod:"B8860B",darkgray:"A9A9A9",darkgreen:"006400",darkkhaki:"BDB76B",darkmagenta:"8B008B",darkolivegreen:"556B2F",darkorange:"FF8C00",darkorchid:"9932CC",darkred:"8B0000",darksalmon:"E9967A",darkseagreen:"8FBC8F",darkslateblue:"483D8B",darkslategray:"2F4F4F",darkturquoise:"00CED1",darkviolet:"9400D3",deeppink:"FF1493",deepskyblue:"00BFFF",dimgray:"696969",dodgerblue:"1E90FF",firebrick:"B22222",floralwhite:"FFFAF0",forestgreen:"228B22",fuchsia:"F0F",gainsboro:"DCDCDC",ghostwhite:"F8F8FF",
gold:"FFD700",goldenrod:"DAA520",gray:"808080",green:"008000",greenyellow:"ADFF2F",honeydew:"F0FFF0",hotpink:"FF69B4",indianred:"CD5C5C",indigo:"4B0082",ivory:"FFFFF0",khaki:"F0E68C",lavender:"E6E6FA",lavenderblush:"FFF0F5",lawngreen:"7CFC00",lemonchiffon:"FFFACD",lightblue:"ADD8E6",lightcoral:"F08080",lightcyan:"E0FFFF",lightgoldenrodyellow:"FAFAD2",lightgreen:"90EE90",lightgrey:"D3D3D3",lightpink:"FFB6C1",lightsalmon:"FFA07A",lightseagreen:"20B2AA",lightskyblue:"87CEFA",lightslategray:"789",lightsteelblue:"B0C4DE",
lightyellow:"FFFFE0",lime:"0F0",limegreen:"32CD32",linen:"FAF0E6",magenta:"F0F",maroon:"800000",mediumauqamarine:"66CDAA",mediumblue:"0000CD",mediumorchid:"BA55D3",mediumpurple:"9370D8",mediumseagreen:"3CB371",mediumslateblue:"7B68EE",mediumspringgreen:"00FA9A",mediumturquoise:"48D1CC",mediumvioletred:"C71585",midnightblue:"191970",mintcream:"F5FFFA",mistyrose:"FFE4E1",moccasin:"FFE4B5",navajowhite:"FFDEAD",navy:"000080",oldlace:"FDF5E6",olive:"808000",olivedrab:"688E23",orange:"FFA500",orangered:"FF4500",
orchid:"DA70D6",palegoldenrod:"EEE8AA",palegreen:"98FB98",paleturquoise:"AFEEEE",palevioletred:"D87093",papayawhip:"FFEFD5",peachpuff:"FFDAB9",peru:"CD853F",pink:"FFC0CB",plum:"DDA0DD",powderblue:"B0E0E6",purple:"800080",red:"F00",rosybrown:"BC8F8F",royalblue:"4169E1",saddlebrown:"8B4513",salmon:"FA8072",sandybrown:"F4A460",seagreen:"2E8B57",seashell:"FFF5EE",sienna:"A0522D",silver:"C0C0C0",skyblue:"87CEEB",slateblue:"6A5ACD",slategray:"708090",snow:"FFFAFA",springgreen:"00FF7F",steelblue:"4682B4",
tan:"D2B48C",teal:"008080",thistle:"D8BFD8",tomato:"FF6347",turquoise:"40E0D0",violet:"EE82EE",wheat:"F5DEB3",white:"FFF",whitesmoke:"F5F5F5",yellow:"FF0",yellowgreen:"9ACD32"};b.prototype={parse:function(){if(!this.pb){var c=this.ga,d;if(d=c.match(b.Sd)){c=this.oc(+d[1],+d[2],+d[3]);d=d[5]?+d[5]:1}else if(d=c.match(b.Fd)){var f=d[1],g=d[2],j=d[3],h,k;c=Math.round;g/=100;j/=100;if(g){g=j<=0.5?j*(g+1):j+g-j*g;h=j*2-g;f=f%360/360;j=a(h,g,f+1/3);k=a(h,g,f);f=a(h,g,f-1/3)}else j=k=f=j*255;c={Qd:c(j),
td:c(k),Wc:c(f)};c=this.oc(c.Qd,c.td,c.Wc);d=d[5]?+d[5]:1}else{if(b.Db.hasOwnProperty(d=c.toLowerCase()))c="#"+b.Db[d];d=c==="transparent"?0:1}this.pb=c;this.Nc=d}},oc:function(c,d,f){return"#"+(c<16?"0":"")+c.toString(16)+(d<16?"0":"")+d.toString(16)+(f<16?"0":"")+f.toString(16)},L:function(c){this.parse();return this.pb==="currentColor"?i.X(c.currentStyle.color).L(c):this.pb},ka:function(){this.parse();return this.Nc}};i.X=function(c){return e[c]||(e[c]=new b(c))};return b}();i.p=function(){function a(e){this.ab=
e;this.ch=0;this.fa=[];this.Ja=0}var b=a.xa={La:1,Lb:2,u:4,Hc:8,Mb:16,ua:32,I:64,va:128,wa:256,Ua:512,Kc:1024,URL:2048};a.ob=function(e,c){this.j=e;this.c=c};a.ob.prototype={Ea:function(){return this.j&b.I||this.j&b.va&&this.c==="0"},N:function(){return this.Ea()||this.j&b.Ua}};a.prototype={le:/\s/,Md:/^[\+\-]?(\d*\.)?\d+/,url:/^url\(\s*("([^"]*)"|'([^']*)'|([!#$%&*-~]*))\s*\)/i,ec:/^\-?[_a-z][\w-]*/i,de:/^("([^"]*)"|'([^']*)')/,Dd:/^#([\da-f]{6}|[\da-f]{3})/i,he:{px:b.I,em:b.I,ex:b.I,mm:b.I,cm:b.I,
"in":b.I,pt:b.I,pc:b.I,deg:b.La,rad:b.La,grad:b.La},$c:{rgb:1,rgba:1,hsl:1,hsla:1},next:function(e){function c(o,r){o=new a.ob(o,r);if(!e){k.fa.push(o);k.Ja++}return o}function d(){k.Ja++;return null}var f,g,j,h,k=this;if(this.Ja<this.fa.length)return this.fa[this.Ja++];for(;this.le.test(this.ab.charAt(this.ch));)this.ch++;if(this.ch>=this.ab.length)return d();g=this.ch;f=this.ab.substring(this.ch);j=f.charAt(0);switch(j){case "#":if(h=f.match(this.Dd)){this.ch+=h[0].length;return c(b.u,h[0])}break;
case '"':case "'":if(h=f.match(this.de)){this.ch+=h[0].length;return c(b.Kc,h[2]||h[3]||"")}break;case "/":case ",":this.ch++;return c(b.wa,j);case "u":if(h=f.match(this.url)){this.ch+=h[0].length;return c(b.URL,h[2]||h[3]||h[4]||"")}}if(h=f.match(this.Md)){j=h[0];this.ch+=j.length;if(f.charAt(j.length)==="%"){this.ch++;return c(b.Ua,j+"%")}if(h=f.substring(j.length).match(this.ec)){j+=h[0];this.ch+=h[0].length;return c(this.he[h[0].toLowerCase()]||b.Hc,j)}return c(b.va,j)}if(h=f.match(this.ec)){j=
h[0];this.ch+=j.length;if(j.toLowerCase()in i.Fc.Db||j==="currentColor"||j==="transparent")return c(b.u,j);if(f.charAt(j.length)==="("){this.ch++;if(j.toLowerCase()in this.$c){f=function(o){return o&&o.j&b.va};h=function(o){return o&&o.j&(b.va|b.Ua)};var n=function(o,r){return o&&o.c===r},m=function(){return k.next(1)};if((j.charAt(0)==="r"?h(m()):f(m()))&&n(m(),",")&&h(m())&&n(m(),",")&&h(m())&&(j==="rgb"||j==="hsa"||n(m(),",")&&f(m()))&&n(m(),")"))return c(b.u,this.ab.substring(g,this.ch));return d()}return c(b.Mb,
j)}return c(b.ua,j)}this.ch++;return c(b.Lb,j)},w:function(){return this.fa[this.Ja-- -2]},all:function(){for(;this.next(););return this.fa},ta:function(e,c){for(var d=[],f,g;f=this.next();){if(e(f)){g=true;this.w();break}d.push(f)}return c&&!g?null:d}};return a}();i.Kb=function(a){this.d=a};i.Kb.prototype={U:0,Od:function(){var a=this.qb,b;return!a||(b=this.n())&&(a.x!==b.x||a.y!==b.y)},Xd:function(){var a=this.qb,b;return!a||(b=this.n())&&(a.f!==b.f||a.e!==b.e)},ac:function(){var a=this.d,b=a.getBoundingClientRect(),
e=i.pa===9;return{x:b.left,y:b.top,f:e?a.offsetWidth:b.right-b.left,e:e?a.offsetHeight:b.bottom-b.top}},n:function(){return this.U?this.Xa||(this.Xa=this.ac()):this.ac()},Cd:function(){return!!this.qb},cb:function(){++this.U},hb:function(){if(!--this.U){if(this.Xa)this.qb=this.Xa;this.Xa=null}}};(function(){function a(b){var e=i.Q.oa(b);return function(){if(this.U){var c=this.Pb||(this.Pb={});return e in c?c[e]:(c[e]=b.call(this))}else return b.call(this)}}i.o={U:0,aa:function(b){function e(c){this.d=
c;this.Ob=this.Y()}i.Fa(e.prototype,i.o,b);e.Sc={};return e},i:function(){var b=this.Y(),e=this.constructor.Sc;return b?b in e?e[b]:(e[b]=this.da(b)):null},Y:a(function(){var b=this.d,e=this.constructor,c=b.style;b=b.currentStyle;var d=this.Aa,f=this.Ia,g=e.Qc||(e.Qc=i.H+d);e=e.Rc||(e.Rc=i.nb+f.charAt(0).toUpperCase()+f.substring(1));return c[e]||b.getAttribute(g)||c[f]||b.getAttribute(d)}),h:a(function(){return!!this.i()}),F:a(function(){var b=this.Y(),e=b!==this.Ob;this.Ob=b;return e}),na:a,cb:function(){++this.U},
hb:function(){--this.U||delete this.Pb}}})();i.Hb=i.o.aa({Aa:i.H+"background",Ia:i.nb+"Background",Vc:{scroll:1,fixed:1,local:1},gb:{"repeat-x":1,"repeat-y":1,repeat:1,"no-repeat":1},lc:{"padding-box":1,"border-box":1,"content-box":1},Pd:{top:1,right:1,bottom:1,left:1,center:1},Yd:{contain:1,cover:1},eb:{Pa:"backgroundClip",u:"backgroundColor",ha:"backgroundImage",Sa:"backgroundOrigin",P:"backgroundPosition",ja:"backgroundRepeat",Va:"backgroundSize"},da:function(a){function b(q){return q&&q.N()||
q.j&k&&q.c in s}function e(q){return q&&(q.N()&&i.m(q.c)||q.c==="auto"&&"auto")}var c=this.d.currentStyle,d,f,g,j=i.p.xa,h=j.wa,k=j.ua,n=j.u,m,o,r=0,s=this.Pd,l,p,t={R:[]};if(this.vb()){d=new i.p(a);for(g={};f=d.next();){m=f.j;o=f.c;if(!g.T&&m&j.Mb&&o==="linear-gradient"){l={sa:[],T:o};for(p={};f=d.next();){m=f.j;o=f.c;if(m&j.Lb&&o===")"){p.color&&l.sa.push(p);l.sa.length>1&&i.Fa(g,l);break}if(m&n){if(l.ya||l.zb){f=d.w();if(f.j!==h)break;d.next()}p={color:i.X(o)};f=d.next();if(f.N())p.jc=i.m(f.c);
else d.w()}else if(m&j.La&&!l.ya&&!p.color&&!l.sa.length)l.ya=new i.zc(f.c);else if(b(f)&&!l.zb&&!p.color&&!l.sa.length){d.w();l.zb=new i.Ma(d.ta(function(q){return!b(q)},false))}else if(m&h&&o===","){if(p.color){l.sa.push(p);p={}}}else break}}else if(!g.T&&m&j.URL){g.Bb=o;g.T="image"}else if(b(f)&&!g.la){d.w();g.la=new i.Ma(d.ta(function(q){return!b(q)},false))}else if(m&k)if(o in this.gb&&!g.bb)g.bb=o;else if(o in this.lc&&!g.Za){g.Za=o;if((f=d.next())&&f.j&k&&f.c in this.lc)g.Ya=f.c;else{g.Ya=
o;d.w()}}else if(o in this.Vc&&!g.Xc)g.Xc=o;else return null;else if(m&n&&!t.color)t.color=i.X(o);else if(m&h&&o==="/"&&!g.$a&&g.la){f=d.next();if(f.j&k&&f.c in this.Yd)g.$a=new i.Na(f.c);else if(f=e(f)){m=e(d.next());if(!m){m=f;d.w()}g.$a=new i.Na(f,m)}else return null}else if(m&h&&o===","&&g.T){g.kc=a.substring(r,d.ch-1);r=d.ch;t.R.push(g);g={}}else return null}if(g.T){g.kc=a.substring(r);t.R.push(g)}t.Zc=g.Ya}else this.vc(i.pa<9?function(){var q=this.eb,u=c[q.P+"X"],B=c[q.P+"Y"],z=c[q.ha],A=c[q.u];
if(A!=="transparent")t.color=i.X(A);if(z!=="none")t.R=[{T:"image",Bb:(new i.p(z)).next().c,bb:c[q.ja],la:new i.Ma((new i.p(u+" "+B)).all())}]}:function(){var q=this.eb,u=/\s*,\s*/,B=c[q.ha].split(u),z=c[q.u],A,C,F,G,J,w;if(z!=="transparent")t.color=i.X(z);if((G=B.length)&&B[0]!=="none"){z=c[q.ja].split(u);A=c[q.P].split(u);C=c[q.Sa].split(u);F=c[q.Pa].split(u);q=c[q.Va].split(u);t.R=[];for(u=0;u<G;u++)if((J=B[u])&&J!=="none"){w=q[u].split(" ");t.R.push({kc:J+" "+z[u]+" "+A[u]+" / "+q[u]+" "+C[u]+
" "+F[u],T:"image",Bb:(new i.p(J)).next().c,bb:z[u],la:new i.Ma((new i.p(A[u])).all()),Za:C[u],Ya:F[u],$a:new i.Na(w[0],w[1])})}}});return t.color||t.R[0]?t:null},vc:function(a){var b=i.pa>8,e=this.eb,c=this.d.runtimeStyle,d=c[e.ha],f=c[e.u],g=c[e.ja],j,h,k,n;if(d)c[e.ha]="";if(f)c[e.u]="";if(g)c[e.ja]="";if(b){j=c[e.Pa];h=c[e.Sa];n=c[e.P];k=c[e.Va];if(j)c[e.Pa]="";if(h)c[e.Sa]="";if(n)c[e.P]="";if(k)c[e.Va]=""}a=a.call(this);if(d)c[e.ha]=d;if(f)c[e.u]=f;if(g)c[e.ja]=g;if(b){if(j)c[e.Pa]=j;if(h)c[e.Sa]=
h;if(n)c[e.P]=n;if(k)c[e.Va]=k}return a},Y:i.o.na(function(){return this.vb()||this.vc(function(){var a=this.d.currentStyle,b=this.eb;return a[b.u]+" "+a[b.ha]+" "+a[b.ja]+" "+a[b.P+"X"]+" "+a[b.P+"Y"]})}),vb:i.o.na(function(){var a=this.d;return a.style[this.Ia]||a.currentStyle.getAttribute(this.Aa)}),ud:function(a,b,e,c){var d=this.d,f=b.n();b=f.f;f=f.e;if(a!=="border-box")if((e=e.i())&&(e=e.O)){b-=e.l.a(d)+e.l.a(d);f-=e.t.a(d)+e.b.a(d)}if(a==="content-box")if(a=c.i()){b-=a.l.a(d)+a.l.a(d);f-=a.t.a(d)+
a.b.a(d)}return{f:b,e:f}},gc:function(){var a=0;if(i.Z<7){a=this.d;a=""+(a.style[i.nb+"PngFix"]||a.currentStyle.getAttribute(i.H+"png-fix"))==="true"}return a},h:i.o.na(function(){return(this.vb()||this.gc())&&!!this.i()})});i.Jb=i.o.aa({qc:["Top","Right","Bottom","Left"],Kd:{thin:"1px",medium:"3px",thick:"5px"},da:function(){var a={},b={},e={},c=false,d=true,f=true,g=true;this.wc(function(){for(var j=this.d.currentStyle,h=0,k,n,m,o,r,s,l;h<4;h++){m=this.qc[h];l=m.charAt(0).toLowerCase();k=b[l]=j["border"+
m+"Style"];n=j["border"+m+"Color"];m=j["border"+m+"Width"];if(h>0){if(k!==o)f=false;if(n!==r)d=false;if(m!==s)g=false}o=k;r=n;s=m;e[l]=i.X(n);m=a[l]=i.m(b[l]==="none"?"0":this.Kd[m]||m);if(m.a(this.d)>0)c=true}});return c?{O:a,ee:b,ad:e,ue:g,bd:d,fe:f}:null},Y:i.o.na(function(){var a=this.d,b=a.currentStyle,e;a.tagName in i.sc&&a.offsetParent.currentStyle.borderCollapse==="collapse"||this.wc(function(){e=b.borderWidth+"|"+b.borderStyle+"|"+b.borderColor});return e}),wc:function(a){var b=this.d.runtimeStyle,
e=b.borderWidth,c=b.borderColor;if(e)b.borderWidth="";if(c)b.borderColor="";a=a.call(this);if(e)b.borderWidth=e;if(c)b.borderColor=c;return a}});(function(){i.ib=i.o.aa({Aa:"border-radius",Ia:"borderRadius",da:function(b){var e=null,c,d,f,g,j=false;if(b){d=new i.p(b);var h=function(){for(var k=[],n;(f=d.next())&&f.N();){g=i.m(f.c);n=g.bc();if(n<0)return null;if(n>0)j=true;k.push(g)}return k.length>0&&k.length<5?{tl:k[0],tr:k[1]||k[0],br:k[2]||k[0],bl:k[3]||k[1]||k[0]}:null};if(b=h()){if(f){if(f.j&
i.p.xa.wa&&f.c==="/")c=h()}else c=b;if(j&&b&&c)e={x:b,y:c}}}return e}});var a=i.m("0");a={tl:a,tr:a,br:a,bl:a};i.ib.yc={x:a,y:a}})();i.Ib=i.o.aa({Aa:"border-image",Ia:"borderImage",gb:{stretch:1,round:1,repeat:1,space:1},da:function(a){var b=null,e,c,d,f,g,j,h=0,k=i.p.xa,n=k.ua,m=k.va,o=k.Ua;if(a){e=new i.p(a);b={};for(var r=function(p){return p&&p.j&k.wa&&p.c==="/"},s=function(p){return p&&p.j&n&&p.c==="fill"},l=function(){f=e.ta(function(p){return!(p.j&(m|o))});if(s(e.next())&&!b.fill)b.fill=true;
else e.w();if(r(e.next())){h++;g=e.ta(function(p){return!p.N()&&!(p.j&n&&p.c==="auto")});if(r(e.next())){h++;j=e.ta(function(p){return!p.Ea()})}}else e.w()};a=e.next();){c=a.j;d=a.c;if(c&(m|o)&&!f){e.w();l()}else if(s(a)&&!b.fill){b.fill=true;l()}else if(c&n&&this.gb[d]&&!b.repeat){b.repeat={e:d};if(a=e.next())if(a.j&n&&this.gb[a.c])b.repeat.uc=a.c;else e.w()}else if(c&k.URL&&!b.src)b.src=d;else return null}if(!b.src||!f||f.length<1||f.length>4||g&&g.length>4||h===1&&g.length<1||j&&j.length>4||h===
2&&j.length<1)return null;if(!b.repeat)b.repeat={e:"stretch"};if(!b.repeat.uc)b.repeat.uc=b.repeat.e;a=function(p,t){return{t:t(p[0]),r:t(p[1]||p[0]),b:t(p[2]||p[0]),l:t(p[3]||p[1]||p[0])}};b.slice=a(f,function(p){return i.m(p.j&m?p.c+"px":p.c)});if(g&&g[0])b.O=a(g,function(p){return p.N()?i.m(p.c):p.c});if(j&&j[0])b.Ga=a(j,function(p){return p.Ea()?i.m(p.c):p.c})}return b}});i.Ec=i.o.aa({Aa:"box-shadow",Ia:"boxShadow",da:function(a){var b,e=i.m,c=i.p.xa,d;if(a){d=new i.p(a);b={Ga:[],Cb:[]};for(a=
function(){for(var f,g,j,h,k,n;f=d.next();){j=f.c;g=f.j;if(g&c.wa&&j===",")break;else if(f.Ea()&&!k){d.w();k=d.ta(function(m){return!m.Ea()})}else if(g&c.u&&!h)h=j;else if(g&c.ua&&j==="inset"&&!n)n=true;else return false}f=k&&k.length;if(f>1&&f<5){(n?b.Cb:b.Ga).push({me:e(k[0].c),ne:e(k[1].c),blur:e(k[2]?k[2].c:"0"),Zd:e(k[3]?k[3].c:"0"),color:i.X(h||"currentColor")});return true}return false};a(););}return b&&(b.Cb.length||b.Ga.length)?b:null}});i.Nb=i.o.aa({da:function(a){a=new i.p(a);for(var b=
[],e;(e=a.next())&&e.N();)b.push(i.m(e.c));return b.length>0&&b.length<5?{t:b[0],r:b[1]||b[0],b:b[2]||b[0],l:b[3]||b[1]||b[0]}:null},Y:i.o.na(function(){var a=this.d,b=a.runtimeStyle,e=b.padding;if(e)b.padding="";a=a.currentStyle.padding;if(e)b.padding=e;return a})});i.Lc=i.o.aa({Y:i.o.na(function(){var a=this.d.currentStyle;return a.visibility+"|"+a.display}),da:function(){var a=this.d,b=a.runtimeStyle;a=a.currentStyle;var e=b.visibility,c;b.visibility="";c=a.visibility;b.visibility=e;return{ke:c!==
"hidden",kd:a.display!=="none"}},h:function(){return false}});i.Mc=function(){function a(d){return function(){var f=arguments,g,j=f.length,h,k,n;h=this[e+d]||(this[e+d]={});for(g=0;g<j;g+=2)h[f[g]]=f[g+1];if(h=this.B()){if(d)h=h[d];for(g=0;g<j;g+=2){k=f[g];if(n=c[k])n.call(this,h,k,f[g+1]);else h[k]=f[g+1]}}}}function b(d,f){this.Xb="_pie_"+(d||"shape")+i.Q.oa(this);this.db=f||0}var e="_attrs_",c={colors:function(d,f,g){if(d[f])d[f].value=g;else d[f]=g},size:function(d,f,g){if(g){d[f].x=1;d[f]=g}else delete d[f]},
"o:opacity2":function(d,f,g){if(g!==this.Id){this.B().insertAdjacentHTML("afterEnd",this.xb());this.k();this.Id=g}}};(function d(){try{H.namespaces.add("pievml","urn:schemas-microsoft-com:vml","#default#VML")}catch(f){setTimeout(d,1)}})();b.prototype={Sb:"behavior:url(#default#VML);",ed:"position:absolute;top:0px;left:0px;",dd:'coordorigin="1,1" stroked="false" ',tagName:"shape",ic:0,B:function(){return this.ic?this.Qb||(this.Qb=H.getElementById(this.Xb)):null},ea:a(""),Ha:a("style"),z:a("fill"),
ra:function(d,f){this.Ha("width",d+"px","height",f+"px");this.ea("coordsize",d*2+","+f*2)},Ad:function(){var d=this[e+"style"]||{},f=[],g;for(g in d)d.hasOwnProperty(g)&&f.push(g+":"+d[g]);return this.Sb+this.ed+f.join(";")},xb:function(){function d(m){if(m)for(var o in m)m.hasOwnProperty(o)&&g.push(" "+o+'="'+m[o]+'"')}function f(m){var o=j[e+m];if(o){g.push(k+m);d(o);g.push(n)}}var g,j=this,h=j.tagName,k="<pievml:",n=' style="'+j.Sb+'" />';j.ic=1;g=[k,h,' id="',j.Xb,'" style="',j.Ad(),'" ',j.dd];
d(j[e]);g.push(">");f("fill");g.push("</pievml:"+h+">");return g.join("")},k:function(){var d=this.B(),f=d&&d.parentNode;if(f){f.removeChild(d);delete this.Qb}}};return b}();i.v={qa:function(a){function b(e,c,d,f){this.d=e;this.s=c;this.g=d;this.parent=f}i.Fa(b.prototype,i.v,a);return b},$:function(){return false},nc:i.od,tc:function(){this.h()?this.Ca():this.k()},Ab:function(){this.d.runtimeStyle.borderColor="transparent"},k:function(){}};i.Fa(i.v,{B:function(a,b){var e=this.tb||(this.tb={}),c=e[a];
if(!c){c=e[a]=new i.Mc(a,b);this.parent.rd(c)}return c},Ba:function(a){var b=this.tb,e=b&&b[a];if(e){e.k();this.parent.Rd(e);delete b[a]}return!!e},zd:function(a){var b=this.d,e=this.s.n(),c=e.f,d=e.e,f,g,j,h,k,n;e=a.x.tl.a(b,c);f=a.y.tl.a(b,d);g=a.x.tr.a(b,c);j=a.y.tr.a(b,d);h=a.x.br.a(b,c);k=a.y.br.a(b,d);n=a.x.bl.a(b,c);a=a.y.bl.a(b,d);c=Math.min(c/(e+g),d/(j+k),c/(n+h),d/(f+a));if(c<1){e*=c;f*=c;g*=c;j*=c;h*=c;k*=c;n*=c;a*=c}return{x:{tl:e,tr:g,br:h,bl:n},y:{tl:f,tr:j,br:k,bl:a}}},V:function(a,
b,e,c,d,f){a=this.W(a,b,e,c,d,f);return"m"+a[0]+","+a[1]+"qy"+a[2]+","+a[3]+"l"+a[4]+","+a[5]+"qx"+a[6]+","+a[7]+"l"+a[8]+","+a[9]+"qy"+a[10]+","+a[11]+"l"+a[12]+","+a[13]+"qx"+a[14]+","+a[15]+"x"},W:function(a,b,e,c,d,f){var g=this.s.n(),j=g.f*d,h=g.e*d,k=Math;g=k.floor;var n=k.ceil,m=k.max;k=k.min;a*=d;b*=d;e*=d;c*=d;f||(f=this.g.D.i());if(f){f=this.zd(f);var o=f.x.tl*d,r=f.y.tl*d,s=f.x.tr*d,l=f.y.tr*d,p=f.x.br*d,t=f.y.br*d,q=f.x.bl*d;d=f.y.bl*d;c=[g(c),g(k(m(r,a),h-e)),g(k(m(o,c),j-b)),g(a),n(m(c,
j-m(s,b))),g(a),n(j-b),g(k(m(l,a),h-e)),n(j-b),n(m(a,h-m(t,e))),n(m(c,j-m(p,b))),n(h-e),g(k(m(q,c),j-b)),n(h-e),g(c),n(m(a,h-m(d,e)))]}else{a=g(a);b=n(j-b);e=n(h-e);c=g(c);c=[c,a,c,a,b,a,b,a,b,e,b,e,c,e,c,e]}return c},Ab:function(){var a=this.d,b=a.currentStyle,e=a.runtimeStyle,c=a.tagName,d=i.Z===6,f;if(d&&(c in i.Tb||c==="FIELDSET")||c==="BUTTON"||c==="INPUT"&&a.type in i.Hd){e.borderWidth="";c=this.g.q.qc;for(f=c.length;f--;){d=c[f];e["padding"+d]="";e["padding"+d]=i.m(b["padding"+d]).a(a)+i.m(b["border"+
d+"Width"]).a(a)+(i.Z!==8&&f%2?1:0)}e.borderWidth=0}else if(d){if(a.childNodes.length!==1||a.firstChild.tagName!=="ie6-mask"){b=H.createElement("ie6-mask");c=b.style;c.visibility="visible";for(c.zoom=1;c=a.firstChild;)b.appendChild(c);a.appendChild(b);e.visibility="hidden"}}else e.borderColor="transparent"},te:function(){},k:function(){var a=this.tb,b;if(a)for(b in a)a.hasOwnProperty(b)&&this.Ba(b)}});i.Jc=i.v.qa({hc:false,h:function(){var a=this.Yc;for(var b in a)if(a.hasOwnProperty(b)&&a[b].h())return true;
return false},$:function(){return this.g.Gb.F()},ie:function(){if(this.h()&&this.ub()){var a=this.cc(),b=a,e;a=a.currentStyle;var c=a.position,d=this.ub().style,f=0,g=0;g=this.s.n();if(c==="fixed"&&i.Z>6){f=g.x;g=g.y;b=c}else{do b=b.offsetParent;while(b&&b.currentStyle.position==="static");if(b){e=b.getBoundingClientRect();b=b.currentStyle;f=g.x-e.left-(parseFloat(b.borderLeftWidth)||0);g=g.y-e.top-(parseFloat(b.borderTopWidth)||0)}else{b=H.documentElement;f=g.x+b.scrollLeft-b.clientLeft;g=g.y+b.scrollTop-
b.clientTop}b="absolute"}d.position=b;d.left=f;d.top=g;d.zIndex=c==="static"?-1:a.zIndex;this.hc=true}},je:function(){var a=this.g.Gb,b=this.Wa;if(b&&a.F()){a=a.i();b.style.display=a.ke&&a.kd?"":"none"}},tc:function(){this.h()?this.je():this.k()},cc:function(){var a=this.d;return a.tagName in i.sc?a.offsetParent:a},ub:function(){var a=this.Wa;if(!a)a=this.Wa=H.getElementById("_pie"+i.Q.oa(this));return a},sd:function(){var a=this.sb,b,e,c,d,f,g;if(a){if(b=this.rb){e=0;for(c=a.length;e<c;e++){for(d=
b.length;d--;)if(b[d].db<a[e].db)break;if(d<0){f=this.ub();g="afterBegin"}else{f=b[d].B();g="afterEnd"}f.insertAdjacentHTML(g,a[e].xb());b.splice(d<0?0:d,0,a[e])}}else{a.sort(this.Vd);b=['<css3pie id="_pie'+i.Q.oa(this)+'" style="direction:ltr;position:absolute;">'];e=0;for(c=a.length;e<c;e++)b.push(a[e].xb());b.push("</css3pie>");this.cc().insertAdjacentHTML("beforeBegin",b.join(""));this.rb=a}this.sb=0}},Vd:function(a,b){return a.db-b.db},rd:function(a){(this.sb||(this.sb=[])).push(a)},Rd:function(a){var b=
this.rb,e;if(b)for(e=b.length;e--;)if(b[e]===a){b.splice(e,1);break}},k:function(){var a=this.Wa,b;if(a&&(b=a.parentNode))b.removeChild(a);delete this.Wa;delete this.rb}});H.createElement("css3pie");i.Ac=i.v.qa({G:2,$:function(){var a=this.g;return a.K.F()||a.D.F()},h:function(){var a=this.g;return a.C.h()||a.D.h()||a.K.h()||a.ma.h()&&a.ma.i().Cb},Ca:function(){var a=this.s.n();if(a.f&&a.e){this.md();this.nd()}},md:function(){var a=this.g.K.i(),b=this.s.n(),e=this.d,c=a&&a.color,d;if(c&&c.ka()>0){this.dc();
d=this.B("bgColor",this.G);d.ra(b.f,b.e);d.ea("path",this.$b(b,a.Zc));d.z("color",c.L(e));a=c.ka();a<1&&d.z("opacity",a)}else this.Ba("bgColor")},nd:function(){var a=this.g.K.i(),b=this.s.n();a=a&&a.R;var e,c,d,f,g;if(a){this.dc();d=b.f;f=b.e;for(g=a.length;g--;){e=a[g];c=this.B("bgImage"+g,this.G+(0.5-g/1E3));c.ea("path",this.$b(b,e.Ya));c.ra(d,f);if(e.T==="linear-gradient")this.Uc(c,e);else{c.z("type","tile","color","none");this.Nd(c,e.Bb,g)}}}for(g=a?a.length:0;this.Ba("bgImage"+g++););},Nd:function(a,
b,e){i.Q.xc(b,function(c){var d=this.d,f=this.s.n(),g=f.f;f=f.e;if(g&&f){var j=this.g,h=j.K,k=h.i().R[e],n=h.ud(k.Za,this.s,j.q,j.ca);j=(k.$a||i.Na.Gc).a(this.d,n.f,n.e,c.f,c.e);h=this.vd(k.Za);d=k.la?k.la.coords(d,n.f-j.f,n.e-j.e):{x:0,y:0};k=k.bb;var m=0,o=0,r=g+1,s=f+1,l=i.Z===8?0:1;n=Math.round(h.x+d.x)+0.5;h=Math.round(h.y+d.y)+0.5;a.z("src",b,"position",n/g+","+h/f,"size",j.f!==c.f||j.e!==c.e||screen.logicalXDPI/screen.deviceXDPI!==1?i.Ra.fb(j.f)+"pt,"+i.Ra.fb(j.e)+"pt":"");if(k&&k!=="repeat"){if(k===
"repeat-x"||k==="no-repeat"){m=h+1;s=h+j.e+l}if(k==="repeat-y"||k==="no-repeat"){o=n+1;r=n+j.f+l}a.Ha("clip","rect("+m+"px,"+r+"px,"+s+"px,"+o+"px)")}}},this)},$b:function(a,b){var e=0,c=0,d=0,f=0,g=this.d,j=this.g,h;if(b&&b!=="border-box")if((h=j.q.i())&&(h=h.O)){e+=h.t.a(g);c+=h.r.a(g);d+=h.b.a(g);f+=h.l.a(g)}if(b==="content-box")if(b=j.ca.i()){e+=b.t.a(g);c+=b.r.a(g);d+=b.b.a(g);f+=b.l.a(g)}return"m0,0r0,0m"+a.f*2+","+a.e*2+"r0,0"+this.V(e,c,d,f,2)},vd:function(a){var b=this.d,e=this.g,c=0,d=0,
f;if(a!=="border-box")if((f=e.q.i())&&(f=f.O)){c+=f.l.a(b);d+=f.t.a(b)}if(a==="content-box")if(a=e.ca.i()){c+=a.l.a(b);d+=a.t.a(b)}return{x:c,y:d}},Uc:function(a,b){var e=this.d,c=this.s.n(),d=c.f,f=c.e;c=b.sa;var g=c.length,j=Math.PI,h=i.kb,k=h.mc,n=h.Vb;b=h.xd(e,d,f,b);h=b.ya;var m=b.be,o=b.ce,r=b.$d,s=b.ae,l=b.pd,p=b.qd,t=b.gd,q=b.hd;b=b.Jd;d=h%90?Math.atan2(t*d/f,q)/j*180:h+90;d+=180;d%=360;l=k(r,s,h,l,p);f=n(r,s,l[0],l[1]);j=[];l=k(m,o,h,r,s);n=n(m,o,l[0],l[1])/f*100;k=[];for(h=0;h<g;h++)k.push(c[h].jc?
c[h].jc.a(e,b):h===0?0:h===g-1?b:null);for(h=1;h<g;h++){if(k[h]===null){m=k[h-1];b=h;do o=k[++b];while(o===null);k[h]=m+(o-m)/(b-h+1)}k[h]=Math.max(k[h],k[h-1])}for(h=0;h<g;h++)j.push(n+k[h]/f*100+"% "+c[h].color.L(e));a.z("angle",d,"type","gradient","method","sigma","color",c[0].color.L(e),"color2",c[g-1].color.L(e),"colors",j.join(","));g===2&&a.z("opacity",c[1].color.ka(),"o:opacity2",c[0].color.ka())},dc:function(){var a=this.d.runtimeStyle;a.backgroundImage="url(about:blank)";a.backgroundColor=
"transparent"},k:function(){i.v.k.call(this);var a=this.d.runtimeStyle;a.backgroundImage=a.backgroundColor=""}});i.Cc=i.v.qa({G:4,Wd:{t:[2,1,0,3,4,7,6,5,90],r:[4,7,6,5,10,9,8,11,0],b:[10,9,8,11,12,15,14,13,270],l:[12,15,14,13,2,1,0,3,180]},cd:{dotted:1,dashed:1},Ub:{groove:1,ridge:1,inset:1,outset:1},ld:{groove:1,ridge:1,"double":1},$:function(){var a=this.g;return a.q.F()||a.D.F()},h:function(){var a=this.g;return a.D.h()&&!a.C.h()&&a.q.h()},Ca:function(){var a=this.g.q.i(),b=this.s.n(),e,c,d;if(a){this.Ab();
e=this.wd();c=0;for(d=e.length;c<d;c+=2){a=this.B("border"+c,this.G);a.ra(b.f,b.e);a.ea("path",e[c]);a.z("color",e[c+1])}for(;this.Ba("border"+c++););}},S:function(a,b,e,c,d,f,g){g=c*(g==="dashed"?3:1);c=d+c;var j;if(g<e-b)for(b+=(e-b-g)/2%g;b<e;){j=Math.min(b+g,e);a.push(f?"m"+d+","+b+"l"+d+","+j+"l"+c+","+j+"l"+c+","+b+"x":"m"+b+","+d+"l"+j+","+d+"l"+j+","+c+"l"+b+","+c+"x");b+=g*2}},wd:function(){var a=this.g.q,b=[];if(a.h()){var e=this.d,c=this.s.n(),d=a.i(),f=d.O;a=d.ee;var g=d.ad,j=Math,h=j.abs,
k=j.round;j=k(f.t.a(e));var n=k(f.r.a(e)),m=k(f.b.a(e));f=k(f.l.a(e));k=[];var o,r,s,l=this.Wd,p,t=this.cd,q,u;if(d.fe&&d.bd&&!(a.t in this.Ub)){if(g.t.ka()>0){k[0]=this.V(0,0,0,0,2);q=a.t;if(q==="double")k.push(this.V(j/3,n/3,m/3,f/3,2)+this.V(j*2/3,n*2/3,m*2/3,f*2/3,2));else if(q in t){d=this.W(j,n,m,f,2);this.S(k,d[2],d[4],j*2,0,0,a.t);this.S(k,d[7],d[9],n*2,(c.f-n)*2,1,a.r);this.S(k,d[12],d[10],m*2,(c.e-m)*2,0,a.b);this.S(k,d[1],d[15],f*2,0,1,a.l)}k.push(this.V(j,n,m,f,2));b.push(k.join(""),g.t.L(e))}}else{o=
this.W(0,0,0,0,2);d=this.W(j,n,m,f,2);for(p in l)if(l.hasOwnProperty(p)){q=l[p];var B=q[0],z=q[1],A=q[2],C=q[3],F=q[4],G=q[5],J=q[6],w=q[7],I=q[8],Q=p==="t"||p==="l";q=a[p];k[0]="al"+o[B]+","+o[z]+","+h(o[A]-o[B])+","+h(o[C]-o[z])+","+(I+45)*65535+",-2949075ae"+o[F]+","+o[G]+","+h(o[J]-o[F])+","+h(o[w]-o[G])+","+I*65535+",-2949075";if(q in this.ld){if(!r)if(q==="double"){r=this.W(j/3,n/3,m/3,f/3,2);s=this.W(j*2/3,n*2/3,m*2/3,f*2/3,2)}else r=s=this.W(j/2,n/2,m/2,f/2,2);k.push("ae"+r[F]+","+r[G]+","+
h(r[J]-r[F])+","+h(r[w]-r[G])+","+(I-45)*65535+",2949075ae"+r[B]+","+r[z]+","+h(r[A]-r[B])+","+h(r[C]-r[z])+","+I*65535+",2949075x");if(q!=="double"){u=g[p].L(e)+((q==="groove"?Q:!Q)?" darken(128)":" lighten(128)");b.push(k.join(""),u);k.length=0}k.push("al"+s[B]+","+s[z]+","+h(s[A]-s[B])+","+h(s[C]-s[z])+","+(I+45)*65535+",-2949075ae"+s[F]+","+s[G]+","+h(s[J]-s[F])+","+h(s[w]-s[G])+","+I*65535+",-2949075")}k.push("ae"+d[F]+","+d[G]+","+h(d[J]-d[F])+","+h(d[w]-d[G])+","+(I-45)*65535+",2949075ae"+
d[B]+","+d[z]+","+h(d[A]-d[B])+","+h(d[C]-d[z])+","+I*65535+",2949075x");if(q in t)p==="t"?this.S(k,d[2],d[4],j*2,0,0,q):p==="r"?this.S(k,d[7],d[9],n*2,(c.f-n)*2,1,q):p==="b"?this.S(k,d[12],d[10],m*2,(c.e-m)*2,0,q):this.S(k,d[1],d[15],f*2,0,1,q);u=g[p].L(e);if(q in this.Ub)u+=(q==="groove"||q==="outset"?Q:!Q)?" lighten(128)":" darken(128)";b.push(k.join(""),u);k.length=0}}}return b},k:function(){if(this.Yb||!this.g.C.h())this.d.runtimeStyle.borderColor="";i.v.k.call(this)}});i.Bc=i.v.qa({G:5,$:function(){return this.g.C.F()},
h:function(){return this.g.C.h()},Ca:function(){var a=this.g.C.i(),b=this.g.q.i(),e=this.s.n(),c=this.d;i.Q.xc(a.src,function(d){function f(u,B,z,A,C,F,G,J,w){var I=Math.max;if(!t||!q||!A||!C||!J||!w)u.Ha("display","none");else{A=I(A,0);C=I(C,0);u.ea("path","m0,0l"+A*2+",0l"+A*2+","+C*2+"l0,"+C*2+"x");u.z("src",p,"type","tile","position","0,0","origin",(F-0.5)/t+","+(G-0.5)/q,"size",i.Ra.fb(A*t/J)+"pt,"+i.Ra.fb(C*q/w)+"pt");u.ra(A,C);u.Ha("left",B+"px","top",z+"px","display","")}}var g=e.f,j=e.e,
h=i.m("0"),k=a.O||(b?b.O:{t:h,r:h,b:h,l:h});h=k.t.a(c);var n=k.r.a(c),m=k.b.a(c);k=k.l.a(c);var o=a.slice,r=o.t.a(c),s=o.r.a(c),l=o.b.a(c);o=o.l.a(c);var p=a.src,t=d.f,q=d.e;f(this.M("tl"),0,0,k,h,0,0,o,r);f(this.M("t"),k,0,g-k-n,h,o,0,t-o-s,r);f(this.M("tr"),g-n,0,n,h,t-s,0,s,r);f(this.M("r"),g-n,h,n,j-h-m,t-s,r,s,q-r-l);f(this.M("br"),g-n,j-m,n,m,t-s,q-l,s,l);f(this.M("b"),k,j-m,g-k-n,m,o,q-l,t-o-s,l);f(this.M("bl"),0,j-m,k,m,0,q-l,o,l);f(this.M("l"),0,h,k,j-h-m,0,r,o,q-r-l);f(this.M("c"),k,h,g-
k-n,j-h-m,o,r,a.fill?t-o-s:0,q-r-l)},this)},M:function(a){return this.B("borderImage_"+a,this.G)},nc:function(){if(this.h()){var a=this.d,b=a.runtimeStyle,e=this.g.C.i().O;b.borderStyle="solid";if(e){b.borderTopWidth=e.t.a(a);b.borderRightWidth=e.r.a(a);b.borderBottomWidth=e.b.a(a);b.borderLeftWidth=e.l.a(a)}this.Ab()}},k:function(){var a=this.d.runtimeStyle;a.borderStyle="";if(this.Yb||!this.g.q.h())a.borderColor=a.borderWidth="";i.v.k.call(this)}});i.Dc=i.v.qa({G:1,$:function(){var a=this.g;return a.ma.F()||
a.D.F()},h:function(){var a=this.g.ma;return a.h()&&a.i().Ga[0]},Ca:function(){var a=this.d,b=this.g,e=b.ma.i().Ga;b=b.D.i();var c=e.length,d=c,f=this.s.n(),g=f.f;f=f.e;for(var j,h,k,n,m,o,r,s,l,p;d--;){j=e[d];k=j.me.a(a);n=j.ne.a(a);m=j.Zd.a(a);o=j.blur.a(a);j=j.color;r=j.ka();j=j.L(a);h=-m-o;if(!b&&o)b=i.ib.yc;s=this.V(h,h,h,h,2,b);h=this.B("shadow"+d,this.G+(0.5-d/1E3));if(o){l=(m+o)*2+g;p=(m+o)*2+f;m=l?o*2/l:0;o=p?o*2/p:0;if(m>0.5||o>0.5){l=0.5/Math.max(m,o);m*=l;o*=l;r*=l*l}h.z("type","gradienttitle",
"color2",j,"focusposition",m+","+o,"focussize",1-m*2+","+(1-o*2),"opacity",0,"o:opacity2",r)}else h.z("type","solid","opacity",r);h.ea("path",s);h.z("color",j);h.Ha("left",k+"px","top",n+"px");h.ra(g,f)}for(;this.Ba("shadow"+c++););}});i.Ic=i.v.qa({G:6,$:function(){var a=this.g;return this.d.src!==this.Pc||a.D.F()},h:function(){var a=this.g;return a.D.h()||a.K.gc()},Ca:function(){this.Pc=f;this.Ed();var a=this.B("img",this.G),b=this.s.n(),e=b.f;b=b.e;var c=this.g.q.i(),d=c&&c.O;c=this.d;var f=c.src,
g=Math.round,j=this.g.ca.i();if(!d||i.Z<7){d=i.m("0");d={t:d,r:d,b:d,l:d}}a.ea("path",this.V(g(d.t.a(c)+j.t.a(c)),g(d.r.a(c)+j.r.a(c)),g(d.b.a(c)+j.b.a(c)),g(d.l.a(c)+j.l.a(c)),2));a.z("type","frame","src",f,"position",(e?0.5/e:0)+","+(b?0.5/b:0));a.ra(e,b)},Ed:function(){this.d.runtimeStyle.filter="alpha(opacity=0)"},k:function(){i.v.k.call(this);this.d.runtimeStyle.filter=""}});i.jb=function(){function a(l,p){l.className+=" "+p}function b(l){var p=s.slice.call(arguments,1),t=p.length;setTimeout(function(){if(l)for(;t--;)a(l,
p[t])},0)}function e(l){var p=s.slice.call(arguments,1),t=p.length;setTimeout(function(){if(l)for(;t--;){var q=p[t];q=r[q]||(r[q]=new RegExp("\\b"+q+"\\b","g"));l.className=l.className.replace(q,"")}},0)}function c(l){function p(){if(!W){var v,x,E=i.pa,M=l.currentStyle,K=M.getAttribute(f)==="true",$=M.getAttribute(j)!=="false";R=M.getAttribute(g);R=E>7?R!=="false":R==="true";if(!T){T=1;l.runtimeStyle.zoom=1;M=l;for(var Z=1;M=M.previousSibling;)if(M.nodeType===1){Z=0;break}Z&&a(l,m)}D.cb();if(K&&(x=
D.n())&&(v=H.documentElement||H.body)&&(x.y>v.clientHeight||x.x>v.clientWidth||x.y+x.e<0||x.x+x.f<0)){if(!X){X=1;i.mb.ba(p)}}else{W=1;X=T=0;i.mb.Ka(p);if(E===9){y={K:new i.Hb(l),C:new i.Ib(l),q:new i.Jb(l),ca:new i.Nb(l)};P=[y.K,y.q,y.C,y.ca];L=new i.qe(l,D,y);v=[new i.oe(l,D,y,L),new i.pe(l,D,y,L)]}else{y={K:new i.Hb(l),q:new i.Jb(l),C:new i.Ib(l),D:new i.ib(l),ma:new i.Ec(l),ca:new i.Nb(l),Gb:new i.Lc(l)};P=[y.K,y.q,y.C,y.D,y.ma,y.ca,y.Gb];L=new i.Jc(l,D,y);v=[new i.Dc(l,D,y,L),new i.Ac(l,D,y,L),
new i.Cc(l,D,y,L),new i.Bc(l,D,y,L)];l.tagName==="IMG"&&v.push(new i.Ic(l,D,y,L));L.Yc=v}N=[L].concat(v);if(v=l.currentStyle.getAttribute(i.H+"watch-ancestors")){v=parseInt(v,10);x=0;for(K=l.parentNode;K&&(v==="NaN"||x++<v);){w(K,"onpropertychange",J);w(K,"onmouseenter",B);w(K,"onmouseleave",z);w(K,"onmousedown",A);if(K.tagName in i.Zb){w(K,"onfocus",F);w(K,"onblur",G)}K=K.parentNode}}if(R){i.Qa.ba(q);i.Qa.Td()}q(0,1)}if(!U){U=1;E<9&&w(l,"onmove",t);w(l,"onresize",t);w(l,"onpropertychange",u);w(l,
"onmouseenter",B);w(l,"onmouseleave",z);$&&w(l,"onmousedown",A);if(l.tagName in i.Zb){w(l,"onfocus",F);w(l,"onblur",G)}i.Ta.ba(t);i.J.ba(I)}D.hb()}}function t(){D&&D.Cd()&&q()}function q(v,x){if(!Y)if(W){D.cb();for(var E=P.length;E--;)P[E].cb();var M=N.length,K=D.Xd();for(E=0;E<M;E++)N[E].nc();for(E=0;E<M;E++)if(x||K||v&&N[E].$())N[E].tc();L.sd();if(x||L.hc&&D.Od())L.ie();for(v=P.length;v--;)P[v].hb();D.hb()}else T||p()}function u(){var v=event;v&&v.propertyName in o||q(1)}function B(){b(l,h)}function z(){e(l,
h,k)}function A(){b(l,k);i.lb.ba(C)}function C(){e(l,k);i.lb.Ka(C)}function F(){b(l,n)}function G(){e(l,n)}function J(){var v=event.propertyName;if(v==="className"||v==="id")u()}function w(v,x,E){v.attachEvent(x,E);V.push([v,x,E])}function I(){if(U){for(var v=V.length,x;v--;){x=V[v];x[0].detachEvent(x[1],x[2])}i.J.Ka(I);U=0;V=[]}}function Q(){if(!Y){var v,x;I();Y=1;if(N){v=0;for(x=N.length;v<x;v++){N[v].Yb=1;N[v].k()}}R&&i.Qa.Ka(q);i.Ta.Ka(q);N=D=y=P=l=null;S.Wb=S=0}}var S=this,N,L,D=new i.Kb(l),
y,P,T,W,U,V=[],X,Y,R;S.Wb=l;S.Gd=p;S.k=Q}var d={},f=i.H+"lazy-init",g=i.H+"poll",j=i.H+"track-active",h=i.Oa+"hover",k=i.Oa+"active",n=i.Oa+"focus",m=i.Oa+"first-child",o={background:1,bgColor:1,display:1},r={},s=[];c.yd=function(l){var p=l.uniqueID;return d[p]||(d[p]=new c(l))};c.k=function(l){l=l.uniqueID;var p=d[l];if(p){p.k();delete d[l]}};c.jd=function(){var l=[],p;if(d){for(var t in d)if(d.hasOwnProperty(t)){p=d[t];l.push(p.Wb);p.k()}d={}}return l};return c}();i.version="2.0beta1-SNAPSHOT";
i.supportsVML=i.rc;i.attach=function(a){if(i.pa===9||i.pa<9&&i.rc)i.jb.yd(a).Gd()};i.detach=function(a){i.jb.k(a)}})(window,document);
