(function(N,L){var e=N.PIE||(N.PIE={});e.ia=function(a){var b,c,d,f,g=arguments;b=1;for(c=g.length;b<c;b++){f=g[b];for(d in f)if(f.hasOwnProperty(d))a[d]=f[d]}return a};e.ia(e,{z:"-pie-",Ya:"Pie",oa:"pie_",Yc:{TD:1,TH:1},Wb:{TABLE:1,THEAD:1,TBODY:1,TFOOT:1,TR:1,INPUT:1,TEXTAREA:1,SELECT:1,OPTION:1,IMG:1,HR:1},Ab:{A:1,INPUT:1,TEXTAREA:1,SELECT:1,BUTTON:1},zd:{submit:1,button:1,reset:1},Ea:aa()});try{L.execCommand("BackgroundImageCache",false,true)}catch($){}(function(){for(var a=4,b=L.createElement("div"),
c=b.getElementsByTagName("i");b.innerHTML="<!--[if gt IE "+ ++a+"]><i></i><![endif]--\>",c[0];);e.ba=a;if(a===6)e.z=e.z.replace(/^-/,"");e.T=L.documentMode||e.ba;b.innerHTML='<v:shape adj="1"/>';a=b.firstChild;a.style.behavior="url(#default#VML)";e.Kb=typeof a.adj==="object"})();(function(){var a=0,b={};e.O={aa:function(c){return c&&c.uniqueID||c._pieId||(c._pieId="_"+a++)},dc:function(c,d,f){var g=b[c],i,j;if(g)Object.prototype.toString.call(g)==="[object Array]"?g.push([d,f]):d.call(f,g);else{j=
b[c]=[[d,f]];i=new Image;i.onload=function(){g=b[c]={g:i.width,f:i.height};for(var h=0,l=j.length;h<l;h++)j[h][0].call(j[h][1],g);i.onload=null};i.src=c}}}})();e.Wa={Bc:function(a,b,c,d){function f(){l=i>=90&&i<270?b:0;n=i<180?c:0;m=b-l;p=c-n}function g(){for(;i<0;)i+=360;i%=360}var i=d.ga;d=d.eb;var j,h,l,n,m,p,v,k;if(d){d=d.coords(a,b,c);j=d.x;h=d.y}if(i){i=i.wc();g();f();if(!d){j=l;h=n}d=e.Wa.bc(j,h,i,m,p);a=d[0];d=d[1]}else if(d){a=b-j;d=c-h}else{j=h=a=0;d=c}v=a-j;k=d-h;if(i===void 0){i=!v?k<
0?90:270:!k?v<0?180:0:-Math.atan2(k,v)/Math.PI*180;g();f()}return{ga:i,Uc:j,Vc:h,td:a,ud:d,Dd:l,Ed:n,rd:m,sd:p,pd:v,qd:k,Jc:e.Wa.Yb(j,h,a,d)}},bc:function(a,b,c,d,f){if(c===0||c===180)return[d,b];else if(c===90||c===270)return[a,f];else{c=Math.tan(-c*Math.PI/180);a=c*a-b;b=-1/c;d=b*d-f;f=b-c;return[(d-a)/f,(c*d-b*a)/f]}},Yb:function(a,b,c,d){a=c-a;b=d-b;return Math.abs(a===0?b:b===0?a:Math.sqrt(a*a+b*b))}};e.X=function(){this.gb=[];this.Gb={}};e.X.prototype={Q:function(a){var b=e.O.aa(a),c=this.Gb,
d=this.gb;if(!(b in c)){c[b]=d.length;d.push(a)}},ea:function(a){a=e.O.aa(a);var b=this.Gb;if(a&&a in b){delete this.gb[b[a]];delete b[a]}},Fa:function(){for(var a=this.gb,b=a.length;b--;)a[b]&&a[b]()}};e.qa=new e.X;e.qa.Qc=function(){var a=this;if(!a.Rc){setInterval(function(){a.Fa()},250);a.Rc=1}};e.ta=new e.X;e.L.xa(window,"onresize",function(){e.ta.Fa()});(function(){function a(){e.Xa.Fa()}e.Xa=new e.X;e.L.xa(window,"onscroll",a);e.ta.Q(a)})();(function(){function a(){c=e.Va.yc()}function b(){if(c){for(var d=
0,f=c.length;d<f;d++)e.attach(c[d]);c=0}}var c;e.L.xa(window,"onbeforeprint",a);e.L.xa(window,"onafterprint",b)})();e.Hd=function(){function a(h){this.K=h}var b=L.createElement("length-calc"),c=L.documentElement,d=b.style,f={},g=["mm","cm","in","pt","pc"],i=g.length,j={};d.position="absolute";d.top=d.left="-9999px";for(c.appendChild(b);i--;){b.style.width="100"+g[i];f[g[i]]=b.offsetWidth/100}c.removeChild(b);b.style.width="1em";a.prototype={hb:/(px|em|ex|mm|cm|in|pt|pc|%)$/,$b:function(){var h=this.Kc;
if(h===void 0)h=this.Kc=parseFloat(this.K);return h},db:function(){var h=this.Zc;if(!h)h=this.Zc=(h=this.K.match(this.hb))&&h[0]||"px";return h},a:function(h,l){var n=this.$b(),m=this.db();switch(m){case "px":return n;case "%":return n*(typeof l==="function"?l():l)/100;case "em":return n*this.cb(h);case "ex":return n*this.cb(h)/2;default:return n*f[m]}},cb:function(h){var l=h.currentStyle.fontSize,n,m;if(l.indexOf("px")>0)return parseFloat(l);else if(h.tagName in e.Wb){m=this;n=h.parentNode;return e.m(l).a(n,
function(){return m.cb(n)})}else{h.appendChild(b);l=b.offsetWidth;b.parentNode===h&&h.removeChild(b);return l}}};e.m=function(h){return j[h]||(j[h]=new a(h))};return a}();e.ma=function(){function a(f){this.J=f}var b=e.m("50%"),c={top:1,center:1,bottom:1},d={left:1,center:1,right:1};a.prototype={Dc:function(){if(!this.yb){var f=this.J,g=f.length,i=e.q,j=i.Ma,h=e.m("0");j=j.ra;h=["left",h,"top",h];if(g===1){f.push(new i.Za(j,"center"));g++}if(g===2){j&(f[0].h|f[1].h)&&f[0].d in c&&f[1].d in d&&f.push(f.shift());
if(f[0].h&j)if(f[0].d==="center")h[1]=b;else h[0]=f[0].d;else if(f[0].P())h[1]=e.m(f[0].d);if(f[1].h&j)if(f[1].d==="center")h[3]=b;else h[2]=f[1].d;else if(f[1].P())h[3]=e.m(f[1].d)}this.yb=h}return this.yb},coords:function(f,g,i){var j=this.Dc(),h=j[1].a(f,g);f=j[3].a(f,i);return{x:j[0]==="right"?g-h:h,y:j[2]==="bottom"?i-f:f}}};return a}();e.na=function(){function a(b,c){this.g=b;this.f=c}a.prototype={a:function(b,c,d,f,g){var i=this.g,j=this.f,h=c/d;f=f/g;if(i==="contain"){i=f>h?c:d*f;j=f>h?c/
f:d}else if(i==="cover"){i=f<h?c:d*f;j=f<h?c/f:d}else if(i==="auto"){j=j==="auto"?g:j.a(b,d);i=j*f}else{i=i.a(b,c);j=j==="auto"?i/f:j.a(b,d)}return{g:i,f:j}}};a.hc=new a("auto","auto");return a}();e.ec=function(){function a(b){this.K=b}a.prototype={hb:/[a-z]+$/i,db:function(){return this.rc||(this.rc=this.K.match(this.hb)[0].toLowerCase())},wc:function(){var b=this.lc,c;if(b===undefined){b=this.db();c=parseFloat(this.K,10);b=this.lc=b==="deg"?c:b==="rad"?c/Math.PI*180:b==="grad"?c/400*360:b==="turn"?
c*360:0}return b}};return a}();e.Sb=function(){function a(c){this.K=c}var b={};a.Pc=/\s*rgba\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d+|\d*\.\d+)\s*\)\s*/;a.Qa={};a.prototype={parse:function(){if(!this.va){var c=this.K,d;if(d=c.match(a.Pc)){this.va="rgb("+d[1]+","+d[2]+","+d[3]+")";this.ub=parseFloat(d[4])}else{if((d=c.toLowerCase())in a.Qa)c="#"+a.Qa[d];this.va=c;this.ub=c==="transparent"?0:1}}},Ca:function(c){this.parse();return this.va==="currentColor"?c.currentStyle.color:this.va},
ab:function(){this.parse();return this.ub}};e.Z=function(c){return b[c]||(b[c]=new a(c))};return a}();e.q=function(){function a(c){this.Da=c;this.ch=0;this.J=[];this.da=0}var b=a.Ma={la:1,rb:2,o:4,ic:8,sb:16,ra:32,u:64,fa:128,Ka:256,La:512,jc:1024,URL:2048};a.Za=function(c,d){this.h=c;this.d=d};a.Za.prototype={fb:function(){return this.h&b.u||this.h&b.fa&&this.d==="0"},P:function(){return this.fb()||this.h&b.La}};a.prototype={dd:/\s/,Lc:/^[\+\-]?(\d*\.)?\d+/,url:/^url\(\s*("([^"]*)"|'([^']*)'|([!#$%&*-~]*))\s*\)/i,
Fb:/^\-?[_a-z][\w-]*/i,Wc:/^("([^"]*)"|'([^']*)')/,Fc:/^#([\da-f]{6}|[\da-f]{3})/i,$c:{px:b.u,em:b.u,ex:b.u,mm:b.u,cm:b.u,"in":b.u,pt:b.u,pc:b.u,deg:b.la,rad:b.la,grad:b.la},vc:{rgb:1,rgba:1,hsl:1,hsla:1},next:function(c){function d(p,v){p=new a.Za(p,v);if(!c){l.J.push(p);l.da++}return p}function f(){l.da++;return null}var g,i,j,h,l=this;if(this.da<this.J.length)return this.J[this.da++];for(;this.dd.test(this.Da.charAt(this.ch));)this.ch++;if(this.ch>=this.Da.length)return f();i=this.ch;g=this.Da.substring(this.ch);
j=g.charAt(0);switch(j){case "#":if(h=g.match(this.Fc)){this.ch+=h[0].length;return d(b.o,h[0])}break;case '"':case "'":if(h=g.match(this.Wc)){this.ch+=h[0].length;return d(b.jc,h[2]||h[3]||"")}break;case "/":case ",":this.ch++;return d(b.Ka,j);case "u":if(h=g.match(this.url)){this.ch+=h[0].length;return d(b.URL,h[2]||h[3]||h[4]||"")}}if(h=g.match(this.Lc)){j=h[0];this.ch+=j.length;if(g.charAt(j.length)==="%"){this.ch++;return d(b.La,j+"%")}if(h=g.substring(j.length).match(this.Fb)){j+=h[0];this.ch+=
h[0].length;return d(this.$c[h[0].toLowerCase()]||b.ic,j)}return d(b.fa,j)}if(h=g.match(this.Fb)){j=h[0];this.ch+=j.length;if(j.toLowerCase()in e.Sb.Qa||j==="currentColor"||j==="transparent")return d(b.o,j);if(g.charAt(j.length)==="("){this.ch++;if(j.toLowerCase()in this.vc){g=function(p){return p&&p.h&b.fa};h=function(p){return p&&p.h&(b.fa|b.La)};var n=function(p,v){return p&&p.d===v},m=function(){return l.next(1)};if((j.charAt(0)==="r"?h(m()):g(m()))&&n(m(),",")&&h(m())&&n(m(),",")&&h(m())&&(j===
"rgb"||j==="hsa"||n(m(),",")&&g(m()))&&n(m(),")"))return d(b.o,this.Da.substring(i,this.ch));return f()}return d(b.sb,j)}return d(b.ra,j)}this.ch++;return d(b.rb,j)},s:function(){return this.J[this.da-- -2]},all:function(){for(;this.next(););return this.J},Ja:function(c,d){for(var f=[],g,i;g=this.next();){if(c(g)){i=true;this.s();break}f.push(g)}return d&&!i?null:f}};return a}();e.qb=function(a){this.e=a};e.qb.prototype={N:0,Mc:function(){var a=this.$a,b;return!a||(b=this.p())&&(a.x!==b.x||a.y!==
b.y)},Sc:function(){var a=this.$a,b;return!a||(b=this.p())&&(a.g!==b.g||a.f!==b.f)},Db:function(){var a=this.e,b=a.getBoundingClientRect(),c=e.T===9;return{x:b.left,y:b.top,g:c?a.offsetWidth:b.right-b.left,f:c?a.offsetHeight:b.bottom-b.top}},p:function(){return this.N?this.wa||(this.wa=this.Db()):this.Db()},Ec:function(){return!!this.$a},Ga:function(){++this.N},Ia:function(){if(!--this.N){if(this.wa)this.$a=this.wa;this.wa=null}}};(function(){function a(b){var c=e.O.aa(b);return function(){if(this.N){var d=
this.xb||(this.xb={});return c in d?d[c]:(d[c]=b.call(this))}else return b.call(this)}}e.w={N:0,Ra:function(b){function c(d){this.e=d;this.vb=this.$()}e.ia(c.prototype,e.w,b);c.oc={};return c},n:function(){var b=this.$(),c=this.constructor.oc;return b?b in c?c[b]:(c[b]=this.Sa(b)):null},$:a(function(){var b=this.e,c=this.constructor,d=b.style;b=b.currentStyle;var f=this.Oa,g=this.Ua,i=c.mc||(c.mc=e.z+f);c=c.nc||(c.nc=e.Ya+g.charAt(0).toUpperCase()+g.substring(1));return d[c]||b.getAttribute(i)||d[g]||
b.getAttribute(f)}),i:a(function(){return!!this.n()}),W:a(function(){var b=this.$(),c=b!==this.vb;this.vb=b;return c}),Ba:a,Ga:function(){++this.N},Ia:function(){--this.N||delete this.xb}}})();e.pb=e.w.Ra({Oa:e.z+"background",Ua:e.Ya+"Background",tc:{scroll:1,fixed:1,local:1},ob:{"repeat-x":1,"repeat-y":1,repeat:1,"no-repeat":1},Ib:{"padding-box":1,"border-box":1,"content-box":1},Nc:{top:1,right:1,bottom:1,left:1,center:1},Tc:{contain:1,cover:1},Ha:{pa:"backgroundClip",o:"backgroundColor",R:"backgroundImage",
sa:"backgroundOrigin",B:"backgroundPosition",M:"backgroundRepeat",ua:"backgroundSize"},Sa:function(a){function b(t){return t&&t.P()||t.h&l&&t.d in k}function c(t){return t&&(t.P()&&e.m(t.d)||t.d==="auto"&&"auto")}var d=this.e.currentStyle,f,g,i,j=e.q.Ma,h=j.Ka,l=j.ra,n=j.o,m,p,v=0,k=this.Nc,q,r,u={G:[]};if(this.bb()){f=new e.q(a);for(i={};g=f.next();){m=g.h;p=g.d;if(!i.F&&m&j.sb&&p==="linear-gradient"){q={U:[],F:p};for(r={};g=f.next();){m=g.h;p=g.d;if(m&j.rb&&p===")"){r.color&&q.U.push(r);q.U.length>
1&&e.ia(i,q);break}if(m&n){if(q.ga||q.eb){g=f.s();if(g.h!==h)break;f.next()}r={color:e.Z(p)};g=f.next();if(g.P())r.Hb=e.m(g.d);else f.s()}else if(m&j.la&&!q.ga&&!r.color&&!q.U.length)q.ga=new e.ec(g.d);else if(b(g)&&!q.eb&&!r.color&&!q.U.length){f.s();q.eb=new e.ma(f.Ja(function(t){return!b(t)},false))}else if(m&h&&p===","){if(r.color){q.U.push(r);r={}}}else break}}else if(!i.F&&m&j.URL){i.lb=p;i.F="image"}else if(b(g)&&!i.V){f.s();i.V=new e.ma(f.Ja(function(t){return!b(t)},false))}else if(m&l)if(p in
this.ob&&!i.Pa)i.Pa=p;else if(p in this.Ib&&!i.ya){i.ya=p;if((g=f.next())&&g.h&l&&g.d in this.Ib)i.jb=g.d;else{i.jb=p;f.s()}}else if(p in this.tc&&!i.Ub)i.Ub=p;else return null;else if(m&n&&!u.color)u.color=e.Z(p);else if(m&h&&p==="/"&&!i.za&&i.V){g=f.next();if(g.h&l&&g.d in this.Tc)i.za=new e.na(g.d);else if(g=c(g)){m=c(f.next());if(!m){m=g;f.s()}i.za=new e.na(g,m)}else return null}else if(m&h&&p===","&&i.F){i.nb=a.substring(v,f.ch-1);v=f.ch;u.G.push(i);i={}}else return null}if(i.F){i.nb=a.substring(v);
u.G.push(i)}}else this.Ob(e.T<9?function(){var t=this.Ha,o=d[t.B+"X"],x=d[t.B+"Y"],y=d[t.R],A=d[t.o];if(A!=="transparent")u.color=e.Z(A);if(y!=="none")u.G=[{F:"image",lb:(new e.q(y)).next().d,Pa:d[t.M],V:new e.ma((new e.q(o+" "+x)).all())}]}:function(){var t=this.Ha,o=/\s*,\s*/,x=d[t.R].split(o),y=d[t.o],A,C,E,K,G,D;if(y!=="transparent")u.color=e.Z(y);if((K=x.length)&&x[0]!=="none"){y=d[t.M].split(o);A=d[t.B].split(o);C=d[t.sa].split(o);E=d[t.pa].split(o);t=d[t.ua].split(o);u.G=[];for(o=0;o<K;o++)if((G=
x[o])&&G!=="none"){D=t[o].split(" ");u.G.push({nb:G+" "+y[o]+" "+A[o]+" / "+t[o]+" "+C[o]+" "+E[o],F:"image",lb:(new e.q(G)).next().d,Pa:y[o],V:new e.ma((new e.q(A[o])).all()),ya:C[o],jb:E[o],za:new e.na(D[0],D[1])})}}});return u.color||u.G[0]?u:null},Ob:function(a){var b=e.T>8,c=this.Ha,d=this.e.runtimeStyle,f=d[c.R],g=d[c.o],i=d[c.M],j,h,l,n;if(f)d[c.R]="";if(g)d[c.o]="";if(i)d[c.M]="";if(b){j=d[c.pa];h=d[c.sa];n=d[c.B];l=d[c.ua];if(j)d[c.pa]="";if(h)d[c.sa]="";if(n)d[c.B]="";if(l)d[c.ua]=""}a=
a.call(this);if(f)d[c.R]=f;if(g)d[c.o]=g;if(i)d[c.M]=i;if(b){if(j)d[c.pa]=j;if(h)d[c.sa]=h;if(n)d[c.B]=n;if(l)d[c.ua]=l}return a},$:e.w.Ba(function(){return this.bb()||this.Ob(function(){var a=this.e.currentStyle,b=this.Ha;return a[b.o]+" "+a[b.R]+" "+a[b.M]+" "+a[b.B+"X"]+" "+a[b.B+"Y"]})}),bb:e.w.Ba(function(){var a=this.e;return a.style[this.Ua]||a.currentStyle.getAttribute(this.Oa)}),ac:function(){var a=0;if(e.ba<7){a=this.e;a=""+(a.style[e.Ya+"PngFix"]||a.currentStyle.getAttribute(e.z+"png-fix"))===
"true"}return a},i:e.w.Ba(function(){return(this.bb()||this.ac())&&!!this.n()})});e.C={ja:function(a){function b(c,d,f,g){this.e=c;this.I=d;this.j=f;this.parent=g}e.ia(b.prototype,e.C,a);return b},mb:false,ca:function(){return false},Ta:e.Ea,Lb:function(){this.k();this.i()&&this.ha()},ib:function(){this.mb=true},Mb:function(){this.i()?this.ha():this.k()},k:aa()};e.kd=e.C.ja({ib:e.Ea,Mb:e.Ea,ad:e.Ea,Lb:e.Ea,ae:/^,+|,+$/g,Zd:/,+/g,cc:function(a,b){(this.kc||(this.kc=[]))[a]=b||void 0},kb:function(){var a=
this.kc,b;if(a&&(b=a.join(",").replace(this.ae,"").replace(this.Zd,","))!==this.Kd)this.Kd=this.e.runtimeStyle.background=b},k:function(){this.e.runtimeStyle.background="";delete this.kc}});e.hd=e.C.ja({zb:1,ca:function(){return this.j.D.W()},i:function(){var a=this.j;return a.D.i()||a.v.i()},ha:function(){var a=this.j.D.n(),b,c,d=0,f,g;if(a){b=[];if(c=a.G)for(;f=c[d++];)if(f.F==="linear-gradient"){g=this.Zb(f.ya);g=(f.za||e.na.hc).a(this.e,g.g,g.f,g.g,g.f);b.push("url(data:image/svg+xml,"+escape(this.Wd(f,
g.g,g.f))+") "+this.Nd(f.V)+" / "+g.g+"px "+g.f+"px "+(f.Ub||"")+" "+(f.ya||"")+" "+(f.jb||""))}else b.push(f.nb);a.color&&b.push(a.color.K);this.parent.cc(this.zb,b.join(","))}},Nd:function(a){return a?a.J.map(function(b){return b.d}).join(" "):"0 0"},Zb:e.fc.prototype.Zb,Wd:function(a,b,c){var d=this.e,f=a.U,g=f.length,i=e.Wa.Bc(d,b,c,a);a=i.Uc;var j=i.Vc,h=i.td,l=i.ud;i=i.Jc;var n,m,p,v,k;n=[];for(m=0;m<g;m++)n.push(f[m].Hb?f[m].Hb.a(d,i):m===0?0:m===g-1?i:null);for(m=1;m<g;m++)if(n[m]===null){v=
n[m-1];p=m;do k=n[++p];while(k===null);n[m]=v+(k-v)/(p-m+1)}b=['<svg width="'+b+'" height="'+c+'" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="g" gradientUnits="userSpaceOnUse" x1="'+a/b*100+'%" y1="'+j/c*100+'%" x2="'+h/b*100+'%" y2="'+l/c*100+'%">'];for(m=0;m<g;m++)b.push('<stop offset="'+n[m]/i+'" stop-color="'+f[m].color.Ca(d)+'" stop-opacity="'+f[m].color.ab()+'"/>');b.push('</linearGradient></defs><rect width="100%" height="100%" fill="url(#g)"/></svg>');return b.join("")},k:function(){this.parent.cc(this.zb)}});
e.jd=e.C.ja({M:"repeat",Jd:"stretch",Id:"round",zb:0,ca:function(){return this.j.v.W()},i:function(){return this.j.v.i()},ha:function(){var a=this,b=a.j.v.n(),c=a.j.H.n(),d=a.I.p(),f=b.repeat,g=f.f,i=f.bd,j=a.e,h=0;e.O.dc(b.src,function(l){function n(T,U,W,Y,X,R,s,w,J,P){F.push('<pattern patternUnits="userSpaceOnUse" id="pattern'+S+'" x="'+(g===r?T+W/2-J/2:T)+'" y="'+(i===r?U+Y/2-P/2:U)+'" width="'+J+'" height="'+P+'"><svg width="'+J+'" height="'+P+'" viewBox="'+X+" "+R+" "+s+" "+w+'" preserveAspectRatio="none"><image xlink:href="'+
q+'" x="0" y="0" width="'+v+'" height="'+k+'" /></svg></pattern>');O.push('<rect x="'+T+'" y="'+U+'" width="'+W+'" height="'+Y+'" fill="url(#pattern'+S+')" />');S++}var m=d.g,p=d.f,v=l.g,k=l.f,q=a.Yd(b.src,v,k),r=a.M,u=a.Jd;l=a.Id;var t=Math.ceil,o=e.m("0"),x=b.ka||(c?c.ka:{t:o,r:o,b:o,l:o});o=x.t.a(j);var y=x.r.a(j),A=x.b.a(j);x=x.l.a(j);var C=b.slice,E=C.t.a(j),K=C.r.a(j),G=C.b.a(j);C=C.l.a(j);var D=m-x-y,z=p-o-A,Q=v-C-K,V=k-E-G,H=g===u?D:Q*o/E,I=i===u?z:V*y/K,B=g===u?D:Q*A/G;u=i===u?z:V*x/C;var F=
[],O=[],S=0;if(g===l){H-=(H-(D%H||H))/t(D/H);B-=(B-(D%B||B))/t(D/B)}if(i===l){I-=(I-(z%I||I))/t(z/I);u-=(u-(z%u||u))/t(z/u)}l=['<svg width="'+m+'" height="'+p+'" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">'];n(0,0,x,o,0,0,C,E,x,o);n(x,0,D,o,C,0,Q,E,H,o);n(m-y,0,y,o,v-K,0,K,E,y,o);n(0,o,x,z,0,E,C,V,x,u);if(b.fill)n(x,o,D,z,C,E,Q,V,H||B||Q,u||I||V);n(m-y,o,y,z,v-K,E,K,V,y,I);n(0,p-A,x,A,0,k-G,C,G,x,A);n(x,p-A,D,A,C,k-G,Q,G,B,A);n(m-y,p-A,y,A,v-K,k-G,K,G,y,A);l.push("<defs>"+
F.join("\n")+"</defs>"+O.join("\n")+"</svg>");a.parent.cc(a.zb,"url(data:image/svg+xml,"+escape(l.join(""))+") no-repeat border-box border-box");h&&a.parent.kb()},a);h=1},Yd:function(){var a={};return function(b,c,d){var f=a[b],g;if(!f){f=new Image;g=L.createElement("canvas");f.src=b;g.width=c;g.height=d;g.getContext("2d").drawImage(f,0,0);f=a[b]=g.toDataURL()}return f}}(),Ta:e.gc.prototype.Ta,k:function(){var a=this.e.runtimeStyle;this.parent.cc(this.zb);a.borderColor=a.borderStyle=a.borderWidth=
""}});e.Va=function(){function a(k,q){k.className+=" "+q}function b(k){var q=v.slice.call(arguments,1),r=q.length;setTimeout(function(){for(;r--;)a(k,q[r])},0)}function c(k){var q=v.slice.call(arguments,1),r=q.length;setTimeout(function(){for(;r--;){var u=q[r];u=p[u]||(p[u]=new RegExp("\\b"+u+"\\b","g"));k.className=k.className.replace(u,"")}},0)}function d(k){function q(){if(!T){var s,w,J=e.T,P=k.currentStyle,M=P.getAttribute(g)==="true";R=P.getAttribute(i);R=J>7?R!=="false":R==="true";if(!S){S=
1;k.runtimeStyle.zoom=1;P=k;for(var ba=1;P=P.previousSibling;)if(P.nodeType===1){ba=0;break}ba&&a(k,n)}B.Ga();if(M&&(w=B.p())&&(s=L.documentElement||L.body)&&(w.y>s.clientHeight||w.x>s.clientWidth||w.y+w.f<0||w.x+w.g<0)){if(!Y){Y=1;e.Xa.Q(q)}}else{T=1;Y=S=0;e.Xa.ea(q);if(J===9){F={D:new e.pb(k),v:new e.Pb(k),H:new e.Rb(k)};O=[F.D,F.v];I=new e.kd(k,B,F);s=[new e.hd(k,B,F,I),new e.jd(k,B,F,I)]}else{F={D:new e.pb(k),H:new e.Rb(k),v:new e.Pb(k),S:new e.Qb(k),Na:new e.gd(k),Nb:new e.nd(k)};O=[F.D,F.H,
F.v,F.S,F.Na,F.Nb];I=new e.md(k,B,F);s=[new e.fd(k,B,F,I),new e.fc(k,B,F,I),new e.ed(k,B,F,I),new e.gc(k,B,F,I)];k.tagName==="IMG"&&s.push(new e.ld(k,B,F,I));I.od=s}H=[I].concat(s);if(s=k.currentStyle.getAttribute(e.z+"watch-ancestors")){s=parseInt(s,10);w=0;for(M=k.parentNode;M&&(s==="NaN"||w++<s);){z(M,"onpropertychange",K);z(M,"onmouseenter",o);z(M,"onmouseleave",x);z(M,"onmousedown",y);if(M.tagName in e.Ab){z(M,"onfocus",C);z(M,"onblur",E)}M=M.parentNode}}if(R){e.qa.Q(u);e.qa.Qc()}u(1)}if(!U){U=
1;J<9&&z(k,"onmove",r);z(k,"onresize",r);z(k,"onpropertychange",t);z(k,"onmouseenter",o);z(k,"onmouseleave",x);z(k,"onmousedown",y);if(k.tagName in e.Ab){z(k,"onfocus",C);z(k,"onblur",E)}e.ta.Q(r);e.L.Q(Q)}B.Ia()}}function r(){B&&B.Ec()&&u()}function u(s){if(!X)if(T){var w,J=H.length;G();for(w=0;w<J;w++)H[w].Ta();if(s||B.Mc())for(w=0;w<J;w++)H[w].ib();if(s||B.Sc())for(w=0;w<J;w++)H[w].Mb();I.kb();D()}else S||q()}function t(){var s,w=H.length,J;s=event;if(!X&&!(s&&s.propertyName in m))if(T){G();for(s=
0;s<w;s++)H[s].Ta();for(s=0;s<w;s++){J=H[s];J.mb||J.ib();J.ca()&&J.Lb()}I.kb();D()}else S||q()}function o(){b(k,j)}function x(){c(k,j,h)}function y(){b(k,h);e.tb.Q(A)}function A(){c(k,h);e.tb.ea(A)}function C(){b(k,l)}function E(){c(k,l)}function K(){var s=event.propertyName;if(s==="className"||s==="id")t()}function G(){B.Ga();for(var s=O.length;s--;)O[s].Ga()}function D(){for(var s=O.length;s--;)O[s].Ia();B.Ia()}function z(s,w,J){s.attachEvent(w,J);W.push([s,w,J])}function Q(){if(U){for(var s=W.length,
w;s--;){w=W[s];w[0].detachEvent(w[1],w[2])}e.L.ea(Q);U=0;W=[]}}function V(){if(!X){var s,w;Q();X=1;if(H){s=0;for(w=H.length;s<w;s++){H[s].Ac=1;H[s].k()}}R&&e.qa.ea(u);e.ta.ea(u);H=B=F=O=k=null}}var H,I,B=new e.qb(k),F,O,S,T,U,W=[],Y,X,R;this.Gc=q;this.update=u;this.k=V;this.zc=k}var f={},g=e.z+"lazy-init",i=e.z+"poll",j=e.oa+"hover",h=e.oa+"active",l=e.oa+"focus",n=e.oa+"first-child",m={background:1,bgColor:1,display:1},p={},v=[];d.Cc=function(k){var q=e.O.aa(k);return f[q]||(f[q]=new d(k))};d.k=
function(k){k=e.O.aa(k);var q=f[k];if(q){q.k();delete f[k]}};d.yc=function(){var k=[],q;if(f){for(var r in f)if(f.hasOwnProperty(r)){q=f[r];k.push(q.zc);q.k()}f={}}return k};return d}();e.version="1.0beta6-SNAPSHOT";e.supportsVML=e.Kb;e.attach=function(a){if(e.T===9||e.T<9&&e.Kb)e.Va.Cc(a).Gc()};e.detach=function(a){e.Va.k(a)}})(window,document);
