(function(O,P){var d=O.PIE||(O.PIE={});d.ya=function(b){var a,c,e,f,h=arguments;a=1;for(c=h.length;a<c;a++){f=h[a];for(e in f)if(f.hasOwnProperty(e))b[e]=f[e]}return b};d.ya(d,{q:"-pie-",Ia:"Pie",fa:"pie_",Pc:{TD:1,TH:1},bc:{TABLE:1,THEAD:1,TBODY:1,TFOOT:1,TR:1,INPUT:1,TEXTAREA:1,SELECT:1,OPTION:1,IMG:1,HR:1},tb:{A:1,INPUT:1,TEXTAREA:1,SELECT:1,BUTTON:1},od:{submit:1,button:1,reset:1},wa:function(){}});try{P.execCommand("BackgroundImageCache",false,true)}catch(Y){}(function(){for(var b=4,a=P.createElement("div"),
c=a.getElementsByTagName("i");a.innerHTML="<!--[if gt IE "+ ++b+"]><i></i><![endif]--\>",c[0];);d.wb=b;if(b===6)d.q=d.q.replace(/^-/,"");d.O=P.documentMode||d.wb;a.innerHTML='<v:shape adj="1"/>';b=a.firstChild;b.style.behavior="url(#default#VML)";d.Cb=typeof b.adj==="object"})();(function(){var b=0,a={};d.M={Y:function(c){return c&&c.uniqueID||c._pieId||(c._pieId="_"+b++)},Uc:function(c,e,f){var h=a[c],g,j;if(h)Object.prototype.toString.call(h)==="[object Array]"?h.push([e,f]):e.call(f,h);else{j=
a[c]=[[e,f]];g=new Image;g.onload=function(){h=a[c]={g:g.width,f:g.height};for(var i=0,o=j.length;i<o;i++)j[i][0].call(j[i][1],h);g.onload=null};g.src=c}}}})();d.Ea={kc:function(b,a,c,e){function f(){o=g>=90&&g<270?a:0;n=g<180?c:0;l=a-o;p=c-n}function h(){for(;g<0;)g+=360;g%=360}var g=e.qa;e=e.Sa;var j,i,o,n,l,p,v,k;if(e){e=e.coords(b,a,c);j=e.x;i=e.y}if(g){g=g.ec();h();f();if(!e){j=o;i=n}e=d.Ea.Dc(j,i,g,l,p);b=e[0];e=e[1]}else if(e){b=a-j;e=c-i}else{j=i=b=0;e=c}v=b-j;k=e-i;if(g===void 0){g=!v?k<
0?90:270:!k?v<0?180:0:-Math.atan2(k,v)/Math.PI*180;h();f()}return{qa:g,Mc:j,Nc:i,hc:b,ic:e,rd:o,sd:n,ld:l,md:p,hd:v,jd:k,yc:d.Ea.gc(j,i,b,e)}},Dc:function(b,a,c,e,f){if(c===0||c===180)return[e,a];else if(c===90||c===270)return[b,f];else{c=Math.tan(-c*Math.PI/180);b=c*b-a;a=-1/c;e=a*e-f;f=a-c;return[(e-b)/f,(c*e-a*b)/f]}},gc:function(b,a,c,e){b=c-b;a=e-a;return Math.abs(b===0?a:a===0?b:Math.sqrt(b*b+a*a))}};d.L=function(){this.Za=[];this.yb={}};d.L.prototype={J:function(b){var a=d.M.Y(b),c=this.yb,
e=this.Za;if(!(a in c)){c[a]=e.length;e.push(b)}},$:function(b){b=d.M.Y(b);var a=this.yb;if(b&&b in a){delete this.Za[a[b]];delete a[b]}},U:function(){for(var b=this.Za,a=b.length;a--;)b[a]&&b[a]()}};d.ha=new d.L;d.ha.Hc=function(){var b=this;if(!b.Ic){setInterval(function(){b.U()},250);b.Ic=1}};(function(){function b(){d.n.U();O.detachEvent("onunload",b);O.PIE=null}d.n=new d.L;O.attachEvent("onunload",b);d.n.R=function(a,c,e){a.attachEvent(c,e);this.J(function(){a.detachEvent(c,e)})}})();d.ka=new d.L;
d.n.R(O,"onresize",function(){d.ka.U()});(function(){function b(){d.Ha.U()}d.Ha=new d.L;d.n.R(O,"onscroll",b);d.ka.J(b)})();(function(){function b(){c=d.Da.fc()}function a(){if(c){for(var e=0,f=c.length;e<f;e++)d.attach(c[e]);c=0}}var c;d.n.R(O,"onbeforeprint",b);d.n.R(O,"onafterprint",a)})();d.Ga=new d.L;d.n.R(P,"onmouseup",function(){d.Ga.U()});d.bd=function(){function b(i){this.D=i}var a=P.createElement("length-calc"),c=P.documentElement,e=a.style,f={},h=["mm","cm","in","pt","pc"],g=h.length,j=
{};e.position="absolute";e.top=e.left="-9999px";for(c.appendChild(a);g--;){a.style.width="100"+h[g];f[h[g]]=a.offsetWidth/100}c.removeChild(a);a.style.width="1em";b.prototype={cb:/(px|em|ex|mm|cm|in|pt|pc|%)$/,nc:function(){var i=this.Ac;if(i===void 0)i=this.Ac=parseFloat(this.D);return i},Ra:function(){var i=this.Qc;if(!i)i=this.Qc=(i=this.D.match(this.cb))&&i[0]||"px";return i},c:function(i,o){var n=this.nc(),l=this.Ra();switch(l){case "px":return n;case "%":return n*(typeof o==="function"?o():
o)/100;case "em":return n*this.Qa(i);case "ex":return n*this.Qa(i)/2;default:return n*f[l]}},Qa:function(i){var o=i.currentStyle.fontSize,n,l;if(o.indexOf("px")>0)return parseFloat(o);else if(i.tagName in d.bc){l=this;n=i.parentNode;return d.h(o).c(n,function(){return l.Qa(n)})}else{i.appendChild(a);o=a.offsetWidth;a.parentNode===i&&i.removeChild(a);return o}}};b.qd=function(i){return i/f.pt};d.h=function(i){return j[i]||(j[i]=new b(i))};return b}();d.da=function(){function b(f){this.C=f}var a=d.h("50%"),
c={top:1,center:1,bottom:1},e={left:1,center:1,right:1};b.prototype={oc:function(){if(!this.nb){var f=this.C,h=f.length,g=d.o,j=g.Ka,i=d.h("0");j=j.ia;i=["left",i,"top",i];if(h===1){f.push(new g.Ja(j,"center"));h++}if(h===2){j&(f[0].e|f[1].e)&&f[0].a in c&&f[1].a in e&&f.push(f.shift());if(f[0].e&j)if(f[0].a==="center")i[1]=a;else i[0]=f[0].a;else if(f[0].I())i[1]=d.h(f[0].a);if(f[1].e&j)if(f[1].a==="center")i[3]=a;else i[2]=f[1].a;else if(f[1].I())i[3]=d.h(f[1].a)}this.nb=i}return this.nb},coords:function(f,
h,g){var j=this.oc(),i=j[1].c(f,h);f=j[3].c(f,g);return{x:j[0]==="right"?h-i:i,y:j[2]==="bottom"?g-f:f}}};return b}();d.ea=function(){function b(a,c){this.g=a;this.f=c}b.prototype={c:function(a,c,e,f,h){var g=this.g,j=this.f,i=c/e;f=f/h;if(g==="contain"){g=f>i?c:e*f;j=f>i?c/f:e}else if(g==="cover"){g=f<i?c:e*f;j=f<i?c/f:e}else if(g==="auto"){j=j==="auto"?h:j.c(a,e);g=j*f}else{g=g.c(a,c);j=j==="auto"?g/f:j.c(a,e)}return{g:g,f:j}}};b.Jb=new b("auto","auto");return b}();d.Hb=function(){function b(a){this.D=
a}b.prototype={cb:/[a-z]+$/i,Ra:function(){return this.Wb||(this.Wb=this.D.match(this.cb)[0].toLowerCase())},ec:function(){var a=this.Rb,c;if(a===undefined){a=this.Ra();c=parseFloat(this.D,10);a=this.Rb=a==="deg"?c:a==="rad"?c/Math.PI*180:a==="grad"?c/400*360:a==="turn"?c*360:0}return a}};return b}();d.Ib=function(){function b(c){this.D=c}var a={};b.Gc=/\s*rgba\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d+|\d*\.\d+)\s*\)\s*/;b.Va={aliceblue:"F0F8FF",antiquewhite:"FAEBD7",aqua:"0FF",aquamarine:"7FFFD4",
azure:"F0FFFF",beige:"F5F5DC",bisque:"FFE4C4",black:"000",blanchedalmond:"FFEBCD",blue:"00F",blueviolet:"8A2BE2",brown:"A52A2A",burlywood:"DEB887",cadetblue:"5F9EA0",chartreuse:"7FFF00",chocolate:"D2691E",coral:"FF7F50",cornflowerblue:"6495ED",cornsilk:"FFF8DC",crimson:"DC143C",cyan:"0FF",darkblue:"00008B",darkcyan:"008B8B",darkgoldenrod:"B8860B",darkgray:"A9A9A9",darkgreen:"006400",darkkhaki:"BDB76B",darkmagenta:"8B008B",darkolivegreen:"556B2F",darkorange:"FF8C00",darkorchid:"9932CC",darkred:"8B0000",
darksalmon:"E9967A",darkseagreen:"8FBC8F",darkslateblue:"483D8B",darkslategray:"2F4F4F",darkturquoise:"00CED1",darkviolet:"9400D3",deeppink:"FF1493",deepskyblue:"00BFFF",dimgray:"696969",dodgerblue:"1E90FF",firebrick:"B22222",floralwhite:"FFFAF0",forestgreen:"228B22",fuchsia:"F0F",gainsboro:"DCDCDC",ghostwhite:"F8F8FF",gold:"FFD700",goldenrod:"DAA520",gray:"808080",green:"008000",greenyellow:"ADFF2F",honeydew:"F0FFF0",hotpink:"FF69B4",indianred:"CD5C5C",indigo:"4B0082",ivory:"FFFFF0",khaki:"F0E68C",
lavender:"E6E6FA",lavenderblush:"FFF0F5",lawngreen:"7CFC00",lemonchiffon:"FFFACD",lightblue:"ADD8E6",lightcoral:"F08080",lightcyan:"E0FFFF",lightgoldenrodyellow:"FAFAD2",lightgreen:"90EE90",lightgrey:"D3D3D3",lightpink:"FFB6C1",lightsalmon:"FFA07A",lightseagreen:"20B2AA",lightskyblue:"87CEFA",lightslategray:"789",lightsteelblue:"B0C4DE",lightyellow:"FFFFE0",lime:"0F0",limegreen:"32CD32",linen:"FAF0E6",magenta:"F0F",maroon:"800000",mediumauqamarine:"66CDAA",mediumblue:"0000CD",mediumorchid:"BA55D3",
mediumpurple:"9370D8",mediumseagreen:"3CB371",mediumslateblue:"7B68EE",mediumspringgreen:"00FA9A",mediumturquoise:"48D1CC",mediumvioletred:"C71585",midnightblue:"191970",mintcream:"F5FFFA",mistyrose:"FFE4E1",moccasin:"FFE4B5",navajowhite:"FFDEAD",navy:"000080",oldlace:"FDF5E6",olive:"808000",olivedrab:"688E23",orange:"FFA500",orangered:"FF4500",orchid:"DA70D6",palegoldenrod:"EEE8AA",palegreen:"98FB98",paleturquoise:"AFEEEE",palevioletred:"D87093",papayawhip:"FFEFD5",peachpuff:"FFDAB9",peru:"CD853F",
pink:"FFC0CB",plum:"DDA0DD",powderblue:"B0E0E6",purple:"800080",red:"F00",rosybrown:"BC8F8F",royalblue:"4169E1",saddlebrown:"8B4513",salmon:"FA8072",sandybrown:"F4A460",seagreen:"2E8B57",seashell:"FFF5EE",sienna:"A0522D",silver:"C0C0C0",skyblue:"87CEEB",slateblue:"6A5ACD",slategray:"708090",snow:"FFFAFA",springgreen:"00FF7F",steelblue:"4682B4",tan:"D2B48C",teal:"008080",thistle:"D8BFD8",tomato:"FF6347",turquoise:"40E0D0",violet:"EE82EE",wheat:"F5DEB3",white:"FFF",whitesmoke:"F5F5F5",yellow:"FF0",
yellowgreen:"9ACD32"};b.prototype={parse:function(){if(!this.oa){var c=this.D,e;if(e=c.match(b.Gc)){this.oa="rgb("+e[1]+","+e[2]+","+e[3]+")";this.kb=parseFloat(e[4])}else{if((e=c.toLowerCase())in b.Va)c="#"+b.Va[e];this.oa=c;this.kb=c==="transparent"?0:1}}},dc:function(c){this.parse();return this.oa==="currentColor"?c.currentStyle.color:this.oa},Xb:function(){this.parse();return this.kb}};d.W=function(c){return a[c]||(a[c]=new b(c))};return b}();d.o=function(){function b(c){this.va=c;this.ch=0;this.C=
[];this.Z=0}var a=b.Ka={ca:1,ib:2,i:4,Kb:8,jb:16,ia:32,m:64,Q:128,Fa:256,la:512,Qb:1024,URL:2048};b.Ja=function(c,e){this.e=c;this.a=e};b.Ja.prototype={Ua:function(){return this.e&a.m||this.e&a.Q&&this.a==="0"},I:function(){return this.Ua()||this.e&a.la}};b.prototype={Tc:/\s/,Bc:/^[\+\-]?(\d*\.)?\d+/,url:/^url\(\s*("([^"]*)"|'([^']*)'|([!#$%&*-~]*))\s*\)/i,vb:/^\-?[_a-z][\w-]*/i,Oc:/^("([^"]*)"|'([^']*)')/,rc:/^#([\da-f]{6}|[\da-f]{3})/i,Rc:{px:a.m,em:a.m,ex:a.m,mm:a.m,cm:a.m,"in":a.m,pt:a.m,pc:a.m,
deg:a.ca,rad:a.ca,grad:a.ca},cc:{rgb:1,rgba:1,hsl:1,hsla:1},next:function(c){function e(p,v){p=new b.Ja(p,v);if(!c){o.C.push(p);o.Z++}return p}function f(){o.Z++;return null}var h,g,j,i,o=this;if(this.Z<this.C.length)return this.C[this.Z++];for(;this.Tc.test(this.va.charAt(this.ch));)this.ch++;if(this.ch>=this.va.length)return f();g=this.ch;h=this.va.substring(this.ch);j=h.charAt(0);switch(j){case "#":if(i=h.match(this.rc)){this.ch+=i[0].length;return e(a.i,i[0])}break;case '"':case "'":if(i=h.match(this.Oc)){this.ch+=
i[0].length;return e(a.Qb,i[2]||i[3]||"")}break;case "/":case ",":this.ch++;return e(a.Fa,j);case "u":if(i=h.match(this.url)){this.ch+=i[0].length;return e(a.URL,i[2]||i[3]||i[4]||"")}}if(i=h.match(this.Bc)){j=i[0];this.ch+=j.length;if(h.charAt(j.length)==="%"){this.ch++;return e(a.la,j+"%")}if(i=h.substring(j.length).match(this.vb)){j+=i[0];this.ch+=i[0].length;return e(this.Rc[i[0].toLowerCase()]||a.Kb,j)}return e(a.Q,j)}if(i=h.match(this.vb)){j=i[0];this.ch+=j.length;if(j.toLowerCase()in d.Ib.Va||
j==="currentColor"||j==="transparent")return e(a.i,j);if(h.charAt(j.length)==="("){this.ch++;if(j.toLowerCase()in this.cc){h=function(p){return p&&p.e&a.Q};i=function(p){return p&&p.e&(a.Q|a.la)};var n=function(p,v){return p&&p.a===v},l=function(){return o.next(1)};if((j.charAt(0)==="r"?i(l()):h(l()))&&n(l(),",")&&i(l())&&n(l(),",")&&i(l())&&(j==="rgb"||j==="hsa"||n(l(),",")&&h(l()))&&n(l(),")"))return e(a.i,this.va.substring(g,this.ch));return f()}return e(a.jb,j)}return e(a.ia,j)}this.ch++;return e(a.ib,
j)},j:function(){return this.C[this.Z-- -2]},all:function(){for(;this.next(););return this.C},aa:function(c,e){for(var f=[],h,g;h=this.next();){if(c(h)){g=true;this.j();break}f.push(h)}return e&&!g?null:f}};return b}();d.hb=function(b){this.d=b};d.hb.prototype={F:0,Ec:function(){var b=this.Ma,a;return!b||(a=this.V())&&(b.x!==a.x||b.y!==a.y)},Kc:function(){var b=this.Ma,a;return!b||(a=this.V())&&(b.g!==a.g||b.f!==a.f)},ub:function(){var b=this.d,a=b.getBoundingClientRect(),c=d.O===9;return{x:a.left,
y:a.top,g:c?b.offsetWidth:a.right-a.left,f:c?b.offsetHeight:a.bottom-a.top}},V:function(){return this.F?this.pa||(this.pa=this.ub()):this.ub()},qc:function(){return!!this.Ma},xa:function(){++this.F},Ca:function(){if(!--this.F){if(this.pa)this.Ma=this.pa;this.pa=null}}};(function(){function b(a){var c=d.M.Y(a);return function(){if(this.F){var e=this.mb||(this.mb={});return c in e?e[c]:(e[c]=a.call(this))}else return a.call(this)}}d.v={F:0,Ya:function(a){function c(e){this.d=e;this.lb=this.X()}d.ya(c.prototype,
d.v,a);c.Vb={};return c},H:function(){var a=this.X(),c=this.constructor.Vb;return a?a in c?c[a]:(c[a]=this.ab(a)):null},X:b(function(){var a=this.d,c=this.constructor,e=a.style;a=a.currentStyle;var f=this.Oa,h=this.bb,g=c.Tb||(c.Tb=d.q+f);c=c.Ub||(c.Ub=d.Ia+h.charAt(0).toUpperCase()+h.substring(1));return e[c]||a.getAttribute(g)||e[h]||a.getAttribute(f)}),B:b(function(){return!!this.H()}),qb:b(function(){var a=this.X(),c=a!==this.lb;this.lb=a;return c}),ua:b,xa:function(){++this.F},Ca:function(){--this.F||
delete this.mb}}})();d.eb=d.v.Ya({Oa:d.q+"background",bb:d.Ia+"Background",Yb:{scroll:1,fixed:1,local:1},Aa:{"repeat-x":1,"repeat-y":1,repeat:1,"no-repeat":1},Ab:{"padding-box":1,"border-box":1,"content-box":1},Fc:{top:1,right:1,bottom:1,left:1,center:1},Lc:{contain:1,cover:1},za:{ga:"backgroundClip",i:"backgroundColor",K:"backgroundImage",ja:"backgroundOrigin",s:"backgroundPosition",u:"backgroundRepeat",na:"backgroundSize"},ab:function(b){function a(t){return t&&t.I()||t.e&o&&t.a in k}function c(t){return t&&
(t.I()&&d.h(t.a)||t.a==="auto"&&"auto")}var e=this.d.currentStyle,f,h,g,j=d.o.Ka,i=j.Fa,o=j.ia,n=j.i,l,p,v=0,k=this.Fc,q,m,r={G:[]};if(this.Pa()){f=new d.o(b);for(g={};h=f.next();){l=h.e;p=h.a;if(!g.z&&l&j.jb&&p==="linear-gradient"){q={P:[],z:p};for(m={};h=f.next();){l=h.e;p=h.a;if(l&j.ib&&p===")"){m.color&&q.P.push(m);q.P.length>1&&d.ya(g,q);break}if(l&n){if(q.qa||q.Sa){h=f.j();if(h.e!==i)break;f.next()}m={color:d.W(p)};h=f.next();if(h.I())m.zb=d.h(h.a);else f.j()}else if(l&j.ca&&!q.qa&&!m.color&&
!q.P.length)q.qa=new d.Hb(h.a);else if(a(h)&&!q.Sa&&!m.color&&!q.P.length){f.j();q.Sa=new d.da(f.aa(function(t){return!a(t)},false))}else if(l&i&&p===","){if(m.color){q.P.push(m);m={}}}else break}}else if(!g.z&&l&j.URL){g.xb=p;g.z="image"}else if(a(h)&&!g.T){f.j();g.T=new d.da(f.aa(function(t){return!a(t)},false))}else if(l&o)if(p in this.Aa&&!g.Ta)g.Ta=p;else if(p in this.Ab&&!g.ra){g.ra=p;if((h=f.next())&&h.e&o&&h.a in this.Ab)g.Na=h.a;else{g.Na=p;f.j()}}else if(p in this.Yb&&!g.ob)g.ob=p;else return null;
else if(l&n&&!r.color)r.color=d.W(p);else if(l&i&&p==="/"&&!g.sa&&g.T){h=f.next();if(h.e&o&&h.a in this.Lc)g.sa=new d.ea(h.a);else if(h=c(h)){l=c(f.next());if(!l){l=h;f.j()}g.sa=new d.ea(h,l)}else return null}else if(l&i&&p===","&&g.z){g.$a=b.substring(v,f.ch-1);v=f.ch;r.G.push(g);g={}}else return null}if(g.z){g.$a=b.substring(v);r.G.push(g)}}else this.Fb(d.O<9?function(){var t=this.za,s=e[t.s+"X"],z=e[t.s+"Y"],C=e[t.K],D=e[t.i];if(D!=="transparent")r.color=d.W(D);if(C!=="none")r.G=[{z:"image",xb:(new d.o(C)).next().a,
Ta:e[t.u],T:new d.da((new d.o(s+" "+z)).all())}]}:function(){var t=this.za,s=/\s*,\s*/,z=e[t.K].split(s),C=e[t.i],D,E,J,L,w,I;if(C!=="transparent")r.color=d.W(C);if((L=z.length)&&z[0]!=="none"){C=e[t.u].split(s);D=e[t.s].split(s);E=e[t.ja].split(s);J=e[t.ga].split(s);t=e[t.na].split(s);r.G=[];for(s=0;s<L;s++)if((w=z[s])&&w!=="none"){I=t[s].split(" ");r.G.push({$a:w+" "+C[s]+" "+D[s]+" / "+t[s]+" "+E[s]+" "+J[s],z:"image",xb:(new d.o(w)).next().a,Ta:C[s],T:new d.da((new d.o(D[s])).all()),ra:E[s],Na:J[s],
sa:new d.ea(I[0],I[1])})}}});return r.color||r.G[0]?r:null},Fb:function(b){var a=d.O>8,c=this.za,e=this.d.runtimeStyle,f=e[c.K],h=e[c.i],g=e[c.u],j,i,o,n;if(f)e[c.K]="";if(h)e[c.i]="";if(g)e[c.u]="";if(a){j=e[c.ga];i=e[c.ja];n=e[c.s];o=e[c.na];if(j)e[c.ga]="";if(i)e[c.ja]="";if(n)e[c.s]="";if(o)e[c.na]=""}b=b.call(this);if(f)e[c.K]=f;if(h)e[c.i]=h;if(g)e[c.u]=g;if(a){if(j)e[c.ga]=j;if(i)e[c.ja]=i;if(n)e[c.s]=n;if(o)e[c.na]=o}return b},X:d.v.ua(function(){return this.Pa()||this.Fb(function(){var b=
this.d.currentStyle,a=this.za;return b[a.i]+" "+b[a.K]+" "+b[a.u]+" "+b[a.s+"X"]+" "+b[a.s+"Y"]})}),Pa:d.v.ua(function(){var b=this.d;return b.style[this.bb]||b.currentStyle.getAttribute(this.Oa)}),jc:function(b,a,c){var e=this.d,f=a.V();a=f.g;f=f.f;if(b!=="border-box")if((c=c.H())&&(c=c.ba)){a-=c.l.c(e)+c.l.c(e);f-=c.t.c(e)+c.b.c(e)}if(b==="content-box"){b=d.h;c=e.currentStyle;a-=b(c.paddingLeft).c(e)+b(c.paddingRight).c(e);f-=b(c.paddingTop).c(e)+b(c.paddingBottom).c(e)}return{g:a,f:f}},wc:function(){var b=
0;if(d.wb<7){b=this.d;b=""+(b.style[d.Ia+"PngFix"]||b.currentStyle.getAttribute(d.q+"png-fix"))==="true"}return b},B:d.v.ua(function(){return(this.Pa()||this.wc())&&!!this.H()})});d.gb=d.v.Ya({Jc:["Top","Right","Bottom","Left"],zc:{thin:"1px",medium:"3px",thick:"5px"},ab:function(){var b={},a={},c={},e=false,f=true,h=true,g=true;this.Gb(function(){for(var j=this.d.currentStyle,i=0,o,n,l,p,v,k,q;i<4;i++){l=this.Jc[i];q=l.charAt(0).toLowerCase();o=a[q]=j["border"+l+"Style"];n=j["border"+l+"Color"];
l=j["border"+l+"Width"];if(i>0){if(o!==p)h=false;if(n!==v)f=false;if(l!==k)g=false}p=o;v=n;k=l;c[q]=d.W(n);l=b[q]=d.h(a[q]==="none"?"0":this.zc[l]||l);if(l.c(this.d)>0)e=true}});return e?{ba:b,td:a,fd:c,wd:g,gd:f,ud:h}:null},X:d.v.ua(function(){var b=this.d,a=b.currentStyle,c;b.tagName in d.Pc&&b.offsetParent.currentStyle.borderCollapse==="collapse"||this.Gb(function(){c=a.borderWidth+"|"+a.borderStyle+"|"+a.borderColor});return c}),Gb:function(b){var a=this.d.runtimeStyle,c=a.borderWidth,e=a.borderColor;
if(c)a.borderWidth="";if(e)a.borderColor="";b=b.call(this);if(c)a.borderWidth=c;if(e)a.borderColor=e;return b}});d.fb=d.v.Ya({Oa:"border-image",bb:"borderImage",Aa:{stretch:1,round:1,repeat:1,space:1},ab:function(b){var a=null,c,e,f,h,g,j,i=0,o=d.o.Ka,n=o.ia,l=o.Q,p=o.la;if(b){c=new d.o(b);a={};for(var v=function(m){return m&&m.e&o.Fa&&m.a==="/"},k=function(m){return m&&m.e&n&&m.a==="fill"},q=function(){h=c.aa(function(m){return!(m.e&(l|p))});if(k(c.next())&&!a.fill)a.fill=true;else c.j();if(v(c.next())){i++;
g=c.aa(function(m){return!m.I()&&!(m.e&n&&m.a==="auto")});if(v(c.next())){i++;j=c.aa(function(m){return!m.Ua()})}}else c.j()};b=c.next();){e=b.e;f=b.a;if(e&(l|p)&&!h){c.j();q()}else if(k(b)&&!a.fill){a.fill=true;q()}else if(e&n&&this.Aa[f]&&!a.repeat){a.repeat={f:f};if(b=c.next())if(b.e&n&&this.Aa[b.a])a.repeat.db=b.a;else c.j()}else if(e&o.URL&&!a.src)a.src=f;else return null}if(!a.src||!h||h.length<1||h.length>4||g&&g.length>4||i===1&&g.length<1||j&&j.length>4||i===2&&j.length<1)return null;if(!a.repeat)a.repeat=
{f:"stretch"};if(!a.repeat.db)a.repeat.db=a.repeat.f;b=function(m,r){return{t:r(m[0]),r:r(m[1]||m[0]),b:r(m[2]||m[0]),l:r(m[3]||m[1]||m[0])}};a.slice=b(h,function(m){return d.h(m.e&l?m.a+"px":m.a)});if(g&&g[0])a.ba=b(g,function(m){return m.I()?d.h(m.a):m.a});if(j&&j[0])a.pd=b(j,function(m){return m.Ua()?d.h(m.a):m.a})}return a}});d.ma={Xa:function(b){function a(c,e,f,h){this.d=c;this.pb=e;this.p=f;this.parent=h}d.ya(a.prototype,d.ma,b);return a},xc:false,Wa:function(){return false},Bb:d.wa,Eb:function(){this.B()?
this.rb():this.k()},Db:function(){this.xc=true},sc:function(){this.d.runtimeStyle.borderColor="transparent"},k:function(){}};d.Nb=d.ma.Xa({Db:d.wa,Eb:d.wa,vd:d.wa,Cc:/^,+|,+$/g,vc:/,+/g,Ba:function(b,a){(this.La||(this.La=[]))[b]=a||void 0},sb:function(){var b=this.La,a;if(b&&(a=b.join(",").replace(this.Cc,"").replace(this.vc,","))!==this.Sb)this.Sb=this.d.runtimeStyle.background=a},k:function(){this.d.runtimeStyle.background="";delete this.La}});d.Lb=d.ma.Xa({S:1,Wa:function(){return this.p.N.qb()},
B:function(){var b=this.p;return b.N.B()||b.w.B()},rb:function(){var b=this.p.N,a=b.H(),c,e,f=0,h,g;if(a){c=[];if(e=a.G)for(;h=e[f++];)if(h.z==="linear-gradient"){g=b.jc(c.ra,this.pb,this.p.ta);g=(h.sa||d.ea.Jb).c(this.d,g.g,g.f,g.g,g.f);c.push("url(data:image/svg+xml,"+escape(this.lc(h,g.g,g.f))+") "+this.Zb(h.T)+" / "+g.g+"px "+g.f+"px "+(h.ob||"")+" "+(h.ra||"")+" "+(h.Na||""))}else c.push(h.$a);a.color&&c.push(a.color.D);this.parent.Ba(this.S,c.join(","))}},Zb:function(b){return b?b.C.map(function(a){return a.a}).join(" "):
"0 0"},lc:function(b,a,c){var e=this.d,f=b.P,h=f.length,g=d.Ea.kc(e,a,c,b);b=g.Mc;var j=g.Nc,i=g.hc,o=g.ic;g=g.yc;var n,l,p,v,k;n=[];for(l=0;l<h;l++)n.push(f[l].zb?f[l].zb.c(e,g):l===0?0:l===h-1?g:null);for(l=1;l<h;l++)if(n[l]===null){v=n[l-1];p=l;do k=n[++p];while(k===null);n[l]=v+(k-v)/(p-l+1)}a=['<svg width="'+a+'" height="'+c+'" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="g" gradientUnits="userSpaceOnUse" x1="'+b/a*100+'%" y1="'+j/c*100+'%" x2="'+i/a*100+'%" y2="'+o/c*100+'%">'];
for(l=0;l<h;l++)a.push('<stop offset="'+n[l]/g+'" stop-color="'+f[l].color.dc(e)+'" stop-opacity="'+f[l].color.Xb()+'"/>');a.push('</linearGradient></defs><rect width="100%" height="100%" fill="url(#g)"/></svg>');return a.join("")},k:function(){this.parent.Ba(this.S)}});d.Mb=d.ma.Xa({u:"repeat",Pb:"stretch",Ob:"round",S:0,Wa:function(){return this.p.w.qb()},B:function(){return this.p.w.B()},rb:function(){var b=this,a=b.p.w.H(),c=b.p.ta.H(),e=b.pb.V(),f=a.repeat,h=f.f,g=f.db,j=b.d,i=0;d.M.Uc(a.src,
function(o){function n(R,T,V,Q,u,A,B,M,G,W){U.push('<pattern patternUnits="userSpaceOnUse" id="pattern'+S+'" x="'+(h===m?R+V/2-G/2:R)+'" y="'+(g===m?T+Q/2-W/2:T)+'" width="'+G+'" height="'+W+'"><svg width="'+G+'" height="'+W+'" viewBox="'+u+" "+A+" "+B+" "+M+'" preserveAspectRatio="none"><image xlink:href="'+q+'" x="0" y="0" width="'+v+'" height="'+k+'" /></svg></pattern>');X.push('<rect x="'+R+'" y="'+T+'" width="'+V+'" height="'+Q+'" fill="url(#pattern'+S+')" />');S++}var l=e.g,p=e.f,v=o.g,k=o.f,
q=b.tc(a.src,v,k),m=b.u,r=b.Pb;o=b.Ob;var t=Math.ceil,s=d.h("0"),z=a.ba||(c?c.ba:{t:s,r:s,b:s,l:s});s=z.t.c(j);var C=z.r.c(j),D=z.b.c(j);z=z.l.c(j);var E=a.slice,J=E.t.c(j),L=E.r.c(j),w=E.b.c(j);E=E.l.c(j);var I=l-z-C,N=p-s-D,H=v-E-L,F=k-J-w,y=h===r?I:H*s/J,x=g===r?N:F*C/L,K=h===r?I:H*D/w;r=g===r?N:F*z/E;var U=[],X=[],S=0;if(h===o){y-=(y-(I%y||y))/t(I/y);K-=(K-(I%K||K))/t(I/K)}if(g===o){x-=(x-(N%x||x))/t(N/x);r-=(r-(N%r||r))/t(N/r)}o=['<svg width="'+l+'" height="'+p+'" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">'];
n(0,0,z,s,0,0,E,J,z,s);n(z,0,I,s,E,0,H,J,y,s);n(l-C,0,C,s,v-L,0,L,J,C,s);n(0,s,z,N,0,J,E,F,z,r);if(a.fill)n(z,s,I,N,E,J,H,F,y||K||H,r||x||F);n(l-C,s,C,N,v-L,J,L,F,C,x);n(0,p-D,z,D,0,k-w,E,w,z,D);n(z,p-D,I,D,E,k-w,H,w,K,D);n(l-C,p-D,C,D,v-L,k-w,L,w,C,D);o.push("<defs>"+U.join("\n")+"</defs>"+X.join("\n")+"</svg>");b.parent.Ba(b.S,"url(data:image/svg+xml,"+escape(o.join(""))+") no-repeat border-box border-box");i&&b.parent.sb()},b);i=1},tc:function(){var b={};return function(a,c,e){var f=b[a],h;if(!f){f=
new Image;h=P.createElement("canvas");f.src=a;h.width=c;h.height=e;h.getContext("2d").drawImage(f,0,0);f=b[a]=h.toDataURL()}return f}}(),Bb:function(){if(this.B()){var b=this.d,a=b.runtimeStyle,c=this.p.w.H().ba;a.borderStyle="solid";if(c){a.borderTopWidth=c.t.c(b)+"px";a.borderRightWidth=c.r.c(b)+"px";a.borderBottomWidth=c.b.c(b)+"px";a.borderLeftWidth=c.l.c(b)+"px"}this.sc()}},k:function(){var b=this.d.runtimeStyle;this.parent.Ba(this.S);b.borderColor=b.borderStyle=b.borderWidth=""}});d.Da=function(){function b(k,
q){k.className+=" "+q}function a(k){var q=v.slice.call(arguments,1),m=q.length;setTimeout(function(){for(;m--;)b(k,q[m])},0)}function c(k){var q=v.slice.call(arguments,1),m=q.length;setTimeout(function(){for(;m--;){var r=q[m];r=p[r]||(p[r]=new RegExp("\\b"+r+"\\b","g"));k.className=k.className.replace(r,"")}},0)}function e(k){function q(){if(!X){var u,A,B=d.O,M=k.currentStyle,G=M.getAttribute(h)==="true";Q=M.getAttribute(g);Q=B>7?Q!=="false":Q==="true";if(!U){U=1;k.runtimeStyle.zoom=1;M=k;for(var W=
1;M=M.previousSibling;)if(M.nodeType===1){W=0;break}W&&b(k,n)}y.xa();if(G&&(A=y.V())&&(u=P.documentElement||P.body)&&(A.y>u.clientHeight||A.x>u.clientWidth||A.y+A.f<0||A.x+A.g<0)){if(!T){T=1;d.Ha.J(q)}}else{X=1;T=U=0;d.Ha.$(q);if(B===9){x={N:new d.eb(k),w:new d.fb(k),ta:new d.gb(k)};K=[x.N,x.w];F=new d.Nb(k,y,x);u=[new d.Lb(k,y,x,F),new d.Mb(k,y,x,F)]}else{x={N:new d.eb(k),ta:new d.gb(k),w:new d.fb(k),$b:new d.Xc(k),ac:new d.$c(k),Sc:new d.dd(k)};K=[x.N,x.ta,x.w,x.$b,x.ac,x.Sc];F=new d.cd(k,y,x);
u=[new d.Zc(k,y,x,F),new d.Vc(k,y,x,F),new d.Yc(k,y,x,F),new d.Wc(k,y,x,F)];k.tagName==="IMG"&&u.push(new d.ad(k,y,x,F));F.ed=u}H=[F].concat(u);if(u=k.currentStyle.getAttribute(d.q+"watch-ancestors")){u=parseInt(u,10);A=0;for(G=k.parentNode;G&&(u==="NaN"||A++<u);){w(G,"onpropertychange",L);w(G,"onmouseenter",s);w(G,"onmouseleave",z);w(G,"onmousedown",C);if(G.tagName in d.tb){w(G,"onfocus",E);w(G,"onblur",J)}G=G.parentNode}}if(Q){d.ha.J(r);d.ha.Hc()}r(0,1)}if(!S){S=1;B<9&&w(k,"onmove",m);w(k,"onresize",
m);w(k,"onpropertychange",t);w(k,"onmouseenter",s);w(k,"onmouseleave",z);w(k,"onmousedown",C);if(k.tagName in d.tb){w(k,"onfocus",E);w(k,"onblur",J)}d.ka.J(m);d.n.J(I)}y.Ca()}}function m(){y&&y.qc()&&r()}function r(u,A){if(!V)if(X){y.xa();for(var B=K.length;B--;)K[B].xa();var M=H.length,G=y.Kc();for(B=0;B<M;B++)H[B].Bb();if(A||y.Ec())for(B=0;B<M;B++)H[B].Db();for(B=0;B<M;B++)if(A||G||u&&H[B].Wa())H[B].Eb();F.sb();for(u=K.length;u--;)K[u].Ca();y.Ca()}else U||q()}function t(){var u=event;u&&u.propertyName in
l||r(1)}function s(){a(k,j)}function z(){c(k,j,i)}function C(){a(k,i);d.Ga.J(D)}function D(){c(k,i);d.Ga.$(D)}function E(){a(k,o)}function J(){c(k,o)}function L(){var u=event.propertyName;if(u==="className"||u==="id")t()}function w(u,A,B){u.attachEvent(A,B);R.push([u,A,B])}function I(){if(S){for(var u=R.length,A;u--;){A=R[u];A[0].detachEvent(A[1],A[2])}d.n.$(I);S=0;R=[]}}function N(){if(!V){var u,A;I();V=1;if(H){u=0;for(A=H.length;u<A;u++){H[u].nd=1;H[u].k()}}Q&&d.ha.$(r);d.ka.$(r);H=y=x=K=k=null}}
var H,F,y=new d.hb(k),x,K,U,X,S,R=[],T,V,Q;this.uc=q;this.k=N}var f={},h=d.q+"lazy-init",g=d.q+"poll",j=d.fa+"hover",i=d.fa+"active",o=d.fa+"focus",n=d.fa+"first-child",l={background:1,bgColor:1,display:1},p={},v=[];e.mc=function(k){var q=d.M.Y(k);return f[q]||(f[q]=new e(k))};e.k=function(k){k=d.M.Y(k);var q=f[k];if(q){q.k();delete f[k]}};e.fc=function(){var k=[],q;if(f){for(var m in f)if(f.hasOwnProperty(m)){q=f[m];k.push(q.kd);q.k()}f={}}return k};return e}();d.version="1.0beta6-SNAPSHOT";d.supportsVML=
d.Cb;d.attach=function(b){if(d.O===9||d.O<9&&d.Cb)d.Da.mc(b).uc()};d.detach=function(b){d.Da.k(b)}})(window,document);
