(function(O,P){var e=O.PIE||(O.PIE={});e.xa=function(b){var a,d,c,f,g=arguments;a=1;for(d=g.length;a<d;a++){f=g[a];for(c in f)if(f.hasOwnProperty(c))b[c]=f[c]}return b};e.xa(e,{q:"-pie-",Ha:"Pie",fa:"pie_",Uc:{TD:1,TH:1},ec:{TABLE:1,THEAD:1,TBODY:1,TFOOT:1,TR:1,INPUT:1,TEXTAREA:1,SELECT:1,OPTION:1,IMG:1,HR:1},tb:{A:1,INPUT:1,TEXTAREA:1,SELECT:1,BUTTON:1},td:{submit:1,button:1,reset:1},va:function(){}});try{P.execCommand("BackgroundImageCache",false,true)}catch(Y){}(function(){for(var b=4,a=P.createElement("div"),
d=a.getElementsByTagName("i");a.innerHTML="<!--[if gt IE "+ ++b+"]><i></i><![endif]--\>",d[0];);e.wb=b;if(b===6)e.q=e.q.replace(/^-/,"");e.P=P.documentMode||e.wb;a.innerHTML='<v:shape adj="1"/>';b=a.firstChild;b.style.behavior="url(#default#VML)";e.Db=typeof b.adj==="object"})();(function(){var b=0,a={};e.M={Y:function(d){return d&&d.uniqueID||d._pieId||(d._pieId="_"+b++)},Zc:function(d,c,f){var g=a[d],h,j;if(g)Object.prototype.toString.call(g)==="[object Array]"?g.push([c,f]):c.call(f,g);else{j=
a[d]=[[c,f]];h=new Image;h.onload=function(){g=a[d]={g:h.width,f:h.height};for(var i=0,n=j.length;i<n;i++)j[i][0].call(j[i][1],g);h.onload=null};h.src=d}}}})();e.Da={nc:function(b,a,d,c){function f(){n=h>=90&&h<270?a:0;o=h<180?d:0;l=a-n;p=d-o}function g(){for(;h<0;)h+=360;h%=360}var h=c.pa;c=c.Sa;var j,i,n,o,l,p,v,k;if(c){c=c.coords(b,a,d);j=c.x;i=c.y}if(h){h=h.gc();g();f();if(!c){j=n;i=o}c=e.Da.Hc(j,i,h,l,p);b=c[0];c=c[1]}else if(c){b=a-j;c=d-i}else{j=i=b=0;c=d}v=b-j;k=c-i;if(h===void 0){h=!v?k<
0?90:270:!k?v<0?180:0:-Math.atan2(k,v)/Math.PI*180;g();f()}return{pa:h,Rc:j,Sc:i,jc:b,kc:c,wd:n,xd:o,qd:l,rd:p,nd:v,od:k,Cc:e.Da.ic(j,i,b,c)}},Hc:function(b,a,d,c,f){if(d===0||d===180)return[c,a];else if(d===90||d===270)return[b,f];else{d=Math.tan(-d*Math.PI/180);b=d*b-a;a=-1/d;c=a*c-f;f=a-d;return[(c-b)/f,(d*c-a*b)/f]}},ic:function(b,a,d,c){b=d-b;a=c-a;return Math.abs(b===0?a:a===0?b:Math.sqrt(b*b+a*a))}};e.L=function(){this.Za=[];this.yb={}};e.L.prototype={J:function(b){var a=e.M.Y(b),d=this.yb,
c=this.Za;if(!(a in d)){d[a]=c.length;c.push(b)}},$:function(b){b=e.M.Y(b);var a=this.yb;if(b&&b in a){delete this.Za[a[b]];delete a[b]}},V:function(){for(var b=this.Za,a=b.length;a--;)b[a]&&b[a]()}};e.ha=new e.L;e.ha.Mc=function(){var b=this;if(!b.Nc){setInterval(function(){b.V()},250);b.Nc=1}};(function(){function b(){e.n.V();O.detachEvent("onunload",b);O.PIE=null}e.n=new e.L;O.attachEvent("onunload",b);e.n.S=function(a,d,c){a.attachEvent(d,c);this.J(function(){a.detachEvent(d,c)})}})();e.ka=new e.L;
e.n.S(O,"onresize",function(){e.ka.V()});(function(){function b(){e.Ga.V()}e.Ga=new e.L;e.n.S(O,"onscroll",b);e.ka.J(b)})();(function(){function b(){d=e.Ca.hc()}function a(){if(d){for(var c=0,f=d.length;c<f;c++)e.attach(d[c]);d=0}}var d;e.n.S(O,"onbeforeprint",b);e.n.S(O,"onafterprint",a)})();e.Fa=new e.L;e.n.S(P,"onmouseup",function(){e.Fa.V()});e.gd=function(){function b(i){this.D=i}var a=P.createElement("length-calc"),d=P.body,c=a.style,f={},g=["mm","cm","in","pt","pc"],h=g.length,j={};c.position=
"absolute";c.top=c.left="-9999px";for(d.appendChild(a);h--;){c.width="100"+g[h];f[g[h]]=a.offsetWidth/100}d.removeChild(a);c.width="1em";b.prototype={cb:/(px|em|ex|mm|cm|in|pt|pc|%)$/,rc:function(){var i=this.Ec;if(i===void 0)i=this.Ec=parseFloat(this.D);return i},Ra:function(){var i=this.Vc;if(!i)i=this.Vc=(i=this.D.match(this.cb))&&i[0]||"px";return i},c:function(i,n){var o=this.rc(),l=this.Ra();switch(l){case "px":return o;case "%":return o*(typeof n==="function"?n():n)/100;case "em":return o*
this.Qa(i);case "ex":return o*this.Qa(i)/2;default:return o*f[l]}},Qa:function(i){var n=i.currentStyle.fontSize,o,l;if(n.indexOf("px")>0)return parseFloat(n);else if(i.tagName in e.ec){l=this;o=i.parentNode;return e.h(n).c(o,function(){return l.Qa(o)})}else{i.appendChild(a);n=a.offsetWidth;a.parentNode===i&&i.removeChild(a);return n}}};b.vd=function(i){return i/f.pt};e.h=function(i){return j[i]||(j[i]=new b(i))};return b}();e.da=function(){function b(f){this.C=f}var a=e.h("50%"),d={top:1,center:1,
bottom:1},c={left:1,center:1,right:1};b.prototype={sc:function(){if(!this.mb){var f=this.C,g=f.length,h=e.o,j=h.Ja,i=e.h("0");j=j.ia;i=["left",i,"top",i];if(g===1){f.push(new h.Ia(j,"center"));g++}if(g===2){j&(f[0].e|f[1].e)&&f[0].a in d&&f[1].a in c&&f.push(f.shift());if(f[0].e&j)if(f[0].a==="center")i[1]=a;else i[0]=f[0].a;else if(f[0].I())i[1]=e.h(f[0].a);if(f[1].e&j)if(f[1].a==="center")i[3]=a;else i[2]=f[1].a;else if(f[1].I())i[3]=e.h(f[1].a)}this.mb=i}return this.mb},coords:function(f,g,h){var j=
this.sc(),i=j[1].c(f,g);f=j[3].c(f,h);return{x:j[0]==="right"?g-i:i,y:j[2]==="bottom"?h-f:f}}};return b}();e.ea=function(){function b(a,d){this.g=a;this.f=d}b.prototype={c:function(a,d,c,f,g){var h=this.g,j=this.f,i=d/c;f=f/g;if(h==="contain"){h=f>i?d:c*f;j=f>i?d/f:c}else if(h==="cover"){h=f<i?d:c*f;j=f<i?d/f:c}else if(h==="auto"){j=j==="auto"?g:j.c(a,c);h=j*f}else{h=h.c(a,d);j=j==="auto"?h/f:j.c(a,c)}return{g:h,f:j}}};b.Kb=new b("auto","auto");return b}();e.Ib=function(){function b(a){this.D=a}b.prototype=
{cb:/[a-z]+$/i,Ra:function(){return this.Yb||(this.Yb=this.D.match(this.cb)[0].toLowerCase())},gc:function(){var a=this.Tb,d;if(a===undefined){a=this.Ra();d=parseFloat(this.D,10);a=this.Tb=a==="deg"?d:a==="rad"?d/Math.PI*180:a==="grad"?d/400*360:a==="turn"?d*360:0}return a}};return b}();e.Jb=function(){function b(c,f,g){if(g<0)g+=1;else if(g>1)g-=1;return 255*(6*g<1?c+(f-c)*g*6:2*g<1?f:3*g<2?c+(f-c)*(2/3-g)*6:c)}function a(c){this.D=c}var d={};a.Lc=/\s*rgba?\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*(,\s*(\d+|\d*\.\d+))?\s*\)\s*/;
a.wc=/\s*hsla?\(\s*(\d*\.?\d+)\s*,\s*(\d{1,3})%\s*,\s*(\d{1,3})%\s*(,\s*(\d+|\d*\.\d+))?\s*\)\s*/;a.Va={aliceblue:"F0F8FF",antiquewhite:"FAEBD7",aqua:"0FF",aquamarine:"7FFFD4",azure:"F0FFFF",beige:"F5F5DC",bisque:"FFE4C4",black:"000",blanchedalmond:"FFEBCD",blue:"00F",blueviolet:"8A2BE2",brown:"A52A2A",burlywood:"DEB887",cadetblue:"5F9EA0",chartreuse:"7FFF00",chocolate:"D2691E",coral:"FF7F50",cornflowerblue:"6495ED",cornsilk:"FFF8DC",crimson:"DC143C",cyan:"0FF",darkblue:"00008B",darkcyan:"008B8B",
darkgoldenrod:"B8860B",darkgray:"A9A9A9",darkgreen:"006400",darkkhaki:"BDB76B",darkmagenta:"8B008B",darkolivegreen:"556B2F",darkorange:"FF8C00",darkorchid:"9932CC",darkred:"8B0000",darksalmon:"E9967A",darkseagreen:"8FBC8F",darkslateblue:"483D8B",darkslategray:"2F4F4F",darkturquoise:"00CED1",darkviolet:"9400D3",deeppink:"FF1493",deepskyblue:"00BFFF",dimgray:"696969",dodgerblue:"1E90FF",firebrick:"B22222",floralwhite:"FFFAF0",forestgreen:"228B22",fuchsia:"F0F",gainsboro:"DCDCDC",ghostwhite:"F8F8FF",
gold:"FFD700",goldenrod:"DAA520",gray:"808080",green:"008000",greenyellow:"ADFF2F",honeydew:"F0FFF0",hotpink:"FF69B4",indianred:"CD5C5C",indigo:"4B0082",ivory:"FFFFF0",khaki:"F0E68C",lavender:"E6E6FA",lavenderblush:"FFF0F5",lawngreen:"7CFC00",lemonchiffon:"FFFACD",lightblue:"ADD8E6",lightcoral:"F08080",lightcyan:"E0FFFF",lightgoldenrodyellow:"FAFAD2",lightgreen:"90EE90",lightgrey:"D3D3D3",lightpink:"FFB6C1",lightsalmon:"FFA07A",lightseagreen:"20B2AA",lightskyblue:"87CEFA",lightslategray:"789",lightsteelblue:"B0C4DE",
lightyellow:"FFFFE0",lime:"0F0",limegreen:"32CD32",linen:"FAF0E6",magenta:"F0F",maroon:"800000",mediumauqamarine:"66CDAA",mediumblue:"0000CD",mediumorchid:"BA55D3",mediumpurple:"9370D8",mediumseagreen:"3CB371",mediumslateblue:"7B68EE",mediumspringgreen:"00FA9A",mediumturquoise:"48D1CC",mediumvioletred:"C71585",midnightblue:"191970",mintcream:"F5FFFA",mistyrose:"FFE4E1",moccasin:"FFE4B5",navajowhite:"FFDEAD",navy:"000080",oldlace:"FDF5E6",olive:"808000",olivedrab:"688E23",orange:"FFA500",orangered:"FF4500",
orchid:"DA70D6",palegoldenrod:"EEE8AA",palegreen:"98FB98",paleturquoise:"AFEEEE",palevioletred:"D87093",papayawhip:"FFEFD5",peachpuff:"FFDAB9",peru:"CD853F",pink:"FFC0CB",plum:"DDA0DD",powderblue:"B0E0E6",purple:"800080",red:"F00",rosybrown:"BC8F8F",royalblue:"4169E1",saddlebrown:"8B4513",salmon:"FA8072",sandybrown:"F4A460",seagreen:"2E8B57",seashell:"FFF5EE",sienna:"A0522D",silver:"C0C0C0",skyblue:"87CEEB",slateblue:"6A5ACD",slategray:"708090",snow:"FFFAFA",springgreen:"00FF7F",steelblue:"4682B4",
tan:"D2B48C",teal:"008080",thistle:"D8BFD8",tomato:"FF6347",turquoise:"40E0D0",violet:"EE82EE",wheat:"F5DEB3",white:"FFF",whitesmoke:"F5F5F5",yellow:"FF0",yellowgreen:"9ACD32"};a.prototype={parse:function(){if(!this.La){var c=this.D,f;if(f=c.match(a.Lc)){c=this.Cb(+f[1],+f[2],+f[3]);f=5 in f?+f[5]:1}else if(f=c.match(a.wc)){var g=f[1],h=f[2],j=f[3],i,n;c=Math.round;h/=100;j/=100;if(h){h=j<=0.5?j*(h+1):j+h-j*h;i=j*2-h;g=g%360/360;j=b(i,h,g+1/3);n=b(i,h,g);g=b(i,h,g-1/3)}else j=n=g=j*255;c={Kc:c(j),
lc:c(n),ac:c(g)};c=this.Cb(c.Kc,c.lc,c.ac);f=5 in f?+f[5]:1}else{if(a.Va.hasOwnProperty(f=c.toLowerCase()))c="#"+a.Va[f];f=c==="transparent"?0:1}this.La=c;this.Sb=f}},Cb:function(c,f,g){return"#"+(c<16?"0":"")+c.toString(16)+(f<16?"0":"")+f.toString(16)+(g<16?"0":"")+g.toString(16)},qb:function(c){this.parse();return this.La==="currentColor"?e.O(c.currentStyle.color).qb(c):this.La},Zb:function(){this.parse();return this.Sb}};e.O=function(c){return d[c]||(d[c]=new a(c))};return a}();e.o=function(){function b(d){this.ua=
d;this.ch=0;this.C=[];this.Z=0}var a=b.Ja={ca:1,ib:2,i:4,Lb:8,jb:16,ia:32,m:64,R:128,Ea:256,la:512,Rb:1024,URL:2048};b.Ia=function(d,c){this.e=d;this.a=c};b.Ia.prototype={Ua:function(){return this.e&a.m||this.e&a.R&&this.a==="0"},I:function(){return this.Ua()||this.e&a.la}};b.prototype={Yc:/\s/,Fc:/^[\+\-]?(\d*\.)?\d+/,url:/^url\(\s*("([^"]*)"|'([^']*)'|([!#$%&*-~]*))\s*\)/i,vb:/^\-?[_a-z][\w-]*/i,Tc:/^("([^"]*)"|'([^']*)')/,uc:/^#([\da-f]{6}|[\da-f]{3})/i,Wc:{px:a.m,em:a.m,ex:a.m,mm:a.m,cm:a.m,"in":a.m,
pt:a.m,pc:a.m,deg:a.ca,rad:a.ca,grad:a.ca},fc:{rgb:1,rgba:1,hsl:1,hsla:1},next:function(d){function c(p,v){p=new b.Ia(p,v);if(!d){n.C.push(p);n.Z++}return p}function f(){n.Z++;return null}var g,h,j,i,n=this;if(this.Z<this.C.length)return this.C[this.Z++];for(;this.Yc.test(this.ua.charAt(this.ch));)this.ch++;if(this.ch>=this.ua.length)return f();h=this.ch;g=this.ua.substring(this.ch);j=g.charAt(0);switch(j){case "#":if(i=g.match(this.uc)){this.ch+=i[0].length;return c(a.i,i[0])}break;case '"':case "'":if(i=
g.match(this.Tc)){this.ch+=i[0].length;return c(a.Rb,i[2]||i[3]||"")}break;case "/":case ",":this.ch++;return c(a.Ea,j);case "u":if(i=g.match(this.url)){this.ch+=i[0].length;return c(a.URL,i[2]||i[3]||i[4]||"")}}if(i=g.match(this.Fc)){j=i[0];this.ch+=j.length;if(g.charAt(j.length)==="%"){this.ch++;return c(a.la,j+"%")}if(i=g.substring(j.length).match(this.vb)){j+=i[0];this.ch+=i[0].length;return c(this.Wc[i[0].toLowerCase()]||a.Lb,j)}return c(a.R,j)}if(i=g.match(this.vb)){j=i[0];this.ch+=j.length;
if(j.toLowerCase()in e.Jb.Va||j==="currentColor"||j==="transparent")return c(a.i,j);if(g.charAt(j.length)==="("){this.ch++;if(j.toLowerCase()in this.fc){g=function(p){return p&&p.e&a.R};i=function(p){return p&&p.e&(a.R|a.la)};var o=function(p,v){return p&&p.a===v},l=function(){return n.next(1)};if((j.charAt(0)==="r"?i(l()):g(l()))&&o(l(),",")&&i(l())&&o(l(),",")&&i(l())&&(j==="rgb"||j==="hsa"||o(l(),",")&&g(l()))&&o(l(),")"))return c(a.i,this.ua.substring(h,this.ch));return f()}return c(a.jb,j)}return c(a.ia,
j)}this.ch++;return c(a.ib,j)},j:function(){return this.C[this.Z-- -2]},all:function(){for(;this.next(););return this.C},aa:function(d,c){for(var f=[],g,h;g=this.next();){if(d(g)){h=true;this.j();break}f.push(g)}return c&&!h?null:f}};return b}();e.hb=function(b){this.d=b};e.hb.prototype={F:0,Ic:function(){var b=this.Ma,a;return!b||(a=this.W())&&(b.x!==a.x||b.y!==a.y)},Pc:function(){var b=this.Ma,a;return!b||(a=this.W())&&(b.g!==a.g||b.f!==a.f)},ub:function(){var b=this.d,a=b.getBoundingClientRect(),
d=e.P===9;return{x:a.left,y:a.top,g:d?b.offsetWidth:a.right-a.left,f:d?b.offsetHeight:a.bottom-a.top}},W:function(){return this.F?this.oa||(this.oa=this.ub()):this.ub()},tc:function(){return!!this.Ma},wa:function(){++this.F},Ba:function(){if(!--this.F){if(this.oa)this.Ma=this.oa;this.oa=null}}};(function(){function b(a){var d=e.M.Y(a);return function(){if(this.F){var c=this.lb||(this.lb={});return d in c?c[d]:(c[d]=a.call(this))}else return a.call(this)}}e.v={F:0,Ya:function(a){function d(c){this.d=
c;this.kb=this.X()}e.xa(d.prototype,e.v,a);d.Xb={};return d},H:function(){var a=this.X(),d=this.constructor.Xb;return a?a in d?d[a]:(d[a]=this.ab(a)):null},X:b(function(){var a=this.d,d=this.constructor,c=a.style;a=a.currentStyle;var f=this.Oa,g=this.bb,h=d.Vb||(d.Vb=e.q+f);d=d.Wb||(d.Wb=e.Ha+g.charAt(0).toUpperCase()+g.substring(1));return c[d]||a.getAttribute(h)||c[g]||a.getAttribute(f)}),B:b(function(){return!!this.H()}),pb:b(function(){var a=this.X(),d=a!==this.kb;this.kb=a;return d}),ta:b,wa:function(){++this.F},
Ba:function(){--this.F||delete this.lb}}})();e.eb=e.v.Ya({Oa:e.q+"background",bb:e.Ha+"Background",$b:{scroll:1,fixed:1,local:1},za:{"repeat-x":1,"repeat-y":1,repeat:1,"no-repeat":1},Ab:{"padding-box":1,"border-box":1,"content-box":1},Jc:{top:1,right:1,bottom:1,left:1,center:1},Qc:{contain:1,cover:1},ya:{ga:"backgroundClip",i:"backgroundColor",K:"backgroundImage",ja:"backgroundOrigin",s:"backgroundPosition",u:"backgroundRepeat",na:"backgroundSize"},ab:function(b){function a(t){return t&&t.I()||t.e&
n&&t.a in k}function d(t){return t&&(t.I()&&e.h(t.a)||t.a==="auto"&&"auto")}var c=this.d.currentStyle,f,g,h,j=e.o.Ja,i=j.Ea,n=j.ia,o=j.i,l,p,v=0,k=this.Jc,q,m,r={G:[]};if(this.Pa()){f=new e.o(b);for(h={};g=f.next();){l=g.e;p=g.a;if(!h.z&&l&j.jb&&p==="linear-gradient"){q={Q:[],z:p};for(m={};g=f.next();){l=g.e;p=g.a;if(l&j.ib&&p===")"){m.color&&q.Q.push(m);q.Q.length>1&&e.xa(h,q);break}if(l&o){if(q.pa||q.Sa){g=f.j();if(g.e!==i)break;f.next()}m={color:e.O(p)};g=f.next();if(g.I())m.zb=e.h(g.a);else f.j()}else if(l&
j.ca&&!q.pa&&!m.color&&!q.Q.length)q.pa=new e.Ib(g.a);else if(a(g)&&!q.Sa&&!m.color&&!q.Q.length){f.j();q.Sa=new e.da(f.aa(function(t){return!a(t)},false))}else if(l&i&&p===","){if(m.color){q.Q.push(m);m={}}}else break}}else if(!h.z&&l&j.URL){h.xb=p;h.z="image"}else if(a(g)&&!h.U){f.j();h.U=new e.da(f.aa(function(t){return!a(t)},false))}else if(l&n)if(p in this.za&&!h.Ta)h.Ta=p;else if(p in this.Ab&&!h.qa){h.qa=p;if((g=f.next())&&g.e&n&&g.a in this.Ab)h.Na=g.a;else{h.Na=p;f.j()}}else if(p in this.$b&&
!h.nb)h.nb=p;else return null;else if(l&o&&!r.color)r.color=e.O(p);else if(l&i&&p==="/"&&!h.ra&&h.U){g=f.next();if(g.e&n&&g.a in this.Qc)h.ra=new e.ea(g.a);else if(g=d(g)){l=d(f.next());if(!l){l=g;f.j()}h.ra=new e.ea(g,l)}else return null}else if(l&i&&p===","&&h.z){h.$a=b.substring(v,f.ch-1);v=f.ch;r.G.push(h);h={}}else return null}if(h.z){h.$a=b.substring(v);r.G.push(h)}}else this.Gb(e.P<9?function(){var t=this.ya,s=c[t.s+"X"],z=c[t.s+"Y"],C=c[t.K],D=c[t.i];if(D!=="transparent")r.color=e.O(D);if(C!==
"none")r.G=[{z:"image",xb:(new e.o(C)).next().a,Ta:c[t.u],U:new e.da((new e.o(s+" "+z)).all())}]}:function(){var t=this.ya,s=/\s*,\s*/,z=c[t.K].split(s),C=c[t.i],D,E,J,L,w,I;if(C!=="transparent")r.color=e.O(C);if((L=z.length)&&z[0]!=="none"){C=c[t.u].split(s);D=c[t.s].split(s);E=c[t.ja].split(s);J=c[t.ga].split(s);t=c[t.na].split(s);r.G=[];for(s=0;s<L;s++)if((w=z[s])&&w!=="none"){I=t[s].split(" ");r.G.push({$a:w+" "+C[s]+" "+D[s]+" / "+t[s]+" "+E[s]+" "+J[s],z:"image",xb:(new e.o(w)).next().a,Ta:C[s],
U:new e.da((new e.o(D[s])).all()),qa:E[s],Na:J[s],ra:new e.ea(I[0],I[1])})}}});return r.color||r.G[0]?r:null},Gb:function(b){var a=e.P>8,d=this.ya,c=this.d.runtimeStyle,f=c[d.K],g=c[d.i],h=c[d.u],j,i,n,o;if(f)c[d.K]="";if(g)c[d.i]="";if(h)c[d.u]="";if(a){j=c[d.ga];i=c[d.ja];o=c[d.s];n=c[d.na];if(j)c[d.ga]="";if(i)c[d.ja]="";if(o)c[d.s]="";if(n)c[d.na]=""}b=b.call(this);if(f)c[d.K]=f;if(g)c[d.i]=g;if(h)c[d.u]=h;if(a){if(j)c[d.ga]=j;if(i)c[d.ja]=i;if(o)c[d.s]=o;if(n)c[d.na]=n}return b},X:e.v.ta(function(){return this.Pa()||
this.Gb(function(){var b=this.d.currentStyle,a=this.ya;return b[a.i]+" "+b[a.K]+" "+b[a.u]+" "+b[a.s+"X"]+" "+b[a.s+"Y"]})}),Pa:e.v.ta(function(){var b=this.d;return b.style[this.bb]||b.currentStyle.getAttribute(this.Oa)}),mc:function(b,a,d){var c=this.d,f=a.W();a=f.g;f=f.f;if(b!=="border-box")if((d=d.H())&&(d=d.ba)){a-=d.l.c(c)+d.l.c(c);f-=d.t.c(c)+d.b.c(c)}if(b==="content-box"){b=e.h;d=c.currentStyle;a-=b(d.paddingLeft).c(c)+b(d.paddingRight).c(c);f-=b(d.paddingTop).c(c)+b(d.paddingBottom).c(c)}return{g:a,
f:f}},Ac:function(){var b=0;if(e.wb<7){b=this.d;b=""+(b.style[e.Ha+"PngFix"]||b.currentStyle.getAttribute(e.q+"png-fix"))==="true"}return b},B:e.v.ta(function(){return(this.Pa()||this.Ac())&&!!this.H()})});e.gb=e.v.Ya({Oc:["Top","Right","Bottom","Left"],Dc:{thin:"1px",medium:"3px",thick:"5px"},ab:function(){var b={},a={},d={},c=false,f=true,g=true,h=true;this.Hb(function(){for(var j=this.d.currentStyle,i=0,n,o,l,p,v,k,q;i<4;i++){l=this.Oc[i];q=l.charAt(0).toLowerCase();n=a[q]=j["border"+l+"Style"];
o=j["border"+l+"Color"];l=j["border"+l+"Width"];if(i>0){if(n!==p)g=false;if(o!==v)f=false;if(l!==k)h=false}p=n;v=o;k=l;d[q]=e.O(o);l=b[q]=e.h(a[q]==="none"?"0":this.Dc[l]||l);if(l.c(this.d)>0)c=true}});return c?{ba:b,yd:a,ld:d,Bd:h,md:f,zd:g}:null},X:e.v.ta(function(){var b=this.d,a=b.currentStyle,d;b.tagName in e.Uc&&b.offsetParent.currentStyle.borderCollapse==="collapse"||this.Hb(function(){d=a.borderWidth+"|"+a.borderStyle+"|"+a.borderColor});return d}),Hb:function(b){var a=this.d.runtimeStyle,
d=a.borderWidth,c=a.borderColor;if(d)a.borderWidth="";if(c)a.borderColor="";b=b.call(this);if(d)a.borderWidth=d;if(c)a.borderColor=c;return b}});e.fb=e.v.Ya({Oa:"border-image",bb:"borderImage",za:{stretch:1,round:1,repeat:1,space:1},ab:function(b){var a=null,d,c,f,g,h,j,i=0,n=e.o.Ja,o=n.ia,l=n.R,p=n.la;if(b){d=new e.o(b);a={};for(var v=function(m){return m&&m.e&n.Ea&&m.a==="/"},k=function(m){return m&&m.e&o&&m.a==="fill"},q=function(){g=d.aa(function(m){return!(m.e&(l|p))});if(k(d.next())&&!a.fill)a.fill=
true;else d.j();if(v(d.next())){i++;h=d.aa(function(m){return!m.I()&&!(m.e&o&&m.a==="auto")});if(v(d.next())){i++;j=d.aa(function(m){return!m.Ua()})}}else d.j()};b=d.next();){c=b.e;f=b.a;if(c&(l|p)&&!g){d.j();q()}else if(k(b)&&!a.fill){a.fill=true;q()}else if(c&o&&this.za[f]&&!a.repeat){a.repeat={f:f};if(b=d.next())if(b.e&o&&this.za[b.a])a.repeat.db=b.a;else d.j()}else if(c&n.URL&&!a.src)a.src=f;else return null}if(!a.src||!g||g.length<1||g.length>4||h&&h.length>4||i===1&&h.length<1||j&&j.length>
4||i===2&&j.length<1)return null;if(!a.repeat)a.repeat={f:"stretch"};if(!a.repeat.db)a.repeat.db=a.repeat.f;b=function(m,r){return{t:r(m[0]),r:r(m[1]||m[0]),b:r(m[2]||m[0]),l:r(m[3]||m[1]||m[0])}};a.slice=b(g,function(m){return e.h(m.e&l?m.a+"px":m.a)});if(h&&h[0])a.ba=b(h,function(m){return m.I()?e.h(m.a):m.a});if(j&&j[0])a.ud=b(j,function(m){return m.Ua()?e.h(m.a):m.a})}return a}});e.ma={Xa:function(b){function a(d,c,f,g){this.d=d;this.ob=c;this.p=f;this.parent=g}e.xa(a.prototype,e.ma,b);return a},
Bc:false,Wa:function(){return false},Bb:e.va,Fb:function(){this.B()?this.rb():this.k()},Eb:function(){this.Bc=true},vc:function(){this.d.runtimeStyle.borderColor="transparent"},k:function(){}};e.Ob=e.ma.Xa({Eb:e.va,Fb:e.va,Ad:e.va,Gc:/^,+|,+$/g,zc:/,+/g,Aa:function(b,a){(this.Ka||(this.Ka=[]))[b]=a||void 0},sb:function(){var b=this.Ka,a;if(b&&(a=b.join(",").replace(this.Gc,"").replace(this.zc,","))!==this.Ub)this.Ub=this.d.runtimeStyle.background=a},k:function(){this.d.runtimeStyle.background="";
delete this.Ka}});e.Mb=e.ma.Xa({T:1,Wa:function(){return this.p.N.pb()},B:function(){var b=this.p;return b.N.B()||b.w.B()},rb:function(){var b=this.p.N,a=b.H(),d,c,f=0,g,h;if(a){d=[];if(c=a.G)for(;g=c[f++];)if(g.z==="linear-gradient"){h=b.mc(d.qa,this.ob,this.p.sa);h=(g.ra||e.ea.Kb).c(this.d,h.g,h.f,h.g,h.f);d.push("url(data:image/svg+xml,"+escape(this.oc(g,h.g,h.f))+") "+this.bc(g.U)+" / "+h.g+"px "+h.f+"px "+(g.nb||"")+" "+(g.qa||"")+" "+(g.Na||""))}else d.push(g.$a);a.color&&d.push(a.color.D);
this.parent.Aa(this.T,d.join(","))}},bc:function(b){return b?b.C.map(function(a){return a.a}).join(" "):"0 0"},oc:function(b,a,d){var c=this.d,f=b.Q,g=f.length,h=e.Da.nc(c,a,d,b);b=h.Rc;var j=h.Sc,i=h.jc,n=h.kc;h=h.Cc;var o,l,p,v,k;o=[];for(l=0;l<g;l++)o.push(f[l].zb?f[l].zb.c(c,h):l===0?0:l===g-1?h:null);for(l=1;l<g;l++)if(o[l]===null){v=o[l-1];p=l;do k=o[++p];while(k===null);o[l]=v+(k-v)/(p-l+1)}a=['<svg width="'+a+'" height="'+d+'" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="g" gradientUnits="userSpaceOnUse" x1="'+
b/a*100+'%" y1="'+j/d*100+'%" x2="'+i/a*100+'%" y2="'+n/d*100+'%">'];for(l=0;l<g;l++)a.push('<stop offset="'+o[l]/h+'" stop-color="'+f[l].color.qb(c)+'" stop-opacity="'+f[l].color.Zb()+'"/>');a.push('</linearGradient></defs><rect width="100%" height="100%" fill="url(#g)"/></svg>');return a.join("")},k:function(){this.parent.Aa(this.T)}});e.Nb=e.ma.Xa({u:"repeat",Qb:"stretch",Pb:"round",T:0,Wa:function(){return this.p.w.pb()},B:function(){return this.p.w.B()},rb:function(){var b=this,a=b.p.w.H(),d=
b.p.sa.H(),c=b.ob.W(),f=a.repeat,g=f.f,h=f.db,j=b.d,i=0;e.M.Zc(a.src,function(n){function o(R,T,V,Q,u,A,B,M,G,W){U.push('<pattern patternUnits="userSpaceOnUse" id="pattern'+S+'" x="'+(g===m?R+V/2-G/2:R)+'" y="'+(h===m?T+Q/2-W/2:T)+'" width="'+G+'" height="'+W+'"><svg width="'+G+'" height="'+W+'" viewBox="'+u+" "+A+" "+B+" "+M+'" preserveAspectRatio="none"><image xlink:href="'+q+'" x="0" y="0" width="'+v+'" height="'+k+'" /></svg></pattern>');X.push('<rect x="'+R+'" y="'+T+'" width="'+V+'" height="'+
Q+'" fill="url(#pattern'+S+')" />');S++}var l=c.g,p=c.f,v=n.g,k=n.f,q=b.xc(a.src,v,k),m=b.u,r=b.Qb;n=b.Pb;var t=Math.ceil,s=e.h("0"),z=a.ba||(d?d.ba:{t:s,r:s,b:s,l:s});s=z.t.c(j);var C=z.r.c(j),D=z.b.c(j);z=z.l.c(j);var E=a.slice,J=E.t.c(j),L=E.r.c(j),w=E.b.c(j);E=E.l.c(j);var I=l-z-C,N=p-s-D,H=v-E-L,F=k-J-w,y=g===r?I:H*s/J,x=h===r?N:F*C/L,K=g===r?I:H*D/w;r=h===r?N:F*z/E;var U=[],X=[],S=0;if(g===n){y-=(y-(I%y||y))/t(I/y);K-=(K-(I%K||K))/t(I/K)}if(h===n){x-=(x-(N%x||x))/t(N/x);r-=(r-(N%r||r))/t(N/
r)}n=['<svg width="'+l+'" height="'+p+'" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">'];o(0,0,z,s,0,0,E,J,z,s);o(z,0,I,s,E,0,H,J,y,s);o(l-C,0,C,s,v-L,0,L,J,C,s);o(0,s,z,N,0,J,E,F,z,r);if(a.fill)o(z,s,I,N,E,J,H,F,y||K||H,r||x||F);o(l-C,s,C,N,v-L,J,L,F,C,x);o(0,p-D,z,D,0,k-w,E,w,z,D);o(z,p-D,I,D,E,k-w,H,w,K,D);o(l-C,p-D,C,D,v-L,k-w,L,w,C,D);n.push("<defs>"+U.join("\n")+"</defs>"+X.join("\n")+"</svg>");b.parent.Aa(b.T,"url(data:image/svg+xml,"+escape(n.join(""))+") no-repeat border-box border-box");
i&&b.parent.sb()},b);i=1},xc:function(){var b={};return function(a,d,c){var f=b[a],g;if(!f){f=new Image;g=P.createElement("canvas");f.src=a;g.width=d;g.height=c;g.getContext("2d").drawImage(f,0,0);f=b[a]=g.toDataURL()}return f}}(),Bb:function(){if(this.B()){var b=this.d,a=b.runtimeStyle,d=this.p.w.H().ba;a.borderStyle="solid";if(d){a.borderTopWidth=d.t.c(b)+"px";a.borderRightWidth=d.r.c(b)+"px";a.borderBottomWidth=d.b.c(b)+"px";a.borderLeftWidth=d.l.c(b)+"px"}this.vc()}},k:function(){var b=this.d.runtimeStyle;
this.parent.Aa(this.T);b.borderColor=b.borderStyle=b.borderWidth=""}});e.Ca=function(){function b(k,q){k.className+=" "+q}function a(k){var q=v.slice.call(arguments,1),m=q.length;setTimeout(function(){for(;m--;)b(k,q[m])},0)}function d(k){var q=v.slice.call(arguments,1),m=q.length;setTimeout(function(){for(;m--;){var r=q[m];r=p[r]||(p[r]=new RegExp("\\b"+r+"\\b","g"));k.className=k.className.replace(r,"")}},0)}function c(k){function q(){if(!X){var u,A,B=e.P,M=k.currentStyle,G=M.getAttribute(g)===
"true";Q=M.getAttribute(h);Q=B>7?Q!=="false":Q==="true";if(!U){U=1;k.runtimeStyle.zoom=1;M=k;for(var W=1;M=M.previousSibling;)if(M.nodeType===1){W=0;break}W&&b(k,o)}y.wa();if(G&&(A=y.W())&&(u=P.documentElement||P.body)&&(A.y>u.clientHeight||A.x>u.clientWidth||A.y+A.f<0||A.x+A.g<0)){if(!T){T=1;e.Ga.J(q)}}else{X=1;T=U=0;e.Ga.$(q);if(B===9){x={N:new e.eb(k),w:new e.fb(k),sa:new e.gb(k)};K=[x.N,x.w];F=new e.Ob(k,y,x);u=[new e.Mb(k,y,x,F),new e.Nb(k,y,x,F)]}else{x={N:new e.eb(k),sa:new e.gb(k),w:new e.fb(k),
cc:new e.bd(k),dc:new e.ed(k),Xc:new e.jd(k)};K=[x.N,x.sa,x.w,x.cc,x.dc,x.Xc];F=new e.hd(k,y,x);u=[new e.dd(k,y,x,F),new e.$c(k,y,x,F),new e.cd(k,y,x,F),new e.ad(k,y,x,F)];k.tagName==="IMG"&&u.push(new e.fd(k,y,x,F));F.kd=u}H=[F].concat(u);if(u=k.currentStyle.getAttribute(e.q+"watch-ancestors")){u=parseInt(u,10);A=0;for(G=k.parentNode;G&&(u==="NaN"||A++<u);){w(G,"onpropertychange",L);w(G,"onmouseenter",s);w(G,"onmouseleave",z);w(G,"onmousedown",C);if(G.tagName in e.tb){w(G,"onfocus",E);w(G,"onblur",
J)}G=G.parentNode}}if(Q){e.ha.J(r);e.ha.Mc()}r(0,1)}if(!S){S=1;B<9&&w(k,"onmove",m);w(k,"onresize",m);w(k,"onpropertychange",t);w(k,"onmouseenter",s);w(k,"onmouseleave",z);w(k,"onmousedown",C);if(k.tagName in e.tb){w(k,"onfocus",E);w(k,"onblur",J)}e.ka.J(m);e.n.J(I)}y.Ba()}}function m(){y&&y.tc()&&r()}function r(u,A){if(!V)if(X){y.wa();for(var B=K.length;B--;)K[B].wa();var M=H.length,G=y.Pc();for(B=0;B<M;B++)H[B].Bb();if(A||y.Ic())for(B=0;B<M;B++)H[B].Eb();for(B=0;B<M;B++)if(A||G||u&&H[B].Wa())H[B].Fb();
F.sb();for(u=K.length;u--;)K[u].Ba();y.Ba()}else U||q()}function t(){var u=event;u&&u.propertyName in l||r(1)}function s(){a(k,j)}function z(){d(k,j,i)}function C(){a(k,i);e.Fa.J(D)}function D(){d(k,i);e.Fa.$(D)}function E(){a(k,n)}function J(){d(k,n)}function L(){var u=event.propertyName;if(u==="className"||u==="id")t()}function w(u,A,B){u.attachEvent(A,B);R.push([u,A,B])}function I(){if(S){for(var u=R.length,A;u--;){A=R[u];A[0].detachEvent(A[1],A[2])}e.n.$(I);S=0;R=[]}}function N(){if(!V){var u,
A;I();V=1;if(H){u=0;for(A=H.length;u<A;u++){H[u].sd=1;H[u].k()}}Q&&e.ha.$(r);e.ka.$(r);H=y=x=K=k=null}}var H,F,y=new e.hb(k),x,K,U,X,S,R=[],T,V,Q;this.yc=q;this.k=N}var f={},g=e.q+"lazy-init",h=e.q+"poll",j=e.fa+"hover",i=e.fa+"active",n=e.fa+"focus",o=e.fa+"first-child",l={background:1,bgColor:1,display:1},p={},v=[];c.qc=function(k){var q=e.M.Y(k);return f[q]||(f[q]=new c(k))};c.k=function(k){k=e.M.Y(k);var q=f[k];if(q){q.k();delete f[k]}};c.hc=function(){var k=[],q;if(f){for(var m in f)if(f.hasOwnProperty(m)){q=
f[m];k.push(q.pd);q.k()}f={}}return k};return c}();e.version="1.0beta6-SNAPSHOT";e.supportsVML=e.Db;e.attach=function(b){if(e.P===9||e.P<9&&e.Db)e.Ca.qc(b).yc()};e.detach=function(b){e.Ca.k(b)}})(window,document);
