(function(L,F){var g=L.PIE||(L.PIE={});g.Ca=function(a){var b,c,e,d,f=arguments;b=1;for(c=f.length;b<c;b++){d=f[b];for(e in d)if(d.hasOwnProperty(e))a[e]=d[e]}return a};g.Ca(g,{L:"-pie-",jb:"Pie",Ma:"pie_",nc:{TD:1,TH:1},Sb:{TABLE:1,THEAD:1,TBODY:1,TFOOT:1,TR:1,INPUT:1,TEXTAREA:1,SELECT:1,OPTION:1,IMG:1,HR:1},Wb:{A:1,INPUT:1,TEXTAREA:1,SELECT:1,BUTTON:1},xd:{submit:1,button:1,reset:1},fd:function(){}});try{F.execCommand("BackgroundImageCache",false,true)}catch(Y){}(function(){for(var a=4,b=F.createElement("div"),
c=b.getElementsByTagName("i");b.innerHTML="<!--[if gt IE "+ ++a+"]><i></i><![endif]--\>",c[0];);g.V=a;if(a===6)g.L=g.L.replace(/^-/,"");g.ka=F.documentMode||g.V;b.innerHTML='<v:shape adj="1"/>';a=b.firstChild;a.style.behavior="url(#default#VML)";g.mc=typeof a.adj==="object"})();(function(){var a=0,b={};g.C={Q:function(c){return c&&c.uniqueID||c._pieId||(c._pieId="_"+a++)},tc:function(c,e,d){var f=b[c],i,j;if(f)Object.prototype.toString.call(f)==="[object Array]"?f.push([e,d]):e.call(d,f);else{j=b[c]=
[[e,d]];i=new Image;i.onload=function(){f=b[c]={f:i.width,d:i.height};for(var h=0,k=j.length;h<k;h++)j[h][0].call(j[h][1],f);i.onload=null};i.src=c}}}})();g.gb={od:function(a,b,c,e){function d(){k=i>=90&&i<270?b:0;m=i<180?c:0;l=b-k;o=c-m}function f(){for(;i<0;)i+=360;i%=360}var i=e.ua;e=e.vb;var j,h,k,m,l,o,r,n;if(e){e=e.coords(a,b,c);j=e.x;h=e.y}if(i){i=i.Zc();f();d();if(!e){j=k;h=m}e=g.gb.ic(j,h,i,l,o);a=e[0];e=e[1]}else if(e){a=b-j;e=c-h}else{j=h=a=0;e=c}r=a-j;n=e-h;if(i===void 0){i=!r?n<0?90:
270:!n?r<0?180:0:-Math.atan2(n,r)/Math.PI*180;f();d()}return{ua:i,Sd:j,Td:h,he:a,ie:e,Qd:k,Rd:m,gd:l,hd:o,$c:r,ad:n,zd:g.gb.Tb(j,h,a,e)}},ic:function(a,b,c,e,d){if(c===0||c===180)return[e,b];else if(c===90||c===270)return[a,d];else{c=Math.tan(-c*Math.PI/180);a=c*a-b;b=-1/c;e=b*e-d;d=b-c;return[(e-a)/d,(c*e-b*a)/d]}},Tb:function(a,b,c,e){a=c-a;b=e-b;return Math.abs(a===0?b:b===0?a:Math.sqrt(a*a+b*b))}};g.ba=function(){this.Ab=[];this.bc={}};g.ba.prototype={X:function(a){var b=g.C.Q(a),c=this.bc,e=
this.Ab;if(!(b in c)){c[b]=e.length;e.push(a)}},Ia:function(a){a=g.C.Q(a);var b=this.bc;if(a&&a in b){delete this.Ab[b[a]];delete b[a]}},Aa:function(){for(var a=this.Ab,b=a.length;b--;)a[b]&&a[b]()}};g.Oa=new g.ba;g.Oa.Id=function(){var a=this;if(!a.Jd){setInterval(function(){a.Aa()},250);a.Jd=1}};(function(){function a(){g.J.Aa();L.detachEvent("onunload",a);L.PIE=null}g.J=new g.ba;L.attachEvent("onunload",a);g.J.va=function(b,c,e){b.attachEvent(c,e);this.X(function(){b.detachEvent(c,e)})}})();g.Qa=
new g.ba;g.J.va(L,"onresize",function(){g.Qa.Aa()});(function(){function a(){g.ib.Aa()}g.ib=new g.ba;g.J.va(L,"onscroll",a);g.Qa.X(a)})();(function(){function a(){c=g.fb.bd()}function b(){if(c){for(var e=0,d=c.length;e<d;e++)g.attach(c[e]);c=0}}var c;g.J.va(L,"onbeforeprint",a);g.J.va(L,"onafterprint",b)})();g.hb=new g.ba;g.J.va(F,"onmouseup",function(){g.hb.Aa()});g.Kb=function(){function a(h){this.$=h}var b=F.createElement("length-calc"),c=F.body,e=b.style,d={},f=["mm","cm","in","pt","pc"],i=f.length,
j={};e.position="absolute";e.top=e.left="-9999px";for(c.appendChild(b);i--;){e.width="100"+f[i];d[f[i]]=b.offsetWidth/100}c.removeChild(b);e.width="1em";a.prototype={Bb:/(px|em|ex|mm|cm|in|pt|pc|%)$/,Yb:function(){var h=this.Bd;if(h===void 0)h=this.Bd=parseFloat(this.$);return h},ub:function(){var h=this.Xd;if(!h)h=this.Xd=(h=this.$.match(this.Bb))&&h[0]||"px";return h},a:function(h,k){var m=this.Yb(),l=this.ub();switch(l){case "px":return m;case "%":return m*(typeof k==="function"?k():k)/100;case "em":return m*
this.rb(h);case "ex":return m*this.rb(h)/2;default:return m*d[l]}},rb:function(h){var k=h.currentStyle.fontSize,m,l;if(k.indexOf("px")>0)return parseFloat(k);else if(h.tagName in g.Sb){l=this;m=h.parentNode;return g.k(k).a(m,function(){return l.rb(m)})}else{h.appendChild(b);k=b.offsetWidth;b.parentNode===h&&h.removeChild(b);return k}}};a.kc=function(h){return h/d.pt};g.k=function(h){return j[h]||(j[h]=new a(h))};return a}();g.Ka=function(){function a(d){this.Z=d}var b=g.k("50%"),c={top:1,center:1,
bottom:1},e={left:1,center:1,right:1};a.prototype={sd:function(){if(!this.Pb){var d=this.Z,f=d.length,i=g.p,j=i.ta,h=g.k("0");j=j.qa;h=["left",h,"top",h];if(f===1){d.push(new i.kb(j,"center"));f++}if(f===2){j&(d[0].i|d[1].i)&&d[0].c in c&&d[1].c in e&&d.push(d.shift());if(d[0].i&j)if(d[0].c==="center")h[1]=b;else h[0]=d[0].c;else if(d[0].S())h[1]=g.k(d[0].c);if(d[1].i&j)if(d[1].c==="center")h[3]=b;else h[2]=d[1].c;else if(d[1].S())h[3]=g.k(d[1].c)}this.Pb=h}return this.Pb},coords:function(d,f,i){var j=
this.sd(),h=j[1].a(d,f);d=j[3].a(d,i);return{x:j[0]==="right"?f-h:h,y:j[2]==="bottom"?i-d:d}}};return a}();g.La=function(){function a(b,c){this.f=b;this.d=c}a.prototype={a:function(b,c,e,d,f){var i=this.f,j=this.d,h=c/e;d=d/f;if(i==="contain"){i=d>h?c:e*d;j=d>h?c/d:e}else if(i==="cover"){i=d<h?c:e*d;j=d<h?c/d:e}else if(i==="auto"){j=j==="auto"?f:j.a(b,e);i=j*d}else{i=i.a(b,c);j=j==="auto"?i/d:j.a(b,e)}return{f:i,d:j}}};a.Cc=new a("auto","auto");return a}();g.vc=function(){function a(b){this.$=b}a.prototype=
{Bb:/[a-z]+$/i,ub:function(){return this.Oc||(this.Oc=this.$.match(this.Bb)[0].toLowerCase())},Zc:function(){var b=this.Jc,c;if(b===undefined){b=this.ub();c=parseFloat(this.$,10);b=this.Jc=b==="deg"?c:b==="rad"?c/Math.PI*180:b==="grad"?c/400*360:b==="turn"?c*360:0}return b}};return a}();g.Bc=function(){function a(c){this.$=c}var b={};a.Hd=/\s*rgba\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d+|\d*\.\d+)\s*\)\s*/;a.zb={aliceblue:"F0F8FF",antiquewhite:"FAEBD7",aqua:"0FF",aquamarine:"7FFFD4",
azure:"F0FFFF",beige:"F5F5DC",bisque:"FFE4C4",black:"000",blanchedalmond:"FFEBCD",blue:"00F",blueviolet:"8A2BE2",brown:"A52A2A",burlywood:"DEB887",cadetblue:"5F9EA0",chartreuse:"7FFF00",chocolate:"D2691E",coral:"FF7F50",cornflowerblue:"6495ED",cornsilk:"FFF8DC",crimson:"DC143C",cyan:"0FF",darkblue:"00008B",darkcyan:"008B8B",darkgoldenrod:"B8860B",darkgray:"A9A9A9",darkgreen:"006400",darkkhaki:"BDB76B",darkmagenta:"8B008B",darkolivegreen:"556B2F",darkorange:"FF8C00",darkorchid:"9932CC",darkred:"8B0000",
darksalmon:"E9967A",darkseagreen:"8FBC8F",darkslateblue:"483D8B",darkslategray:"2F4F4F",darkturquoise:"00CED1",darkviolet:"9400D3",deeppink:"FF1493",deepskyblue:"00BFFF",dimgray:"696969",dodgerblue:"1E90FF",firebrick:"B22222",floralwhite:"FFFAF0",forestgreen:"228B22",fuchsia:"F0F",gainsboro:"DCDCDC",ghostwhite:"F8F8FF",gold:"FFD700",goldenrod:"DAA520",gray:"808080",green:"008000",greenyellow:"ADFF2F",honeydew:"F0FFF0",hotpink:"FF69B4",indianred:"CD5C5C",indigo:"4B0082",ivory:"FFFFF0",khaki:"F0E68C",
lavender:"E6E6FA",lavenderblush:"FFF0F5",lawngreen:"7CFC00",lemonchiffon:"FFFACD",lightblue:"ADD8E6",lightcoral:"F08080",lightcyan:"E0FFFF",lightgoldenrodyellow:"FAFAD2",lightgreen:"90EE90",lightgrey:"D3D3D3",lightpink:"FFB6C1",lightsalmon:"FFA07A",lightseagreen:"20B2AA",lightskyblue:"87CEFA",lightslategray:"789",lightsteelblue:"B0C4DE",lightyellow:"FFFFE0",lime:"0F0",limegreen:"32CD32",linen:"FAF0E6",magenta:"F0F",maroon:"800000",mediumauqamarine:"66CDAA",mediumblue:"0000CD",mediumorchid:"BA55D3",
mediumpurple:"9370D8",mediumseagreen:"3CB371",mediumslateblue:"7B68EE",mediumspringgreen:"00FA9A",mediumturquoise:"48D1CC",mediumvioletred:"C71585",midnightblue:"191970",mintcream:"F5FFFA",mistyrose:"FFE4E1",moccasin:"FFE4B5",navajowhite:"FFDEAD",navy:"000080",oldlace:"FDF5E6",olive:"808000",olivedrab:"688E23",orange:"FFA500",orangered:"FF4500",orchid:"DA70D6",palegoldenrod:"EEE8AA",palegreen:"98FB98",paleturquoise:"AFEEEE",palevioletred:"D87093",papayawhip:"FFEFD5",peachpuff:"FFDAB9",peru:"CD853F",
pink:"FFC0CB",plum:"DDA0DD",powderblue:"B0E0E6",purple:"800080",red:"F00",rosybrown:"BC8F8F",royalblue:"4169E1",saddlebrown:"8B4513",salmon:"FA8072",sandybrown:"F4A460",seagreen:"2E8B57",seashell:"FFF5EE",sienna:"A0522D",silver:"C0C0C0",skyblue:"87CEEB",slateblue:"6A5ACD",slategray:"708090",snow:"FFFAFA",springgreen:"00FF7F",steelblue:"4682B4",tan:"D2B48C",teal:"008080",thistle:"D8BFD8",tomato:"FF6347",turquoise:"40E0D0",violet:"EE82EE",wheat:"F5DEB3",white:"FFF",whitesmoke:"F5F5F5",yellow:"FF0",
yellowgreen:"9ACD32"};a.prototype={parse:function(){if(!this.Ua){var c=this.$,e;if(e=c.match(a.Hd)){this.Ua="rgb("+e[1]+","+e[2]+","+e[3]+")";this.Lb=parseFloat(e[4])}else{if((e=c.toLowerCase())in a.zb)c="#"+a.zb[e];this.Ua=c;this.Lb=c==="transparent"?0:1}}},ga:function(c){this.parse();return this.Ua==="currentColor"?c.currentStyle.color:this.Ua},da:function(){this.parse();return this.Lb}};g.ia=function(c){return b[c]||(b[c]=new a(c))};return a}();g.p=function(){function a(c){this.Ya=c;this.ch=0;
this.Z=[];this.Ha=0}var b=a.ta={Ja:1,Ib:2,q:4,Dc:8,Jb:16,qa:32,I:64,ra:128,sa:256,Ra:512,Gc:1024,URL:2048};a.kb=function(c,e){this.i=c;this.c=e};a.kb.prototype={Ba:function(){return this.i&b.I||this.i&b.ra&&this.c==="0"},S:function(){return this.Ba()||this.i&b.Ra}};a.prototype={ae:/\s/,Cd:/^[\+\-]?(\d*\.)?\d+/,url:/^url\(\s*("([^"]*)"|'([^']*)'|([!#$%&*-~]*))\s*\)/i,ac:/^\-?[_a-z][\w-]*/i,Ud:/^("([^"]*)"|'([^']*)')/,ud:/^#([\da-f]{6}|[\da-f]{3})/i,Yd:{px:b.I,em:b.I,ex:b.I,mm:b.I,cm:b.I,"in":b.I,pt:b.I,
pc:b.I,deg:b.Ja,rad:b.Ja,grad:b.Ja},Tc:{rgb:1,rgba:1,hsl:1,hsla:1},next:function(c){function e(o,r){o=new a.kb(o,r);if(!c){k.Z.push(o);k.Ha++}return o}function d(){k.Ha++;return null}var f,i,j,h,k=this;if(this.Ha<this.Z.length)return this.Z[this.Ha++];for(;this.ae.test(this.Ya.charAt(this.ch));)this.ch++;if(this.ch>=this.Ya.length)return d();i=this.ch;f=this.Ya.substring(this.ch);j=f.charAt(0);switch(j){case "#":if(h=f.match(this.ud)){this.ch+=h[0].length;return e(b.q,h[0])}break;case '"':case "'":if(h=
f.match(this.Ud)){this.ch+=h[0].length;return e(b.Gc,h[2]||h[3]||"")}break;case "/":case ",":this.ch++;return e(b.sa,j);case "u":if(h=f.match(this.url)){this.ch+=h[0].length;return e(b.URL,h[2]||h[3]||h[4]||"")}}if(h=f.match(this.Cd)){j=h[0];this.ch+=j.length;if(f.charAt(j.length)==="%"){this.ch++;return e(b.Ra,j+"%")}if(h=f.substring(j.length).match(this.ac)){j+=h[0];this.ch+=h[0].length;return e(this.Yd[h[0].toLowerCase()]||b.Dc,j)}return e(b.ra,j)}if(h=f.match(this.ac)){j=h[0];this.ch+=j.length;
if(j.toLowerCase()in g.Bc.zb||j==="currentColor"||j==="transparent")return e(b.q,j);if(f.charAt(j.length)==="("){this.ch++;if(j.toLowerCase()in this.Tc){f=function(o){return o&&o.i&b.ra};h=function(o){return o&&o.i&(b.ra|b.Ra)};var m=function(o,r){return o&&o.c===r},l=function(){return k.next(1)};if((j.charAt(0)==="r"?h(l()):f(l()))&&m(l(),",")&&h(l())&&m(l(),",")&&h(l())&&(j==="rgb"||j==="hsa"||m(l(),",")&&f(l()))&&m(l(),")"))return e(b.q,this.Ya.substring(i,this.ch));return d()}return e(b.Jb,j)}return e(b.qa,
j)}this.ch++;return e(b.Ib,j)},w:function(){return this.Z[this.Ha-- -2]},all:function(){for(;this.next(););return this.Z},pa:function(c,e){for(var d=[],f,i;f=this.next();){if(c(f)){i=true;this.w();break}d.push(f)}return e&&!i?null:d}};return a}();g.Hb=function(a){this.e=a};g.Hb.prototype={U:0,Ed:function(){var a=this.lb,b;return!a||(b=this.n())&&(a.x!==b.x||a.y!==b.y)},Nd:function(){var a=this.lb,b;return!a||(b=this.n())&&(a.f!==b.f||a.d!==b.d)},Xb:function(){var a=this.e,b=a.getBoundingClientRect(),
c=g.ka===9;return{x:b.left,y:b.top,f:c?a.offsetWidth:b.right-b.left,d:c?a.offsetHeight:b.bottom-b.top}},n:function(){return this.U?this.Va||(this.Va=this.Xb()):this.Xb()},td:function(){return!!this.lb},$a:function(){++this.U},db:function(){if(!--this.U){if(this.Va)this.lb=this.Va;this.Va=null}}};(function(){function a(b){var c=g.C.Q(b);return function(){if(this.U){var e=this.Nb||(this.Nb={});return c in e?e[c]:(e[c]=b.call(this))}else return b.call(this)}}g.u={U:0,ma:function(b){function c(e){this.e=
e;this.Mb=this.ja()}g.Ca(c.prototype,g.u,b);c.Nc={};return c},m:function(){var b=this.ja(),c=this.constructor.Nc;return b?b in c?c[b]:(c[b]=this.na(b)):null},ja:a(function(){var b=this.e,c=this.constructor,e=b.style;b=b.currentStyle;var d=this.xa,f=this.Ga,i=c.Lc||(c.Lc=g.L+d);c=c.Mc||(c.Mc=g.jb+f.charAt(0).toUpperCase()+f.substring(1));return e[c]||b.getAttribute(i)||e[f]||b.getAttribute(d)}),h:a(function(){return!!this.m()}),G:a(function(){var b=this.ja(),c=b!==this.Mb;this.Mb=b;return c}),wa:a,
$a:function(){++this.U},db:function(){--this.U||delete this.Nb}}})();g.Eb=g.u.ma({xa:g.L+"background",Ga:g.jb+"Background",Qc:{scroll:1,fixed:1,local:1},cb:{"repeat-x":1,"repeat-y":1,repeat:1,"no-repeat":1},hc:{"padding-box":1,"border-box":1,"content-box":1},Fd:{top:1,right:1,bottom:1,left:1,center:1},Od:{contain:1,cover:1},bb:{Na:"backgroundClip",q:"backgroundColor",aa:"backgroundImage",Pa:"backgroundOrigin",M:"backgroundPosition",ca:"backgroundRepeat",Sa:"backgroundSize"},na:function(a){function b(t){return t&&
t.S()||t.i&k&&t.c in n}function c(t){return t&&(t.S()&&g.k(t.c)||t.c==="auto"&&"auto")}var e=this.e.currentStyle,d,f,i,j=g.p.ta,h=j.sa,k=j.qa,m=j.q,l,o,r=0,n=this.Fd,p,q,s={N:[]};if(this.qb()){d=new g.p(a);for(i={};f=d.next();){l=f.i;o=f.c;if(!i.R&&l&j.Jb&&o==="linear-gradient"){p={oa:[],R:o};for(q={};f=d.next();){l=f.i;o=f.c;if(l&j.Ib&&o===")"){q.color&&p.oa.push(q);p.oa.length>1&&g.Ca(i,p);break}if(l&m){if(p.ua||p.vb){f=d.w();if(f.i!==h)break;d.next()}q={color:g.ia(o)};f=d.next();if(f.S())q.fc=
g.k(f.c);else d.w()}else if(l&j.Ja&&!p.ua&&!q.color&&!p.oa.length)p.ua=new g.vc(f.c);else if(b(f)&&!p.vb&&!q.color&&!p.oa.length){d.w();p.vb=new g.Ka(d.pa(function(t){return!b(t)},false))}else if(l&h&&o===","){if(q.color){p.oa.push(q);q={}}}else break}}else if(!i.R&&l&j.URL){i.xb=o;i.R="image"}else if(b(f)&&!i.ea){d.w();i.ea=new g.Ka(d.pa(function(t){return!b(t)},false))}else if(l&k)if(o in this.cb&&!i.Za)i.Za=o;else if(o in this.hc&&!i.Wa){i.Wa=o;if((f=d.next())&&f.i&k&&f.c in this.hc)i.Rb=f.c;else{i.Rb=
o;d.w()}}else if(o in this.Qc&&!i.Rc)i.Rc=o;else return null;else if(l&m&&!s.color)s.color=g.ia(o);else if(l&h&&o==="/"&&!i.Xa&&i.ea){f=d.next();if(f.i&k&&f.c in this.Od)i.Xa=new g.La(f.c);else if(f=c(f)){l=c(d.next());if(!l){l=f;d.w()}i.Xa=new g.La(f,l)}else return null}else if(l&h&&o===","&&i.R){i.gc=a.substring(r,d.ch-1);r=d.ch;s.N.push(i);i={}}else return null}if(i.R){i.gc=a.substring(r);s.N.push(i)}}else this.rc(g.ka<9?function(){var t=this.bb,u=e[t.M+"X"],E=e[t.M+"Y"],A=e[t.aa],x=e[t.q];if(x!==
"transparent")s.color=g.ia(x);if(A!=="none")s.N=[{R:"image",xb:(new g.p(A)).next().c,Za:e[t.ca],ea:new g.Ka((new g.p(u+" "+E)).all())}]}:function(){var t=this.bb,u=/\s*,\s*/,E=e[t.aa].split(u),A=e[t.q],x,B,I,M,w,N;if(A!=="transparent")s.color=g.ia(A);if((M=E.length)&&E[0]!=="none"){A=e[t.ca].split(u);x=e[t.M].split(u);B=e[t.Pa].split(u);I=e[t.Na].split(u);t=e[t.Sa].split(u);s.N=[];for(u=0;u<M;u++)if((w=E[u])&&w!=="none"){N=t[u].split(" ");s.N.push({gc:w+" "+A[u]+" "+x[u]+" / "+t[u]+" "+B[u]+" "+I[u],
R:"image",xb:(new g.p(w)).next().c,Za:A[u],ea:new g.Ka((new g.p(x[u])).all()),Wa:B[u],Rb:I[u],Xa:new g.La(N[0],N[1])})}}});return s.color||s.N[0]?s:null},rc:function(a){var b=g.ka>8,c=this.bb,e=this.e.runtimeStyle,d=e[c.aa],f=e[c.q],i=e[c.ca],j,h,k,m;if(d)e[c.aa]="";if(f)e[c.q]="";if(i)e[c.ca]="";if(b){j=e[c.Na];h=e[c.Pa];m=e[c.M];k=e[c.Sa];if(j)e[c.Na]="";if(h)e[c.Pa]="";if(m)e[c.M]="";if(k)e[c.Sa]=""}a=a.call(this);if(d)e[c.aa]=d;if(f)e[c.q]=f;if(i)e[c.ca]=i;if(b){if(j)e[c.Na]=j;if(h)e[c.Pa]=h;
if(m)e[c.M]=m;if(k)e[c.Sa]=k}return a},ja:g.u.wa(function(){return this.qb()||this.rc(function(){var a=this.e.currentStyle,b=this.bb;return a[b.q]+" "+a[b.aa]+" "+a[b.ca]+" "+a[b.M+"X"]+" "+a[b.M+"Y"]})}),qb:g.u.wa(function(){var a=this.e;return a.style[this.Ga]||a.currentStyle.getAttribute(this.xa)}),ld:function(a,b,c){var e=this.e,d=b.n();b=d.f;d=d.d;if(a!=="border-box")if((c=c.m())&&(c=c.T)){b-=c.l.a(e)+c.l.a(e);d-=c.t.a(e)+c.b.a(e)}if(a==="content-box"){a=g.k;c=e.currentStyle;b-=a(c.paddingLeft).a(e)+
a(c.paddingRight).a(e);d-=a(c.paddingTop).a(e)+a(c.paddingBottom).a(e)}return{f:b,d:d}},cc:function(){var a=0;if(g.V<7){a=this.e;a=""+(a.style[g.jb+"PngFix"]||a.currentStyle.getAttribute(g.L+"png-fix"))==="true"}return a},h:g.u.wa(function(){return(this.qb()||this.cc())&&!!this.m()})});g.Gb=g.u.ma({lc:["Top","Right","Bottom","Left"],Ad:{thin:"1px",medium:"3px",thick:"5px"},na:function(){var a={},b={},c={},e=false,d=true,f=true,i=true;this.sc(function(){for(var j=this.e.currentStyle,h=0,k,m,l,o,r,
n,p;h<4;h++){l=this.lc[h];p=l.charAt(0).toLowerCase();k=b[p]=j["border"+l+"Style"];m=j["border"+l+"Color"];l=j["border"+l+"Width"];if(h>0){if(k!==o)f=false;if(m!==r)d=false;if(l!==n)i=false}o=k;r=m;n=l;c[p]=g.ia(m);l=a[p]=g.k(b[p]==="none"?"0":this.Ad[l]||l);if(l.a(this.e)>0)e=true}});return e?{T:a,Vd:b,Uc:c,ke:i,Vc:d,Wd:f}:null},ja:g.u.wa(function(){var a=this.e,b=a.currentStyle,c;a.tagName in g.nc&&a.offsetParent.currentStyle.borderCollapse==="collapse"||this.sc(function(){c=b.borderWidth+"|"+b.borderStyle+
"|"+b.borderColor});return c}),sc:function(a){var b=this.e.runtimeStyle,c=b.borderWidth,e=b.borderColor;if(c)b.borderWidth="";if(e)b.borderColor="";a=a.call(this);if(c)b.borderWidth=c;if(e)b.borderColor=e;return a}});(function(){g.eb=g.u.ma({xa:"border-radius",Ga:"borderRadius",na:function(b){var c=null,e,d,f,i,j=false;if(b){d=new g.p(b);var h=function(){for(var k=[],m;(f=d.next())&&f.S();){i=g.k(f.c);m=i.Yb();if(m<0)return null;if(m>0)j=true;k.push(i)}return k.length>0&&k.length<5?{tl:k[0],tr:k[1]||
k[0],br:k[2]||k[0],bl:k[3]||k[1]||k[0]}:null};if(b=h()){if(f){if(f.i&g.p.ta.sa&&f.c==="/")e=h()}else e=b;if(j&&b&&e)c={x:b,y:e}}}return c}});var a=g.k("0");a={tl:a,tr:a,br:a,bl:a};g.eb.uc={x:a,y:a}})();g.Fb=g.u.ma({xa:"border-image",Ga:"borderImage",cb:{stretch:1,round:1,repeat:1,space:1},na:function(a){var b=null,c,e,d,f,i,j,h=0,k=g.p.ta,m=k.qa,l=k.ra,o=k.Ra;if(a){c=new g.p(a);b={};for(var r=function(q){return q&&q.i&k.sa&&q.c==="/"},n=function(q){return q&&q.i&m&&q.c==="fill"},p=function(){f=c.pa(function(q){return!(q.i&
(l|o))});if(n(c.next())&&!b.fill)b.fill=true;else c.w();if(r(c.next())){h++;i=c.pa(function(q){return!q.S()&&!(q.i&m&&q.c==="auto")});if(r(c.next())){h++;j=c.pa(function(q){return!q.Ba()})}}else c.w()};a=c.next();){e=a.i;d=a.c;if(e&(l|o)&&!f){c.w();p()}else if(n(a)&&!b.fill){b.fill=true;p()}else if(e&m&&this.cb[d]&&!b.repeat){b.repeat={d:d};if(a=c.next())if(a.i&m&&this.cb[a.c])b.repeat.qc=a.c;else c.w()}else if(e&k.URL&&!b.src)b.src=d;else return null}if(!b.src||!f||f.length<1||f.length>4||i&&i.length>
4||h===1&&i.length<1||j&&j.length>4||h===2&&j.length<1)return null;if(!b.repeat)b.repeat={d:"stretch"};if(!b.repeat.qc)b.repeat.qc=b.repeat.d;a=function(q,s){return{t:s(q[0]),r:s(q[1]||q[0]),b:s(q[2]||q[0]),l:s(q[3]||q[1]||q[0])}};b.slice=a(f,function(q){return g.k(q.i&l?q.c+"px":q.c)});if(i&&i[0])b.T=a(i,function(q){return q.S()?g.k(q.c):q.c});if(j&&j[0])b.Da=a(j,function(q){return q.Ba()?g.k(q.c):q.c})}return b}});g.Ac=g.u.ma({xa:"box-shadow",Ga:"boxShadow",na:function(a){var b,c=g.k,e=g.p.ta,d;
if(a){d=new g.p(a);b={Da:[],yb:[]};for(a=function(){for(var f,i,j,h,k,m;f=d.next();){j=f.c;i=f.i;if(i&e.sa&&j===",")break;else if(f.Ba()&&!k){d.w();k=d.pa(function(l){return!l.Ba()})}else if(i&e.q&&!h)h=j;else if(i&e.qa&&j==="inset"&&!m)m=true;else return false}f=k&&k.length;if(f>1&&f<5){(m?b.yb:b.Da).push({be:c(k[0].c),ce:c(k[1].c),blur:c(k[2]?k[2].c:"0"),Pd:c(k[3]?k[3].c:"0"),color:g.ia(h||"currentColor")});return true}return false};a(););}return b&&(b.yb.length||b.Da.length)?b:null}});g.Hc=g.u.ma({ja:g.u.wa(function(){var a=
this.e.currentStyle;return a.visibility+"|"+a.display}),na:function(){var a=this.e,b=a.runtimeStyle;a=a.currentStyle;var c=b.visibility,e;b.visibility="";e=a.visibility;b.visibility=c;return{$d:e!=="hidden",cd:a.display!=="none"}},h:function(){return false}});g.Ic=function(){function a(d){return function(){var f=arguments,i,j=f.length,h,k,m;h=this[c+d]||(this[c+d]={});for(i=0;i<j;i+=2)h[f[i]]=f[i+1];if(h=this.z()){if(d)h=h[d];for(i=0;i<j;i+=2){k=f[i];if(m=e[k])m.call(this,h,k,f[i+1]);else h[k]=f[i+
1]}}}}function b(d,f){this.Ub="_pie_"+(d||"shape")+g.C.Q(this);this.ab=f||0}var c="_attrs_",e={colors:function(d,f,i){if(d[f])d[f].value=i;else d[f]=i},size:function(d,f,i){if(i){d[f].x=1;d[f]=i}else delete d[f]},"o:opacity2":function(d,f,i){if(i!==this.yd){this.z().insertAdjacentHTML("afterEnd",this.sb());this.j();this.yd=i}}};(function d(){try{F.namespaces.add("pievml","urn:schemas-microsoft-com:vml","#default#VML")}catch(f){setTimeout(d,1)}})();b.prototype={Qb:"behavior:url(#default#VML);",Yc:"position:absolute;top:0px;left:0px;",
Xc:'coordorigin="1,1" stroked="false" ',tagName:"shape",ec:0,z:function(){return this.ec?this.Ob||(this.Ob=F.getElementById(this.Ub)):null},Y:a(""),Fa:a("style"),B:a("fill"),Kd:a("imagedata"),Ea:function(d,f){this.Fa("width",d+"px","height",f+"px");this.Y("coordsize",d*2+","+f*2)},rd:function(){var d=this[c+"style"]||{},f=[],i;for(i in d)d.hasOwnProperty(i)&&f.push(i+":"+d[i]);return this.Qb+this.Yc+f.join(";")},sb:function(){function d(l){if(l)for(var o in l)l.hasOwnProperty(o)&&i.push(" "+o+'="'+
l[o]+'"')}function f(l){var o=j[c+l];if(o){i.push(k+l);d(o);i.push(m)}}var i,j=this,h=j.tagName,k="<pievml:",m=' style="'+j.Qb+'" />';j.ec=1;i=[k,h,' id="',j.Ub,'" style="',j.rd(),'" ',j.Xc];d(j[c]);i.push(">");f("fill");f("imagedata");i.push("</pievml:"+h+">");return i.join("")},j:function(){var d=this.z(),f=d&&d.parentNode;if(f){f.removeChild(d);delete this.Ob}}};return b}();g.s={la:function(a){function b(c,e,d,f){this.e=c;this.o=e;this.g=d;this.parent=f}g.Ca(b.prototype,g.s,a);return b},dc:false,
W:function(){return false},jc:g.fd,oc:function(){this.h()?this.za():this.j()},Cb:function(){this.dc=true},wb:function(){this.e.runtimeStyle.borderColor="transparent"},j:function(){}};g.Ca(g.s,{z:function(a,b){var c=this.ob||(this.ob={}),e=c[a];if(!e){e=c[a]=new g.Ic(a,b);this.parent.jd(e)}return e},ya:function(a){var b=this.ob,c=b&&b[a];if(c){c.j();this.parent.Gd(c);delete b[a]}return!!c},qd:function(a){var b=this.e,c=this.o.n(),e=c.f,d=c.d,f,i,j,h,k,m;c=a.x.tl.a(b,e);f=a.y.tl.a(b,d);i=a.x.tr.a(b,
e);j=a.y.tr.a(b,d);h=a.x.br.a(b,e);k=a.y.br.a(b,d);m=a.x.bl.a(b,e);a=a.y.bl.a(b,d);e=Math.min(e/(c+i),d/(j+k),e/(m+h),d/(f+a));if(e<1){c*=e;f*=e;i*=e;j*=e;h*=e;k*=e;m*=e;a*=e}return{x:{tl:c,tr:i,br:h,bl:m},y:{tl:f,tr:j,br:k,bl:a}}},P:function(a,b,c,e,d,f){a=this.ha(a,b,c,e,d,f);return"m"+a[0]+","+a[1]+"qy"+a[2]+","+a[3]+"l"+a[4]+","+a[5]+"qx"+a[6]+","+a[7]+"l"+a[8]+","+a[9]+"qy"+a[10]+","+a[11]+"l"+a[12]+","+a[13]+"qx"+a[14]+","+a[15]+"x"},ha:function(a,b,c,e,d,f){var i=this.o.n(),j=i.f*d,h=i.d*d,
k=Math;i=k.floor;var m=k.ceil,l=k.max;k=k.min;a*=d;b*=d;c*=d;e*=d;f||(f=this.g.F.m());if(f){f=this.qd(f);var o=f.x.tl*d,r=f.y.tl*d,n=f.x.tr*d,p=f.y.tr*d,q=f.x.br*d,s=f.y.br*d,t=f.x.bl*d;d=f.y.bl*d;e=[i(e),i(k(l(r,a),h-c)),i(k(l(o,e),j-b)),i(a),m(l(e,j-l(n,b))),i(a),m(j-b),i(k(l(p,a),h-c)),m(j-b),m(l(a,h-l(s,c))),m(l(e,j-l(q,b))),m(h-c),i(k(l(t,e),j-b)),m(h-c),i(e),m(l(a,h-l(d,c)))]}else{a=i(a);b=m(j-b);c=m(h-c);e=i(e);e=[e,a,e,a,b,a,b,a,b,c,b,c,e,c,e,c]}return e},wb:function(){var a=this.e,b=a.currentStyle,
c=a.runtimeStyle,e=a.tagName,d=g.V===6,f;if(d&&(e in g.Sb||e==="FIELDSET")||e==="BUTTON"||e==="INPUT"&&a.type in g.xd){c.borderWidth="";e=this.g.v.lc;for(f=e.length;f--;){d=e[f];c["padding"+d]="";c["padding"+d]=g.k(b["padding"+d]).a(a)+g.k(b["border"+d+"Width"]).a(a)+(g.V!==8&&f%2?1:0)}c.borderWidth=0}else if(d){if(a.childNodes.length!==1||a.firstChild.tagName!=="ie6-mask"){b=F.createElement("ie6-mask");e=b.style;e.visibility="visible";for(e.zoom=1;e=a.firstChild;)b.appendChild(e);a.appendChild(b);
c.visibility="hidden"}}else c.borderColor="transparent"},je:function(){},j:function(){var a=this.ob,b;if(a)for(b in a)a.hasOwnProperty(b)&&this.ya(b)}});g.Fc=g.s.la({h:function(){var a=this.Sc;for(var b in a)if(a.hasOwnProperty(b)&&a[b].h())return true;return false},W:function(){return this.g.Db.G()},Cb:function(){if(this.h()&&this.pb()){var a=this.Zb(),b=a,c;a=a.currentStyle;var e=a.position,d=this.pb().style,f=0,i=0;i=this.o.n();if(e==="fixed"&&g.V>6){f=i.x;i=i.y;b=e}else{do b=b.offsetParent;while(b&&
b.currentStyle.position==="static");if(b){c=b.getBoundingClientRect();b=b.currentStyle;f=i.x-c.left-(parseFloat(b.borderLeftWidth)||0);i=i.y-c.top-(parseFloat(b.borderTopWidth)||0)}else{b=F.documentElement;f=i.x+b.scrollLeft-b.clientLeft;i=i.y+b.scrollTop-b.clientTop}b="absolute"}d.position=b;d.left=f;d.top=i;d.zIndex=e==="static"?-1:a.zIndex;this.dc=true}},Zd:function(){var a=this.g.Db,b=this.Ta;if(b&&a.G()){a=a.m();b.style.display=a.$d&&a.cd?"":"none"}},oc:function(){this.h()?this.Zd():this.j()},
Zb:function(){var a=this.e;return a.tagName in g.nc?a.offsetParent:a},pb:function(){var a=this.Ta;if(!a)a=this.Ta=F.getElementById("_pie"+g.C.Q(this));return a},kd:function(){var a=this.nb,b,c,e,d,f,i;if(a){if(b=this.mb){c=0;for(e=a.length;c<e;c++){for(d=b.length;d--;)if(b[d].ab<a[c].ab)break;if(d<0){f=this.pb();i="afterBegin"}else{f=b[d].z();i="afterEnd"}f.insertAdjacentHTML(i,a[c].sb());b.splice(d<0?0:d,0,a[c])}}else{a.sort(this.Ld);b=['<css3pie id="_pie'+g.C.Q(this)+'" style="direction:ltr;position:absolute;">'];
c=0;for(e=a.length;c<e;c++)b.push(a[c].sb());b.push("</css3pie>");this.Zb().insertAdjacentHTML("beforeBegin",b.join(""));this.Cb();this.mb=a}delete this.nb}},Ld:function(a,b){return a.ab-b.ab},jd:function(a){(this.nb||(this.nb=[])).push(a)},Gd:function(a){var b=this.mb,c;if(b)for(c=b.length;c--;)if(b[c]===a){b.splice(c,1);break}},j:function(){var a=this.Ta,b;if(a&&(b=a.parentNode))b.removeChild(a);delete this.Ta;delete this.mb}});F.createElement("css3pie");g.wc=g.s.la({H:2,W:function(){var a=this.g;
return a.K.G()||a.F.G()},h:function(){var a=this.g;return a.D.h()||a.F.h()||a.K.h()||a.fa.h()&&a.fa.m().yb},za:function(){var a=this.o.n();if(a.f&&a.d){this.dd();this.ed()}},dd:function(){var a=this.g.K.m(),b=this.o.n(),c=this.e,e=a&&a.color;if(e&&e.da()>0){this.$b();a=this.z("bgColor",this.H);a.Ea(b.f,b.d);a.Y("path",this.P(0,0,0,0,2));a.B("color",e.ga(c));b=e.da();b<1&&a.B("opacity",b)}else this.ya("bgColor")},ed:function(){var a=this.g.K.m(),b=this.o.n();a=a&&a.N;var c,e,d,f;if(a){this.$b();e=
b.f;d=b.d;for(f=a.length;f--;){b=a[f];c=this.z("bgImage"+f,this.H+(0.5-f/1E3));c.Y("path",this.P(0,0,0,0,2));c.Ea(e,d);if(b.R==="linear-gradient")this.Pc(c,b);else{c.B("type","tile","color","none");this.Dd(c,b.xb,f)}}}for(f=a?a.length:0;this.ya("bgImage"+f++););},Dd:function(a,b,c){g.C.tc(b,function(e){var d=this.e,f=this.o.n(),i=f.f;f=f.d;if(i&&f){var j=this.g.K,h=j.m().N[c],k=j.ld(h.Wa,this.o,this.g.v);j=(h.Xa||g.La.Cc).a(this.e,k.f,k.d,e.f,e.d);var m=this.md(h.Wa);d=h.ea?h.ea.coords(d,k.f-j.f,
k.d-j.d):{x:0,y:0};h=h.Za;var l=0,o=0,r=i+1,n=f+1,p=g.V===8?0:1;k=Math.round(m.x+d.x)+0.5;m=Math.round(m.y+d.y)+0.5;a.B("src",b,"position",k/i+","+m/f,"size",j.f!==e.f||j.d!==e.d||screen.logicalXDPI/screen.deviceXDPI!==1?g.Kb.kc(j.f)+"pt,"+g.Kb.kc(j.d)+"pt":"");if(h&&h!=="repeat"){if(h==="repeat-x"||h==="no-repeat"){l=m+1;n=m+j.d+p}if(h==="repeat-y"||h==="no-repeat"){o=k+1;r=k+j.f+p}a.Fa("clip","rect("+l+"px,"+r+"px,"+n+"px,"+o+"px)")}}},this)},md:function(a){var b=this.e,c=0,e=0,d;if(a!=="border-box")if((d=
this.g.v.m())&&(d=d.T)){c+=d.l.a(b);e+=d.t.a(b)}if(a==="content-box"){a=g.k;d=b.currentStyle;c+=a(d.paddingLeft).a(b);e+=a(d.paddingTop).a(b)}return{x:c,y:e}},Pc:function(a,b){var c=this.e,e=this.o.n(),d=e.f,f=e.d;e=b.oa;var i=e.length,j=Math.PI,h=g.gb,k=h.ic,m=h.Tb;b=h.od(c,d,f,b);h=b.ua;var l=b.Sd,o=b.Td,r=b.Qd,n=b.Rd,p=b.gd,q=b.hd,s=b.$c,t=b.ad;b=b.zd;d=h%90?Math.atan2(s*d/f,t)/j*180:h+90;d+=180;d%=360;p=k(r,n,h,p,q);f=m(r,n,p[0],p[1]);j=[];p=k(l,o,h,r,n);m=m(l,o,p[0],p[1])/f*100;k=[];for(h=0;h<
i;h++)k.push(e[h].fc?e[h].fc.a(c,b):h===0?0:h===i-1?b:null);for(h=1;h<i;h++){if(k[h]===null){l=k[h-1];b=h;do o=k[++b];while(o===null);k[h]=l+(o-l)/(b-h+1)}k[h]=Math.max(k[h],k[h-1])}for(h=0;h<i;h++)j.push(m+k[h]/f*100+"% "+e[h].color.ga(c));a.B("angle",d,"type","gradient","method","sigma","color",e[0].color.ga(c),"color2",e[i-1].color.ga(c),"colors",j.join(","));i===2&&a.B("opacity",e[0].color.da(),"o:opacity2",e[1].color.da())},$b:function(){var a=this.e.runtimeStyle;a.backgroundImage="url(about:blank)";
a.backgroundColor="transparent"},j:function(){g.s.j.call(this);var a=this.e.runtimeStyle;a.backgroundImage=a.backgroundColor=""}});g.yc=g.s.la({H:4,Md:{t:[2,1,0,3,4,7,6,5,90],r:[4,7,6,5,10,9,8,11,0],b:[10,9,8,11,12,15,14,13,270],l:[12,15,14,13,2,1,0,3,180]},Wc:{dotted:1,dashed:1},W:function(){var a=this.g;return a.v.G()||a.F.G()},h:function(){var a=this.g;return a.F.h()&&!a.D.h()&&a.v.h()},za:function(){var a=this.e,b=this.g.v.m(),c=this.o.n(),e,d,f;if(b){this.wb();e=this.nd();d=0;for(f=e.length;d<
f;d+=2){b=this.z("border"+d,this.H);b.Ea(c.f,c.d);b.Y("path",e[d]);b.B("color",e[d+1].ga(a))}for(;this.ya("border"+d++););}},O:function(a,b,c,e,d,f,i){i=e*(i==="dashed"?3:1);e=d+e;var j;if(i<c-b)for(b+=(c-b-i)/2%i;b<c;){j=Math.min(b+i,c);a.push(f?"m"+d+","+b+"l"+d+","+j+"l"+e+","+j+"l"+e+","+b+"x":"m"+b+","+d+"l"+j+","+d+"l"+j+","+e+"l"+b+","+e+"x");b+=i*2}},nd:function(){var a=this.g.v,b=[];if(a.h()){var c=this.e,e=this.o.n(),d=a.m(),f=d.T;a=d.Vd;var i=d.Uc,j=Math,h=j.abs,k=j.round;j=k(f.t.a(c));
var m=k(f.r.a(c)),l=k(f.b.a(c));c=k(f.l.a(c));f=[];var o,r,n;k=this.Md;var p,q=this.Wc,s;if(d.Wd&&d.Vc){if(i.t.da()>0){f[0]=this.P(0,0,0,0,2);s=a.t;if(s==="double")f.push(this.P(j/3,m/3,l/3,c/3,2)+this.P(j*2/3,m*2/3,l*2/3,c*2/3,2));else if(s in q){d=this.ha(j,m,l,c,2);this.O(f,d[2],d[4],j*2,0,0,a.t);this.O(f,d[7],d[9],m*2,(e.f-m)*2,1,a.r);this.O(f,d[12],d[10],l*2,(e.d-l)*2,0,a.b);this.O(f,d[1],d[15],c*2,0,1,a.l)}f.push(this.P(j,m,l,c,2));b.push(f.join(""),i.t)}}else{o=this.ha(0,0,0,0,2);d=this.ha(j,
m,l,c,2);for(p in k)if(k.hasOwnProperty(p)){s=k[p];var t=s[0],u=s[1],E=s[2],A=s[3],x=s[4],B=s[5],I=s[6],M=s[7],w=s[8];s=a[p];f[0]="al"+o[t]+","+o[u]+","+h(o[E]-o[t])+","+h(o[A]-o[u])+","+(w+45)*65535+",-2949075ae"+o[x]+","+o[B]+","+h(o[I]-o[x])+","+h(o[M]-o[B])+","+w*65535+",-2949075";if(s==="double"){if(!r){r=this.ha(j/3,m/3,l/3,c/3,2);n=this.ha(j*2/3,m*2/3,l*2/3,c*2/3,2)}f.push("ae"+r[x]+","+r[B]+","+h(r[I]-r[x])+","+h(r[M]-r[B])+","+(w-45)*65535+",2949075ae"+r[t]+","+r[u]+","+h(r[E]-r[t])+","+
h(r[A]-r[u])+","+w*65535+",2949075xal"+n[t]+","+n[u]+","+h(n[E]-n[t])+","+h(n[A]-n[u])+","+(w+45)*65535+",-2949075ae"+n[x]+","+n[B]+","+h(n[I]-n[x])+","+h(n[M]-n[B])+","+w*65535+",-2949075")}f.push("ae"+d[x]+","+d[B]+","+h(d[I]-d[x])+","+h(d[M]-d[B])+","+(w-45)*65535+",2949075ae"+d[t]+","+d[u]+","+h(d[E]-d[t])+","+h(d[A]-d[u])+","+w*65535+",2949075x");if(s in q)p==="t"?this.O(f,d[2],d[4],j*2,0,0,s):p==="r"?this.O(f,d[7],d[9],m*2,(e.f-m)*2,1,s):p==="b"?this.O(f,d[12],d[10],l*2,(e.d-l)*2,0,s):this.O(f,
d[1],d[15],c*2,0,1,s);b.push(f.join(""),i[p]);f.length=0}}}return b},j:function(){if(this.Vb||!this.g.D.h())this.e.runtimeStyle.borderColor="";g.s.j.call(this)}});g.xc=g.s.la({H:5,W:function(){return this.g.D.G()},h:function(){return this.g.D.h()},za:function(){var a=this,b=a.g.D.m(),c=a.g.v.m(),e=a.o.n(),d=a.e;g.C.tc(b.src,function(f){function i(t,u,E,A,x){var B=Math.max;a.tb(t).Fa("width",B(u,0)+"px","height",B(E,0)+"px","left",A+"px","top",x+"px")}function j(t,u,E){for(var A=b.src,x=0,B=t.length;x<
B;x++)a.tb(t[x]).Kd("src",A,u,E)}var h=e.f,k=e.d,m=g.k("0"),l=b.T||(c?c.T:{t:m,r:m,b:m,l:m});m=l.t.a(d);var o=l.r.a(d),r=l.b.a(d);l=l.l.a(d);var n=b.slice,p=n.t.a(d),q=n.r.a(d),s=n.b.a(d);n=n.l.a(d);i("tl",l,m,0,0);i("t",h-l-o,m,l,0);i("tr",o,m,h-o,0);i("r",o,k-m-r,h-o,m);i("br",o,r,h-o,k-r);i("b",h-l-o,r,l,k-r);i("bl",l,r,0,k-r);i("l",l,k-m-r,0,m);i("c",h-l-o,k-m-r,l,m);j(["tl","t","tr"],"cropBottom",(f.d-p)/f.d);j(["tl","l","bl"],"cropRight",(f.f-n)/f.f);j(["bl","b","br"],"cropTop",(f.d-s)/f.d);
j(["tr","r","br"],"cropLeft",(f.f-q)/f.f);j(["l","r","c"],"cropTop",p/f.d);j(["l","r","c"],"cropBottom",s/f.d);j(["t","b","c"],"cropLeft",n/f.f);j(["t","b","c"],"cropRight",q/f.f);a.tb("c").Fa("display",b.fill?"":"none")},a)},tb:function(a){a=this.z("borderImage"+a,this.H);a.tagName="rect";a.Y("filled",false);return a},jc:function(){if(this.h()){var a=this.e,b=a.runtimeStyle,c=this.g.D.m().T;b.borderStyle="solid";if(c){b.borderTopWidth=c.t.a(a);b.borderRightWidth=c.r.a(a);b.borderBottomWidth=c.b.a(a);
b.borderLeftWidth=c.l.a(a)}this.wb()}},j:function(){var a=this.e.runtimeStyle;a.borderStyle="";if(this.Vb||!this.g.v.h())a.borderColor=a.borderWidth="";g.s.j.call(this)}});g.zc=g.s.la({H:1,W:function(){var a=this.g;return a.fa.G()||a.F.G()},h:function(){var a=this.g.fa;return a.h()&&a.m().Da[0]},za:function(){var a=this.e,b=this.g,c=b.fa.m().Da;b=b.F.m();var e=c.length,d=e,f=this.o.n(),i=f.f;f=f.d;for(var j,h,k,m,l,o,r,n,p,q;d--;){j=c[d];k=j.be.a(a);m=j.ce.a(a);l=j.Pd.a(a);o=j.blur.a(a);j=j.color;
r=j.da();j=j.ga(a);h=-l-o;if(!b&&o)b=g.eb.uc;n=this.P(h,h,h,h,2,b);h=this.z("shadow"+d,this.H+(0.5-d/1E3));if(o){p=(l+o)*2+i;q=(l+o)*2+f;l=o*2/p;o=o*2/q;if(l>0.5||o>0.5){p=0.5/Math.max(l,o);l*=p;o*=p;r*=p*p}h.B("type","gradienttitle","color2",j,"focusposition",l+","+o,"focussize",1-l*2+","+(1-o*2),"opacity",0,"o:opacity2",r)}else h.B("type","solid","opacity",r);h.Y("path",n);h.B("color",j);h.Fa("left",k+"px","top",m+"px");h.Ea(i,f)}for(;this.ya("shadow"+e++););}});g.Ec=g.s.la({H:6,W:function(){var a=
this.g;return this.e.src!==this.Kc||a.F.G()},h:function(){var a=this.g;return a.F.h()||a.K.cc()},za:function(){this.Kc=f;this.vd();var a=this.z("img",this.H),b=this.o.n(),c=b.f;b=b.d;var e=this.g.v.m(),d=e&&e.T;e=this.e;var f=e.src,i=Math.round,j=e.currentStyle,h=g.k;if(!d||g.V<7){d=g.k("0");d={t:d,r:d,b:d,l:d}}a.Y("path",this.P(i(d.t.a(e)+h(j.paddingTop).a(e)),i(d.r.a(e)+h(j.paddingRight).a(e)),i(d.b.a(e)+h(j.paddingBottom).a(e)),i(d.l.a(e)+h(j.paddingLeft).a(e)),2));a.B("type","frame","src",f,"position",
(c?0.5/c:0)+","+(b?0.5/b:0));a.Ea(c,b)},vd:function(){this.e.runtimeStyle.filter="alpha(opacity=0)"},j:function(){g.s.j.call(this);this.e.runtimeStyle.filter=""}});g.fb=function(){function a(n,p){n.className+=" "+p}function b(n){var p=r.slice.call(arguments,1),q=p.length;setTimeout(function(){for(;q--;)a(n,p[q])},0)}function c(n){var p=r.slice.call(arguments,1),q=p.length;setTimeout(function(){for(;q--;){var s=p[q];s=o[s]||(o[s]=new RegExp("\\b"+s+"\\b","g"));n.className=n.className.replace(s,"")}},
0)}function e(n){function p(){if(!T){var v,y,z=g.ka,K=n.currentStyle,G=K.getAttribute(f)==="true";P=K.getAttribute(i);P=z>7?P!=="false":P==="true";if(!Q){Q=1;n.runtimeStyle.zoom=1;K=n;for(var W=1;K=K.previousSibling;)if(K.nodeType===1){W=0;break}W&&a(n,m)}D.$a();if(G&&(y=D.n())&&(v=F.documentElement||F.body)&&(y.y>v.clientHeight||y.x>v.clientWidth||y.y+y.d<0||y.x+y.f<0)){if(!U){U=1;g.ib.X(p)}}else{T=1;U=Q=0;g.ib.Ia(p);if(z===9){C={K:new g.Eb(n),D:new g.Fb(n),v:new g.Gb(n)};O=[C.K,C.D];H=new g.fe(n,
D,C);v=[new g.de(n,D,C,H),new g.ee(n,D,C,H)]}else{C={K:new g.Eb(n),v:new g.Gb(n),D:new g.Fb(n),F:new g.eb(n),fa:new g.Ac(n),Db:new g.Hc(n)};O=[C.K,C.v,C.D,C.F,C.fa,C.Db];H=new g.Fc(n,D,C);v=[new g.zc(n,D,C,H),new g.wc(n,D,C,H),new g.yc(n,D,C,H),new g.xc(n,D,C,H)];n.tagName==="IMG"&&v.push(new g.Ec(n,D,C,H));H.Sc=v}J=[H].concat(v);if(v=n.currentStyle.getAttribute(g.L+"watch-ancestors")){v=parseInt(v,10);y=0;for(G=n.parentNode;G&&(v==="NaN"||y++<v);){w(G,"onpropertychange",M);w(G,"onmouseenter",u);
w(G,"onmouseleave",E);w(G,"onmousedown",A);if(G.tagName in g.Wb){w(G,"onfocus",B);w(G,"onblur",I)}G=G.parentNode}}if(P){g.Oa.X(s);g.Oa.Id()}s(0,1)}if(!R){R=1;z<9&&w(n,"onmove",q);w(n,"onresize",q);w(n,"onpropertychange",t);w(n,"onmouseenter",u);w(n,"onmouseleave",E);w(n,"onmousedown",A);if(n.tagName in g.Wb){w(n,"onfocus",B);w(n,"onblur",I)}g.Qa.X(q);g.J.X(N)}D.db()}}function q(){D&&D.td()&&s()}function s(v,y){if(!V)if(T){D.$a();for(var z=O.length;z--;)O[z].$a();var K=J.length,G=D.Nd();for(z=0;z<
K;z++)J[z].jc();if(y||D.Ed())for(z=0;z<K;z++)J[z].Cb();for(z=0;z<K;z++)if(y||G||v&&J[z].W())J[z].oc();H.kd();for(v=O.length;v--;)O[v].db();D.db()}else Q||p()}function t(){var v=event;v&&v.propertyName in l||s(1)}function u(){b(n,j)}function E(){c(n,j,h)}function A(){b(n,h);g.hb.X(x)}function x(){c(n,h);g.hb.Ia(x)}function B(){b(n,k)}function I(){c(n,k)}function M(){var v=event.propertyName;if(v==="className"||v==="id")t()}function w(v,y,z){v.attachEvent(y,z);S.push([v,y,z])}function N(){if(R){for(var v=
S.length,y;v--;){y=S[v];y[0].detachEvent(y[1],y[2])}g.J.Ia(N);R=0;S=[]}}function X(){if(!V){var v,y;N();V=1;if(J){v=0;for(y=J.length;v<y;v++){J[v].Vb=1;J[v].j()}}P&&g.Oa.Ia(s);g.Qa.Ia(s);J=D=C=O=n=null}}var J,H,D=new g.Hb(n),C,O,Q,T,R,S=[],U,V,P;this.wd=p;this.j=X}var d={},f=g.L+"lazy-init",i=g.L+"poll",j=g.Ma+"hover",h=g.Ma+"active",k=g.Ma+"focus",m=g.Ma+"first-child",l={background:1,bgColor:1,display:1},o={},r=[];e.pd=function(n){var p=g.C.Q(n);return d[p]||(d[p]=new e(n))};e.j=function(n){n=g.C.Q(n);
var p=d[n];if(p){p.j();delete d[n]}};e.bd=function(){var n=[],p;if(d){for(var q in d)if(d.hasOwnProperty(q)){p=d[q];n.push(p.ge);p.j()}d={}}return n};return e}();g.version="1.0beta6-SNAPSHOT";g.supportsVML=g.mc;g.attach=function(a){if(g.ka===9||g.ka<9&&g.mc)g.fb.pd(a).wd()};g.detach=function(a){g.fb.j(a)}})(window,document);
